## Demo's the shield-llc recovering the F16 from stall failure during the level flight maneuver
# System Name
name = "f16-shield"

# directory to output ROSmsg codecs
codec_dir = "codec"

# directory to send CSAF output
output_dir = "output"

# Order to Construct/Evaluate Components
evaluation_order = ["autopilot", "cperf", "crecov", "shield_llc", "plant"]

# File to Log Results
log_file = "f16run.log"

# Log Level (info/debug)
log_level = "info"

[components]

  # Performance controller (substitute for LEC)
  [components.cperf]
    run_command = "python3"
    process = "f16llc.py"
    config = './components/llc_lqr_c1.toml'
    debug = false
    sub = [["plant", "states"], ["plant", "outputs"], ["autopilot", "outputs"]]
    pub = 5520

  # Recovery Controller with formal guarantees
  [components.crecov]
    run_command = "python3"
    process = "f16llc.py"
    config = './components/llc_lqr_c13_tuned.toml'
    debug = false
    sub = [["plant", "states"], ["plant", "outputs"], ["autopilot", "outputs"]]
    pub = 5530

  [components.plant]
    run_command = "python3"
    process = "f16plant.py"
    config = "./components/plant_stall.toml"
    debug = false
    sub = [["shield_llc", "outputs"]]
    pub = 5501

  [components.autopilot]
    run_command = "python3"
    process = "autopilot0.py"
    debug = false
    sub = [["plant", "states"], ["plant", "outputs"]]
    pub = 5503

  [components.shield_llc]
    run_command = "python3"
    process = "shield_llc.py"
    debug = false
    sub = [["plant", "states"], ["cperf", "outputs"], ["crecov", "outputs"]]
    pub = 5507
