# System Name
name = "f16-heidlauf"

# directory to output ROSmsg codecs
codec_dir = "codec"

# directory to send CSAF output
output_dir = "output"

# Order to Construct/Evaluate Components
evaluation_order = ["controller", "plant", "autopilot"]

# File to Log Results
log_file = "f16run.log"

# Log Level (info/debug)
log_level = "info"

# component components
[components]

  [components.controller]
    # environment to run under
    run_command = "python3"

    # path to model executable
    process = "f16llc.py"

    # whether to print debug diagnostics
    debug = false

    # subscribe to topic of a component (component name, topic name)
    sub = [["plant", "states"], ["plant", "outputs"], ["autopilot", "outputs"]]

    # port to publish
    pub = 5502

  [components.plant]
    # environment to run under
    run_command = "python3"

    # path to model executable
    process = "f16plant.py"

    # whether to print debug diagnostics
    debug = false

    # subscribe to topic of a component (component name, topic name)
    sub = [["controller", "outputs"]]

    # method to transport the messages
    transport = "ipc"

    # port to publish
    pub = 5501

  [components.autopilot]
    # environment to run under
    run_command = "python3"

    # path to model executable
    process = "autopilot.py"

    # whether to print debug diagnostics
    debug = false

    # subscribe to topic of a component (component name, topic name)
    sub = [["plant", "states"], ["plant", "outputs"]]

    # port to publish
    pub = 5503
