# Simple job configuration file

# simulation options
tspan = [0.0, 10.0]
show_status = true # show progress during simulation
plot = true # plot results on screen

initial_conditions = [  540.0, # vt [ft/s]
                        0.037027160081059704, # alpha [rad]
                        0.0, # beta [rad]
                        0.1, # phi [rad]
                        -0.1, # theta [rad]
                        -0.1, # psi [rad]
                        0.0, # p [rad/s]
                        0.0, # q [rad/s]
                        0.0, # r [rad/s]
                        0.0, # pn [m]
                        0.0, # pe [m]
                        4800.0, # h [ft]
                        90.0] # power [%]

# Use parallel runner
parallel = true

# [random, fixed, from_file]
x0 = "fixed"
bounds = [    [200.0, 1000.0, 100.0], # vt [ft/s]
              [0.026692982, 0.047745614, 0.01], # alpha [rad]
              [0.0], # beta [rad]
              [0.0], # phi [rad]
              [0.0], # theta [rad]
              [0.0], # psi [rad]
              [0.0], # p [rad/s]
              [0.0], # q [rad/s]
              [0.0], # r [rad/s]
              [0.0], # pn [m]
              [0.0], # pe [m]
              [500.0], # h [ft]
              [9.0]] # power [%]

# predefined terminating condition from a library
terminating_conditions = "ground_collision"

# [true|false]
x0_save_to_file = true

# Static tests to run
[tests]

# Tests
[tests.overshoot_Nz]
    test_type = "StaticRunTest"
    [tests.overshoot_Nz.parameters]
        # "global" test parameters
        fcn_name = "max_norm_deviation"
        # This is silly, but TOML requires arrays to contain only one type
        reference = ['autopilot','0']
        response = ['plant', '0']
        # Test specific generator config

        [tests.overshoot_Nz.parameters.generator_config]
            output_idx = 0

[tests.overshoot_Ny]
    test_type = "StaticRunTest"
    [tests.overshoot_Ny.parameters]
        # "global" test parameters
        fcn_name = "max_norm_deviation"
        # This is silly, but TOML requires arrays to contain only one type
        reference = ['autopilot','1']
        response = ['plant', '1']
        # Test specific generator config

        [tests.overshoot_Ny.parameters.generator_config]
        output_idx = 1

[tests.falsify_gcas]
    test_type = "BayesianFalsifierTest"
    [tests.falsify_gcas.parameters]
        # number of calls for the attack function
        n_calls = 20
