# System Name
name = "f16-ma-central-acas"

# directory to output ROSmsg codecs
codec_dir = "codec"

# directory to send CSAF output
output_dir = "output"

# Order to Construct/Evaluate Components
evaluation_order = ["autopilot", "controllera", "controllerb", "planta", "plantb"]

# File to Log Results
log_file = "f16run.log"

# Log Level (info/debug)
log_level = "info"

# component components
[components]

  [components.controllera]
      # environment to run under
      run_command = "python3"
      # path to model executable
      process = "f16llc.py"
      # whether to print debug diagnostics
      debug = false
      # subscribe to topic of a component (component name, topic name)
      sub = [["planta", "states"], ["planta", "outputs"], ["autopilot", "outputsa"]]
      # port to publish
      pub = 5502

  [components.planta]
      # environment to run under
      run_command = "python3"
      # path to model executable
      process = "f16plant.py"
      # whether to print debug diagnostics
      debug = false
      # subscribe to topic of a component (component name, topic name)
      sub = [["controllera", "outputs"]]
      # port to publish
      pub = 5501

    [components.controllerb]
        # environment to run under
        run_command = "python3"
        # path to model executable
        process = "f16llc.py"
        # whether to print debug diagnostics
        debug = false
        # subscribe to topic of a component (component name, topic name)
        sub = [["plantb", "states"], ["plantb", "outputs"], ["autopilot", "outputsb"]]
        # port to publish
        pub = 5504

    [components.plantb]
        # environment to run under
        run_command = "python3"
        # path to model executable
        process = "f16plant.py"
        # whether to print debug diagnostics
        debug = false
        # subscribe to topic of a component (component name, topic name)
        sub = [["controllerb", "outputs"]]
        # port to publish
        pub = 5505

    [components.autopilot]
        # environment to run under
        run_command = "python3"
        # path to model executable
        process = "ma_central.py"
        # whether to print debug diagnostics
        debug = false
        # subscribe to topic of a component (component name, topic name)
        sub = [["planta", "states"], ["controllera", "states"], ["plantb", "states"], ["controllerb", "states"]]
        # port to publish
        pub = 5503
