# System Name
name = "f16-acas"

# directory to output ROSmsg codecs
codec_dir = "codec"

# directory to send CSAF output
output_dir = "output"

# Order to Construct/Evaluate Components
evaluation_order = ["autopilota", "autopilotb", "controllera", "controllerb", "planta", "plantb"]

# File to Log Results
log_file = "f16run.log"

# Log Level (info/debug)
log_level = "info"

# component components
[components]

  [components.controllera]
      # environment to run under
      run_command = "python3"
      # path to model executable
      process = "f16llc.py"
      # whether to print debug diagnostics
      debug = false
      # subscribe to topic of a component (component name, topic name)
      sub = [["planta", "states"], ["planta", "outputs"], ["autopilota", "outputs"]]
      # port to publish
      pub = 5502

  [components.planta]
      # environment to run under
      run_command = "python3"
      # path to model executable
      process = "f16plant.py"
      # whether to print debug diagnostics
      debug = false
      # subscribe to topic of a component (component name, topic name)
      sub = [["controllera", "outputs"]]
      # port to publish
      pub = 5501

  [components.autopilota]
      # environment to run under
      run_command = "python3"
      # path to model executable
      process = "ma_acas.py"
      # whether to print debug diagnostics
      debug = false
      # subscribe to topic of a component (component name, topic name)
      sub = [["planta", "states"], ["planta", "outputs"], ["plantb", "states"], ["plantb", "outputs"]]
      # port to publish
      pub = 5503

    [components.controllerb]
        # environment to run under
        run_command = "python3"
        # path to model executable
        process = "f16llc.py"
        # whether to print debug diagnostics
        debug = false
        # subscribe to topic of a component (component name, topic name)
        sub = [["plantb", "states"], ["plantb", "outputs"], ["autopilotb", "outputs"]]
        # port to publish
        pub = 5504

    [components.plantb]
        # environment to run under
        run_command = "python3"
        # path to model executable
        process = "f16plant.py"
        # whether to print debug diagnostics
        debug = false
        # subscribe to topic of a component (component name, topic name)
        sub = [["controllerb", "outputs"]]
        # port to publish
        pub = 5505

    [components.autopilotb]
        # environment to run under
        run_command = "python3"
        # path to model executable
        process = "ma_acas.py"
        # whether to print debug diagnostics
        debug = false
        # subscribe to topic of a component (component name, topic name)
        sub = [["plantb", "states"], ["plantb", "outputs"], ["planta", "states"], ["planta", "outputs"]]
        # port to publish
        pub = 5506
