
name = "f16"


codec_dir = "codec"


output_dir = "output"


evaluation_order = ["controller", "plant", "autopilot"]


log_file = "f16run.log"


log_level = "info"


[components]
  [components.controller]
    run_command = "python3"
    process = "f16llc.py"
    debug = false
    sub = [["plant", "states"], ["plant", "outputs"], ["autopilot", "outputs"]]
    pub = 5502

  [components.plant]
    run_command = "python3"
    process = "f16plant.py"
    debug = false
    sub = [["controller", "outputs"]]
    pub = 5501

  [components.autopilot]
    run_command = "python3"
    process = "autopilot.py"
    debug = false
    sub = [["plant", "states"], ["plant", "outputs"]]
    pub = 5503
