C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitstat(setupfunc)
      external setupfunc
      integer nres
      integer ndec
      integer nrem
      integer nadd
      integer nit
      integer nfv
      integer nfg
      integer nfh
      common /stat/ nres,ndec,nrem,nadd,nit,nfv,nfg,nfh
      call setupfunc(nres,ndec,nrem,nadd,nit,nfv,nfg,nfh)
      end


