system_name = "Inverted Pendulum Controller"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 10

is_discrete = true
is_hybrid = false

[parameters]

[inputs]
  names = [['angular_rate', 'angular_acceleration', 'velocity', 'acceleration'],
            ['setpoint']]

[topics]
  [topics.outputs]
    msg = "./msg/ipcontroller_output.msg"
