system_name = "F16 Plant Model"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 100

is_discrete = false
is_hybrid = false

[parameters]

[inputs]
  msgs = [ "f16llc_output.msg" ]

[topics]

  [topics.outputs]
      msg = "f16plant_output.msg"

  [topics.states]
      msg = "f16plant_state.msg"
#       initial = [   540.0,
#                     0.037027160081059704,
#                     0.0,
#                     0.7853981633974483,
#                     -1.2566370614359172,
#                     -0.7853981633974483,
#                     0.0,
#                     0.0,
#                     0.0,
#                     0.0,
#                     0.0,
#                     3600.0,
#                     9.0]
      initial = [   540.0,
                    0.037027160081059704,
                    0.0,
                    0.7853981633974483,
                    -1.2566370614359172,
                    -0.7853981633974483,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    4800.0,
                    9.0]
