system_name = "F16 Low Level Controller"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 100

is_discrete = false
is_hybrid = false

[parameters]
  lqr_name = "lqr_original"

[inputs]
  msgs = [ "f16plant_state.msg", "f16plant_output.msg", "autopilot_output.msg" ]

[topics]

  [topics.outputs]
    msg = "f16llc_output.msg"

  [topics.states]
    msg = "f16llc_state.msg"
    initial = [ 0.0, 0.0, 0.0 ]
