system_name = "F16 Autopilot Monitor"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 30

is_discrete = true
is_hybrid = false

[parameters]

[inputs]
  msgs = ["f16plant_state.msg", "f16plant_output.msg", "autopilot_state.msg"]

[topics]
  [topics.outputs]
      msg = "monitor_output.msg"
