system_name = "F16 Fuzzy On-the-Fly-Control"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 100

is_discrete = false
is_hybrid = false

[parameters]
    sampling_frequency = 100
    lqr_name = "lqr_original"
    xequil = [502.0, 0.03887505597600522, 0.0, 0.0, 0.03887505597600522, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 1000.0, 9.05666543872074]
    uequil = [0.13946204864060271, -0.7495784725828754, 0.0, 0.0]
    throttle_max = 1
    throttle_min = 0
    elevator_max = 25
    elevator_min = -25
    aileron_max = 21.5
    aileron_min = -21.5
    rudder_max = 30.0
    rudder_min = -30.0

[inputs]
msgs = [ "f16plant_state.msg", "f16plant_output.msg", "autopilot_output.msg" ]

[topics]

[topics.outputs]
msg = "f16llc_output.msg"

[topics.states]
msg = "f16llc_state.msg"
initial = [ 0.0, 0.0, 0.0 ]
