system_name = "F16 Plant Model"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 100

is_discrete = false
is_hybrid = false

[parameters]
    s = 300.0
    b = 30.0
    cbar = 11.32
    rm = 1.57e-3
    xcgref = 0.35
    xcg = 0.35
    he = 160.0
    c1 = -0.770
    c2 = 0.02755
    c3 = 1.055e-4
    c4 = 1.642e-6
    c5 = 0.9604
    c6 = 1.759e-2
    c7 = 1.792e-5
    c8 = -0.7336
    c9 = 1.587e-5
    rtod = 57.29578
    g = 32.17
    xcg_mult = 1
    cxt_mult = 1
    cyt_mult = 1
    czt_mult = 1
    clt_mult = 1
    cmt_mult = 1
    cnt_mult = 1
    model = "stevens"

[inputs]
  msgs = [ "f16llc_output.msg" ]

[topics]

  [topics.outputs]
      msg = "f16plant_output.msg"

  [topics.states]
      msg = "f16plant_state.msg"
      initial = [   540.0,
                    0.037027160081059704,
                    0.0,
                    0.7853981633974483,
                    -1.2566370614359172,
                    -0.7853981633974483,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    0.0,
                    4800.0,
                    9.0]
