system_name = "Signal Generator"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 10

is_discrete = true
is_hybrid = false

[parameters]
  # step | impulse | sin
  response_type = "step"
  # Amplitude / size of the response
  response_amplitude = 1.0
  # When does the response start? Valid for impulse | step
  response_time = 1.0
  # zero-index the ouptut:
  # for F16 LLC it is: Nz, ps, Ny_r, throttle (based on autopilot_output.msg)
  output_idx = 0
  output_size = 4

[topics]
  [topics.outputs]
      msg = "autopilot_output.msg"
