system_name = "Autopilot Selector"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 10

is_discrete = true
is_hybrid = false

[parameters]
  mapper = ["gcas", "altitude", "airspeed"]

[inputs]
  msgs = ["autopilot_output.msg", "autopilot_output.msg", "autopilot_output.msg", "monitor_output.msg"]

[topics]
  [topics.outputs]
      msg = "autopilot_output.msg"
