image: galoisinc/csaf:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - export PYTHONPATH=${PYTHONPATH}:${PWD}/src:${PWD}/examples/f16:${PWD}/examples/inverted-pendulum:/csaf-system

f16-shield:
  script:
    - ./run-csaf.sh -e f16-shield -n
  artifacts:
    when: always
    expire_in: 1 week
    paths:
        - ./examples/f16/output/f16run.log
        - ./examples/f16/output/f16-shield-config.pdf
        - ./examples/f16/output/f16-shield-run.png


f16-simple:
  script:
    - ./run-csaf.sh -e f16-simple -n
  artifacts:
    when: always
    expire_in: 1 week
    paths:
        - ./examples/f16/output/f16run.log
        - ./examples/f16/output/f16-shield-config.pdf
        - ./examples/f16/output/f16-shield-run.png

inv-pendulum:
  script:
    - ./run-csaf.sh -e inv-pendulum -n
  artifacts:
    when: always
    expire_in: 1 week
    paths:
        - ./examples/inverted-pendulum/output/inv_pendulum.log
        - ./examples/inverted-pendulum/output/inverted-pendulum-config.pdf
        - ./examples/inverted-pendulum/output/inverted-pendulum-run.png

notebook:
  script:
    - echo "Adjust example paths to match jupyter notebook launch for f16-shield"
    - ln -s ${PWD}/examples/f16 /csaf-system
    - jupyter nbconvert --to pdf --execute  docs/notebooks/f16-shield.ipynb
    - rm /csaf-system
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - docs/notebooks/f16-shield.pdf
