image: galoisinc/csaf:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh

f16-shield:
  script:
    - ./run-example.sh -e f16-shield -n
  artifacts:
    when: always
    expire_in: 1 week
    paths:
        - ./examples/f16/output/f16run.log
        - ./examples/f16/output/f16-shield-heidlauf-config.pdf
        - ./examples/f16/output/f16-shield-heidlauf-run.png


f16-simple:
  script:
    - ./run-example.sh -e f16-simple -n
  artifacts:
    when: always
    expire_in: 1 week
    paths:
        - ./examples/f16/output/f16run.log
        - ./examples/f16/output/f16-shield-heidlauf-config.pdf
        - ./examples/f16/output/f16-shield-heidlauf-run.png

inv-pendulum:
  script:
    - ./run-example.sh -e inv-pendulum -n
  artifacts:
    when: always
    expire_in: 1 week
    paths:
        - ./examples/inverted-pendulum/output/inverted-pendulum.log
        - ./examples/inverted-pendulum/output/inverted-pendulum-config.pdf
        - ./examples/inverted-pendulum/output/inverted-pendulum-run.png

notebooks:
  script:
    - jupyter nbconvert --to pdf --execute  docs/notebooks/CSAF_Simulation.ipynb
  artifacts:
    when: always
    expire_in: 1 week
    paths:
      - docs/notebooks/CSAF_Simulation.pdf
