# System Name
name = "Inverted Pendulum PID"

# directory to output ROSmsg codecs
codec_dir = "codec"

# directory to send CSAF output
output_dir = "output"

# Order to Construct/Evaluate Components
evaluation_order = ["controller", "plant"]

# File to Log Results
log_file = "inv_pendulum_pid.log"

# Log Level (info/debug)
log_level = "info"

[components]

[components.controller]
# environment to run under
run_command = "python3"

# path to model executable
process = "pid_model.py"

# whether to print debug diagnostics
debug = false

# subscribe to topic of a component (component name, topic name)
sub = [["plant", "states"]]

# port to publish
pub = 5502

[components.plant]
# environment to run under
run_command = "python3"

# path to model executable
process = "ip_model.py"

# whether to print debug diagnostics
debug = false

# subscribe to topic of a component (component name, topic name)
sub = [["controller", "outputs"]]

# port to publish
pub = 5501

