C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitnum(setupfunc)
      external setupfunc
      real*8 f
      common /num/ f
      call setupfunc(f)
      end

      subroutine f2pyinitcalfamax(setupfunc)
      external setupfunc
      real*8 alfamax
      common /calfamax/ alfamax
      call setupfunc(alfamax)
      end


