/* File: solvoptmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Apr 11 17:22:54 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *solvopt_error;
static PyObject *solvopt_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_gradc_in_solvopt__user__routines_typedef)(int *,double *,double *);
typedef void(*cb_func_in_solvopt__user__routines_typedef)(int *,double *,double *);
typedef void(*cb_grad_in_solvopt__user__routines_typedef)(int *,double *,double *);
typedef void(*cb_fun_in_solvopt__user__routines_typedef)(int *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"solvopt.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(signed char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = solvopt_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
    TRYPYARRAYTEMPLATE(double,'d');
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = solvopt_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(solvopt_error,errmess);
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = solvopt_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(solvopt,SOLVOPT)(int*,double*,double*,cb_fun_in_solvopt__user__routines_typedef,int*,cb_grad_in_solvopt__user__routines_typedef,double*,int*,cb_func_in_solvopt__user__routines_typedef,int*,cb_gradc_in_solvopt__user__routines_typedef,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,string,size_t);
extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t);
extern void F_FUNC(pyflush,PYFLUSH)(int*);
extern void F_FUNC(closeunit,CLOSEUNIT)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************* cb_fun_in_solvopt__user__routines *********************/
PyObject *cb_fun_in_solvopt__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_fun_in_solvopt__user__routines_args_capi = NULL;
int cb_fun_in_solvopt__user__routines_nofargs = 0;
jmp_buf cb_fun_in_solvopt__user__routines_jmpbuf;
/*typedef void(*cb_fun_in_solvopt__user__routines_typedef)(int *,double *,double *);*/
static void cb_fun_in_solvopt__user__routines (int *n_cb_capi,double *x,double *f_cb_capi) {
  PyTupleObject *capi_arglist = cb_fun_in_solvopt__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n=(*n_cb_capi);
  double f=(*f_cb_capi);
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_fun_in_solvopt__user__routines (maxnofargs=3(-0))\n");
  CFUNCSMESSPY("cb:cb_fun_in_solvopt__user__routines_capi=",cb_fun_in_solvopt__user__routines_capi);
  if (cb_fun_in_solvopt__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_fun_in_solvopt__user__routines_capi = PyObject_GetAttrString(solvopt_module,"fun");
  }
  if (cb_fun_in_solvopt__user__routines_capi==NULL) {
    PyErr_SetString(solvopt_error,"cb: Callback fun not defined (as an argument or module solvopt attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_fun_in_solvopt__user__routines_capi)) {
  cb_fun_in_solvopt__user__routines_typedef cb_fun_in_solvopt__user__routines_cptr;
  cb_fun_in_solvopt__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_fun_in_solvopt__user__routines_capi);
  (*cb_fun_in_solvopt__user__routines_cptr)(n_cb_capi,x,f_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(solvopt_module,"fun_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(solvopt_error,"Failed to convert solvopt.fun_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(solvopt_error,"Callback fun argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=n;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_fun_in_solvopt__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_fun_in_solvopt__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_fun_in_solvopt__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(f)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function fun.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_fun_in_solvopt__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_fun_in_solvopt__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,f_cb_capi,double,"double_from_pyobj failed in converting argument f of call-back function cb_fun_in_solvopt__user__routines to C double\n");
  CFUNCSMESS("cb:cb_fun_in_solvopt__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_fun_in_solvopt__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_fun_in_solvopt__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/****************** end of cb_fun_in_solvopt__user__routines ******************/


/********************* cb_grad_in_solvopt__user__routines *********************/
PyObject *cb_grad_in_solvopt__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_grad_in_solvopt__user__routines_args_capi = NULL;
int cb_grad_in_solvopt__user__routines_nofargs = 0;
jmp_buf cb_grad_in_solvopt__user__routines_jmpbuf;
/*typedef void(*cb_grad_in_solvopt__user__routines_typedef)(int *,double *,double *);*/
static void cb_grad_in_solvopt__user__routines (int *n_cb_capi,double *x,double *g) {
  PyTupleObject *capi_arglist = cb_grad_in_solvopt__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n=(*n_cb_capi);
  npy_intp x_Dims[1] = {-1};
  npy_intp g_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_grad_in_solvopt__user__routines (maxnofargs=3(-0))\n");
  CFUNCSMESSPY("cb:cb_grad_in_solvopt__user__routines_capi=",cb_grad_in_solvopt__user__routines_capi);
  if (cb_grad_in_solvopt__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_grad_in_solvopt__user__routines_capi = PyObject_GetAttrString(solvopt_module,"grad");
  }
  if (cb_grad_in_solvopt__user__routines_capi==NULL) {
    PyErr_SetString(solvopt_error,"cb: Callback grad not defined (as an argument or module solvopt attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_grad_in_solvopt__user__routines_capi)) {
  cb_grad_in_solvopt__user__routines_typedef cb_grad_in_solvopt__user__routines_cptr;
  cb_grad_in_solvopt__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_grad_in_solvopt__user__routines_capi);
  (*cb_grad_in_solvopt__user__routines_cptr)(n_cb_capi,x,g);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(solvopt_module,"grad_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(solvopt_error,"Failed to convert solvopt.grad_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(solvopt_error,"Callback grad argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=n;
  g_Dims[0]=n;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_grad_in_solvopt__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_grad_in_solvopt__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_grad_in_solvopt__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,g_Dims,NPY_DOUBLE,NULL,(char*)g,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function grad.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_grad_in_solvopt__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_grad_in_solvopt__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,g_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(g,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_grad_in_solvopt__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_grad_in_solvopt__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_grad_in_solvopt__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_grad_in_solvopt__user__routines *****************/


/********************* cb_func_in_solvopt__user__routines *********************/
PyObject *cb_func_in_solvopt__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_func_in_solvopt__user__routines_args_capi = NULL;
int cb_func_in_solvopt__user__routines_nofargs = 0;
jmp_buf cb_func_in_solvopt__user__routines_jmpbuf;
/*typedef void(*cb_func_in_solvopt__user__routines_typedef)(int *,double *,double *);*/
static void cb_func_in_solvopt__user__routines (int *n_cb_capi,double *x,double *fc_cb_capi) {
  PyTupleObject *capi_arglist = cb_func_in_solvopt__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n=(*n_cb_capi);
  double fc=(*fc_cb_capi);
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_func_in_solvopt__user__routines (maxnofargs=3(-0))\n");
  CFUNCSMESSPY("cb:cb_func_in_solvopt__user__routines_capi=",cb_func_in_solvopt__user__routines_capi);
  if (cb_func_in_solvopt__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_func_in_solvopt__user__routines_capi = PyObject_GetAttrString(solvopt_module,"func");
  }
  if (cb_func_in_solvopt__user__routines_capi==NULL) {
    PyErr_SetString(solvopt_error,"cb: Callback func not defined (as an argument or module solvopt attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_func_in_solvopt__user__routines_capi)) {
  cb_func_in_solvopt__user__routines_typedef cb_func_in_solvopt__user__routines_cptr;
  cb_func_in_solvopt__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_func_in_solvopt__user__routines_capi);
  (*cb_func_in_solvopt__user__routines_cptr)(n_cb_capi,x,fc_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(solvopt_module,"func_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(solvopt_error,"Failed to convert solvopt.func_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(solvopt_error,"Callback func argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=n;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_func_in_solvopt__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_func_in_solvopt__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_func_in_solvopt__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(fc)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function func.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_func_in_solvopt__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_func_in_solvopt__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,fc_cb_capi,double,"double_from_pyobj failed in converting argument fc of call-back function cb_func_in_solvopt__user__routines to C double\n");
  CFUNCSMESS("cb:cb_func_in_solvopt__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_func_in_solvopt__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_func_in_solvopt__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_func_in_solvopt__user__routines *****************/


/******************** cb_gradc_in_solvopt__user__routines ********************/
PyObject *cb_gradc_in_solvopt__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_gradc_in_solvopt__user__routines_args_capi = NULL;
int cb_gradc_in_solvopt__user__routines_nofargs = 0;
jmp_buf cb_gradc_in_solvopt__user__routines_jmpbuf;
/*typedef void(*cb_gradc_in_solvopt__user__routines_typedef)(int *,double *,double *);*/
static void cb_gradc_in_solvopt__user__routines (int *n_cb_capi,double *x,double *gc) {
  PyTupleObject *capi_arglist = cb_gradc_in_solvopt__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int n=(*n_cb_capi);
  npy_intp x_Dims[1] = {-1};
  npy_intp gc_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_gradc_in_solvopt__user__routines (maxnofargs=3(-0))\n");
  CFUNCSMESSPY("cb:cb_gradc_in_solvopt__user__routines_capi=",cb_gradc_in_solvopt__user__routines_capi);
  if (cb_gradc_in_solvopt__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_gradc_in_solvopt__user__routines_capi = PyObject_GetAttrString(solvopt_module,"gradc");
  }
  if (cb_gradc_in_solvopt__user__routines_capi==NULL) {
    PyErr_SetString(solvopt_error,"cb: Callback gradc not defined (as an argument or module solvopt attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_gradc_in_solvopt__user__routines_capi)) {
  cb_gradc_in_solvopt__user__routines_typedef cb_gradc_in_solvopt__user__routines_cptr;
  cb_gradc_in_solvopt__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_gradc_in_solvopt__user__routines_capi);
  (*cb_gradc_in_solvopt__user__routines_cptr)(n_cb_capi,x,gc);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(solvopt_module,"gradc_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(solvopt_error,"Failed to convert solvopt.gradc_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(solvopt_error,"Callback gradc argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=n;
  gc_Dims[0]=n;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_gradc_in_solvopt__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_gradc_in_solvopt__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_gradc_in_solvopt__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,gc_Dims,NPY_DOUBLE,NULL,(char*)gc,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function gradc.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_gradc_in_solvopt__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_gradc_in_solvopt__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,gc_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(gc,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_gradc_in_solvopt__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_gradc_in_solvopt__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_gradc_in_solvopt__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_gradc_in_solvopt__user__routines *****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/********************************** solvopt **********************************/
static char doc_f2py_rout_solvopt_solvopt[] = "\
x,options = solvopt(n,x,f,fun,flg,grad,options,flfc,func,flgc,gradc,b,g,g0,g1,gt,gc,z,x1,xopt,xrec,grec,xx,deltax,idx,iout,ifile,[fun_extra_args,grad_extra_args,func_extra_args,gradc_extra_args])\n\nWrapper for ``solvopt``.\
\n\nParameters\n----------\n"
"n : input int\n"
"x : input rank-1 array('d') with bounds (n)\n"
"f : in/output rank-0 array(float,'d')\n"
"fun : call-back function\n"
"flg : input int\n"
"grad : call-back function\n"
"options : input rank-1 array('d') with bounds (13)\n"
"flfc : input int\n"
"func : call-back function\n"
"flgc : input int\n"
"gradc : call-back function\n"
"b : input rank-2 array('d') with bounds (n,n)\n"
"g : input rank-1 array('d') with bounds (n)\n"
"g0 : input rank-1 array('d') with bounds (n)\n"
"g1 : input rank-1 array('d') with bounds (n)\n"
"gt : input rank-1 array('d') with bounds (n)\n"
"gc : input rank-1 array('d') with bounds (n)\n"
"z : input rank-1 array('d') with bounds (n)\n"
"x1 : input rank-1 array('d') with bounds (n)\n"
"xopt : input rank-1 array('d') with bounds (n)\n"
"xrec : input rank-1 array('d') with bounds (n)\n"
"grec : input rank-1 array('d') with bounds (n)\n"
"xx : input rank-1 array('d') with bounds (n)\n"
"deltax : input rank-1 array('d') with bounds (n)\n"
"idx : input rank-1 array('i') with bounds (n)\n"
"iout : input int\n"
"ifile : input string(len=-1)\n"
"\nOther Parameters\n----------------\n"
"fun_extra_args : input tuple, optional\n    Default: ()\n"
"grad_extra_args : input tuple, optional\n    Default: ()\n"
"func_extra_args : input tuple, optional\n    Default: ()\n"
"gradc_extra_args : input tuple, optional\n    Default: ()\n"
"\nReturns\n-------\n"
"x : rank-1 array('d') with bounds (n)\n"
"options : rank-1 array('d') with bounds (13)\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def fun(n,x,f): return f\n\
  Required arguments:\n"
"    n : input int\n"
"    x : input rank-1 array('d') with bounds (n)\n"
"    f : input float\n"
"  Return objects:\n"
"    f : float\n"
"  def grad(n,x,g): return g\n\
  Required arguments:\n"
"    n : input int\n"
"    x : input rank-1 array('d') with bounds (n)\n"
"    g : input rank-1 array('d') with bounds (n)\n"
"  Return objects:\n"
"    g : rank-1 array('d') with bounds (n)\n"
"  def func(n,x,fc): return fc\n\
  Required arguments:\n"
"    n : input int\n"
"    x : input rank-1 array('d') with bounds (n)\n"
"    fc : input float\n"
"  Return objects:\n"
"    fc : float\n"
"  def gradc(n,x,gc): return gc\n\
  Required arguments:\n"
"    n : input int\n"
"    x : input rank-1 array('d') with bounds (n)\n"
"    gc : input rank-1 array('d') with bounds (n)\n"
"  Return objects:\n"
"    gc : rank-1 array('d') with bounds (n)";
/* extern void F_FUNC(solvopt,SOLVOPT)(int*,double*,double*,cb_fun_in_solvopt__user__routines_typedef,int*,cb_grad_in_solvopt__user__routines_typedef,double*,int*,cb_func_in_solvopt__user__routines_typedef,int*,cb_gradc_in_solvopt__user__routines_typedef,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,string,size_t); */
static PyObject *f2py_rout_solvopt_solvopt(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,double*,double*,cb_fun_in_solvopt__user__routines_typedef,int*,cb_grad_in_solvopt__user__routines_typedef,double*,int*,cb_func_in_solvopt__user__routines_typedef,int*,cb_gradc_in_solvopt__user__routines_typedef,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int n = 0;
  PyObject *n_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double f = 0;
  PyObject *f_capi = Py_None;
  PyObject *fun_capi = Py_None;
  PyTupleObject *fun_xa_capi = NULL;
  PyTupleObject *fun_args_capi = NULL;
  int fun_nofargs_capi = 0;
  cb_fun_in_solvopt__user__routines_typedef fun_cptr;
  int flg = 0;
  PyObject *flg_capi = Py_None;
  PyObject *grad_capi = Py_None;
  PyTupleObject *grad_xa_capi = NULL;
  PyTupleObject *grad_args_capi = NULL;
  int grad_nofargs_capi = 0;
  cb_grad_in_solvopt__user__routines_typedef grad_cptr;
  double *options = NULL;
  npy_intp options_Dims[1] = {-1};
  const int options_Rank = 1;
  PyArrayObject *capi_options_tmp = NULL;
  int capi_options_intent = 0;
  PyObject *options_capi = Py_None;
  int flfc = 0;
  PyObject *flfc_capi = Py_None;
  PyObject *func_capi = Py_None;
  PyTupleObject *func_xa_capi = NULL;
  PyTupleObject *func_args_capi = NULL;
  int func_nofargs_capi = 0;
  cb_func_in_solvopt__user__routines_typedef func_cptr;
  int flgc = 0;
  PyObject *flgc_capi = Py_None;
  PyObject *gradc_capi = Py_None;
  PyTupleObject *gradc_xa_capi = NULL;
  PyTupleObject *gradc_args_capi = NULL;
  int gradc_nofargs_capi = 0;
  cb_gradc_in_solvopt__user__routines_typedef gradc_cptr;
  double *b = NULL;
  npy_intp b_Dims[2] = {-1, -1};
  const int b_Rank = 2;
  PyArrayObject *capi_b_tmp = NULL;
  int capi_b_intent = 0;
  PyObject *b_capi = Py_None;
  double *g = NULL;
  npy_intp g_Dims[1] = {-1};
  const int g_Rank = 1;
  PyArrayObject *capi_g_tmp = NULL;
  int capi_g_intent = 0;
  PyObject *g_capi = Py_None;
  double *g0 = NULL;
  npy_intp g0_Dims[1] = {-1};
  const int g0_Rank = 1;
  PyArrayObject *capi_g0_tmp = NULL;
  int capi_g0_intent = 0;
  PyObject *g0_capi = Py_None;
  double *g1 = NULL;
  npy_intp g1_Dims[1] = {-1};
  const int g1_Rank = 1;
  PyArrayObject *capi_g1_tmp = NULL;
  int capi_g1_intent = 0;
  PyObject *g1_capi = Py_None;
  double *gt = NULL;
  npy_intp gt_Dims[1] = {-1};
  const int gt_Rank = 1;
  PyArrayObject *capi_gt_tmp = NULL;
  int capi_gt_intent = 0;
  PyObject *gt_capi = Py_None;
  double *gc = NULL;
  npy_intp gc_Dims[1] = {-1};
  const int gc_Rank = 1;
  PyArrayObject *capi_gc_tmp = NULL;
  int capi_gc_intent = 0;
  PyObject *gc_capi = Py_None;
  double *z = NULL;
  npy_intp z_Dims[1] = {-1};
  const int z_Rank = 1;
  PyArrayObject *capi_z_tmp = NULL;
  int capi_z_intent = 0;
  PyObject *z_capi = Py_None;
  double *x1 = NULL;
  npy_intp x1_Dims[1] = {-1};
  const int x1_Rank = 1;
  PyArrayObject *capi_x1_tmp = NULL;
  int capi_x1_intent = 0;
  PyObject *x1_capi = Py_None;
  double *xopt = NULL;
  npy_intp xopt_Dims[1] = {-1};
  const int xopt_Rank = 1;
  PyArrayObject *capi_xopt_tmp = NULL;
  int capi_xopt_intent = 0;
  PyObject *xopt_capi = Py_None;
  double *xrec = NULL;
  npy_intp xrec_Dims[1] = {-1};
  const int xrec_Rank = 1;
  PyArrayObject *capi_xrec_tmp = NULL;
  int capi_xrec_intent = 0;
  PyObject *xrec_capi = Py_None;
  double *grec = NULL;
  npy_intp grec_Dims[1] = {-1};
  const int grec_Rank = 1;
  PyArrayObject *capi_grec_tmp = NULL;
  int capi_grec_intent = 0;
  PyObject *grec_capi = Py_None;
  double *xx = NULL;
  npy_intp xx_Dims[1] = {-1};
  const int xx_Rank = 1;
  PyArrayObject *capi_xx_tmp = NULL;
  int capi_xx_intent = 0;
  PyObject *xx_capi = Py_None;
  double *deltax = NULL;
  npy_intp deltax_Dims[1] = {-1};
  const int deltax_Rank = 1;
  PyArrayObject *capi_deltax_tmp = NULL;
  int capi_deltax_intent = 0;
  PyObject *deltax_capi = Py_None;
  int *idx = NULL;
  npy_intp idx_Dims[1] = {-1};
  const int idx_Rank = 1;
  PyArrayObject *capi_idx_tmp = NULL;
  int capi_idx_intent = 0;
  PyObject *idx_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  string ifile = NULL;
  int slen(ifile);
  PyObject *ifile_capi = Py_None;
  static char *capi_kwlist[] = {"n","x","f","fun","flg","grad","options","flfc","func","flgc","gradc","b","g","g0","g1","gt","gc","z","x1","xopt","xrec","grec","xx","deltax","idx","iout","ifile","fun_extra_args","grad_extra_args","func_extra_args","gradc_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOO|O!O!O!O!:solvopt.solvopt",\
    capi_kwlist,&n_capi,&x_capi,&f_capi,&fun_capi,&flg_capi,&grad_capi,&options_capi,&flfc_capi,&func_capi,&flgc_capi,&gradc_capi,&b_capi,&g_capi,&g0_capi,&g1_capi,&gt_capi,&gc_capi,&z_capi,&x1_capi,&xopt_capi,&xrec_capi,&grec_capi,&xx_capi,&deltax_capi,&idx_capi,&iout_capi,&ifile_capi,&PyTuple_Type,&fun_xa_capi,&PyTuple_Type,&grad_xa_capi,&PyTuple_Type,&func_xa_capi,&PyTuple_Type,&gradc_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"solvopt.solvopt() 1st argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable f */
    f2py_success = double_from_pyobj(&f,f_capi,"solvopt.solvopt() 3rd argument (f) can't be converted to double");
  if (f2py_success) {
  /* Processing variable fun */
if(F2PyCapsule_Check(fun_capi)) {
  fun_cptr = F2PyCapsule_AsVoidPtr(fun_capi);
} else {
  fun_cptr = cb_fun_in_solvopt__user__routines;
}

  fun_nofargs_capi = cb_fun_in_solvopt__user__routines_nofargs;
  if (create_cb_arglist(fun_capi,fun_xa_capi,3,0,&cb_fun_in_solvopt__user__routines_nofargs,&fun_args_capi,"failed in processing argument list for call-back fun.")) {
    jmp_buf fun_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `fun`.\n");
    SWAP(fun_capi,cb_fun_in_solvopt__user__routines_capi,PyObject);
    SWAP(fun_args_capi,cb_fun_in_solvopt__user__routines_args_capi,PyTupleObject);
    memcpy(&fun_jmpbuf,&cb_fun_in_solvopt__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable flg */
    flg = (int)PyObject_IsTrue(flg_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable grad */
if(F2PyCapsule_Check(grad_capi)) {
  grad_cptr = F2PyCapsule_AsVoidPtr(grad_capi);
} else {
  grad_cptr = cb_grad_in_solvopt__user__routines;
}

  grad_nofargs_capi = cb_grad_in_solvopt__user__routines_nofargs;
  if (create_cb_arglist(grad_capi,grad_xa_capi,3,0,&cb_grad_in_solvopt__user__routines_nofargs,&grad_args_capi,"failed in processing argument list for call-back grad.")) {
    jmp_buf grad_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `grad`.\n");
    SWAP(grad_capi,cb_grad_in_solvopt__user__routines_capi,PyObject);
    SWAP(grad_args_capi,cb_grad_in_solvopt__user__routines_args_capi,PyTupleObject);
    memcpy(&grad_jmpbuf,&cb_grad_in_solvopt__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable options */
  options_Dims[0]=13;
  capi_options_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_options_tmp = array_from_pyobj(NPY_DOUBLE,options_Dims,options_Rank,capi_options_intent,options_capi);
  if (capi_options_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 7th argument `options' of solvopt.solvopt to C/Fortran array" );
  } else {
    options = (double *)(PyArray_DATA(capi_options_tmp));

  /* Processing variable flfc */
    flfc = (int)PyObject_IsTrue(flfc_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable func */
if(F2PyCapsule_Check(func_capi)) {
  func_cptr = F2PyCapsule_AsVoidPtr(func_capi);
} else {
  func_cptr = cb_func_in_solvopt__user__routines;
}

  func_nofargs_capi = cb_func_in_solvopt__user__routines_nofargs;
  if (create_cb_arglist(func_capi,func_xa_capi,3,0,&cb_func_in_solvopt__user__routines_nofargs,&func_args_capi,"failed in processing argument list for call-back func.")) {
    jmp_buf func_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `func`.\n");
    SWAP(func_capi,cb_func_in_solvopt__user__routines_capi,PyObject);
    SWAP(func_args_capi,cb_func_in_solvopt__user__routines_args_capi,PyTupleObject);
    memcpy(&func_jmpbuf,&cb_func_in_solvopt__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable flgc */
    flgc = (int)PyObject_IsTrue(flgc_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable gradc */
if(F2PyCapsule_Check(gradc_capi)) {
  gradc_cptr = F2PyCapsule_AsVoidPtr(gradc_capi);
} else {
  gradc_cptr = cb_gradc_in_solvopt__user__routines;
}

  gradc_nofargs_capi = cb_gradc_in_solvopt__user__routines_nofargs;
  if (create_cb_arglist(gradc_capi,gradc_xa_capi,3,0,&cb_gradc_in_solvopt__user__routines_nofargs,&gradc_args_capi,"failed in processing argument list for call-back gradc.")) {
    jmp_buf gradc_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `gradc`.\n");
    SWAP(gradc_capi,cb_gradc_in_solvopt__user__routines_capi,PyObject);
    SWAP(gradc_args_capi,cb_gradc_in_solvopt__user__routines_args_capi,PyTupleObject);
    memcpy(&gradc_jmpbuf,&cb_gradc_in_solvopt__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"solvopt.solvopt() 26th argument (iout) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifile */
  slen(ifile) = -1;
  f2py_success = string_from_pyobj(&ifile,&slen(ifile),"",ifile_capi,"string_from_pyobj failed in converting 27th argument `ifile' of solvopt.solvopt to C string");
  if (f2py_success) {
  /* Processing variable x */
  x_Dims[0]=n;
  capi_x_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 2nd argument `x' of solvopt.solvopt to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable b */
  b_Dims[0]=n,b_Dims[1]=n;
  capi_b_intent |= F2PY_INTENT_IN;
  capi_b_tmp = array_from_pyobj(NPY_DOUBLE,b_Dims,b_Rank,capi_b_intent,b_capi);
  if (capi_b_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 12nd argument `b' of solvopt.solvopt to C/Fortran array" );
  } else {
    b = (double *)(PyArray_DATA(capi_b_tmp));

  /* Processing variable g */
  g_Dims[0]=n;
  capi_g_intent |= F2PY_INTENT_IN;
  capi_g_tmp = array_from_pyobj(NPY_DOUBLE,g_Dims,g_Rank,capi_g_intent,g_capi);
  if (capi_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 13rd argument `g' of solvopt.solvopt to C/Fortran array" );
  } else {
    g = (double *)(PyArray_DATA(capi_g_tmp));

  /* Processing variable g0 */
  g0_Dims[0]=n;
  capi_g0_intent |= F2PY_INTENT_IN;
  capi_g0_tmp = array_from_pyobj(NPY_DOUBLE,g0_Dims,g0_Rank,capi_g0_intent,g0_capi);
  if (capi_g0_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 14th argument `g0' of solvopt.solvopt to C/Fortran array" );
  } else {
    g0 = (double *)(PyArray_DATA(capi_g0_tmp));

  /* Processing variable g1 */
  g1_Dims[0]=n;
  capi_g1_intent |= F2PY_INTENT_IN;
  capi_g1_tmp = array_from_pyobj(NPY_DOUBLE,g1_Dims,g1_Rank,capi_g1_intent,g1_capi);
  if (capi_g1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 15th argument `g1' of solvopt.solvopt to C/Fortran array" );
  } else {
    g1 = (double *)(PyArray_DATA(capi_g1_tmp));

  /* Processing variable gt */
  gt_Dims[0]=n;
  capi_gt_intent |= F2PY_INTENT_IN;
  capi_gt_tmp = array_from_pyobj(NPY_DOUBLE,gt_Dims,gt_Rank,capi_gt_intent,gt_capi);
  if (capi_gt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 16th argument `gt' of solvopt.solvopt to C/Fortran array" );
  } else {
    gt = (double *)(PyArray_DATA(capi_gt_tmp));

  /* Processing variable gc */
  gc_Dims[0]=n;
  capi_gc_intent |= F2PY_INTENT_IN;
  capi_gc_tmp = array_from_pyobj(NPY_DOUBLE,gc_Dims,gc_Rank,capi_gc_intent,gc_capi);
  if (capi_gc_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 17th argument `gc' of solvopt.solvopt to C/Fortran array" );
  } else {
    gc = (double *)(PyArray_DATA(capi_gc_tmp));

  /* Processing variable z */
  z_Dims[0]=n;
  capi_z_intent |= F2PY_INTENT_IN;
  capi_z_tmp = array_from_pyobj(NPY_DOUBLE,z_Dims,z_Rank,capi_z_intent,z_capi);
  if (capi_z_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 18th argument `z' of solvopt.solvopt to C/Fortran array" );
  } else {
    z = (double *)(PyArray_DATA(capi_z_tmp));

  /* Processing variable x1 */
  x1_Dims[0]=n;
  capi_x1_intent |= F2PY_INTENT_IN;
  capi_x1_tmp = array_from_pyobj(NPY_DOUBLE,x1_Dims,x1_Rank,capi_x1_intent,x1_capi);
  if (capi_x1_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 19th argument `x1' of solvopt.solvopt to C/Fortran array" );
  } else {
    x1 = (double *)(PyArray_DATA(capi_x1_tmp));

  /* Processing variable xopt */
  xopt_Dims[0]=n;
  capi_xopt_intent |= F2PY_INTENT_IN;
  capi_xopt_tmp = array_from_pyobj(NPY_DOUBLE,xopt_Dims,xopt_Rank,capi_xopt_intent,xopt_capi);
  if (capi_xopt_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 20th argument `xopt' of solvopt.solvopt to C/Fortran array" );
  } else {
    xopt = (double *)(PyArray_DATA(capi_xopt_tmp));

  /* Processing variable xrec */
  xrec_Dims[0]=n;
  capi_xrec_intent |= F2PY_INTENT_IN;
  capi_xrec_tmp = array_from_pyobj(NPY_DOUBLE,xrec_Dims,xrec_Rank,capi_xrec_intent,xrec_capi);
  if (capi_xrec_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 21st argument `xrec' of solvopt.solvopt to C/Fortran array" );
  } else {
    xrec = (double *)(PyArray_DATA(capi_xrec_tmp));

  /* Processing variable grec */
  grec_Dims[0]=n;
  capi_grec_intent |= F2PY_INTENT_IN;
  capi_grec_tmp = array_from_pyobj(NPY_DOUBLE,grec_Dims,grec_Rank,capi_grec_intent,grec_capi);
  if (capi_grec_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 22nd argument `grec' of solvopt.solvopt to C/Fortran array" );
  } else {
    grec = (double *)(PyArray_DATA(capi_grec_tmp));

  /* Processing variable xx */
  xx_Dims[0]=n;
  capi_xx_intent |= F2PY_INTENT_IN;
  capi_xx_tmp = array_from_pyobj(NPY_DOUBLE,xx_Dims,xx_Rank,capi_xx_intent,xx_capi);
  if (capi_xx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 23rd argument `xx' of solvopt.solvopt to C/Fortran array" );
  } else {
    xx = (double *)(PyArray_DATA(capi_xx_tmp));

  /* Processing variable deltax */
  deltax_Dims[0]=n;
  capi_deltax_intent |= F2PY_INTENT_IN;
  capi_deltax_tmp = array_from_pyobj(NPY_DOUBLE,deltax_Dims,deltax_Rank,capi_deltax_intent,deltax_capi);
  if (capi_deltax_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 24th argument `deltax' of solvopt.solvopt to C/Fortran array" );
  } else {
    deltax = (double *)(PyArray_DATA(capi_deltax_tmp));

  /* Processing variable idx */
  idx_Dims[0]=n;
  capi_idx_intent |= F2PY_INTENT_IN;
  capi_idx_tmp = array_from_pyobj(NPY_INT,idx_Dims,idx_Rank,capi_idx_intent,idx_capi);
  if (capi_idx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(solvopt_error,"failed in converting 25th argument `idx' of solvopt.solvopt to C/Fortran array" );
  } else {
    idx = (int *)(PyArray_DATA(capi_idx_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_fun_in_solvopt__user__routines_jmpbuf)) || (setjmp(cb_grad_in_solvopt__user__routines_jmpbuf)) || (setjmp(cb_func_in_solvopt__user__routines_jmpbuf)) || (setjmp(cb_gradc_in_solvopt__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&n,x,&f,fun_cptr,&flg,grad_cptr,options,&flfc,func_cptr,&flgc,gradc_cptr,b,g,g0,g1,gt,gc,z,x1,xopt,xrec,grec,xx,deltax,idx,&iout,ifile,slen(ifile));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(f_capi,&f);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NN",capi_x_tmp,capi_options_tmp);
/*closepyobjfrom*/
  } /*if (f2py_success) of f pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_idx_tmp!=idx_capi) {
    Py_XDECREF(capi_idx_tmp); }
  }  /*if (capi_idx_tmp == NULL) ... else of idx*/
  /* End of cleaning variable idx */
  if((PyObject *)capi_deltax_tmp!=deltax_capi) {
    Py_XDECREF(capi_deltax_tmp); }
  }  /*if (capi_deltax_tmp == NULL) ... else of deltax*/
  /* End of cleaning variable deltax */
  if((PyObject *)capi_xx_tmp!=xx_capi) {
    Py_XDECREF(capi_xx_tmp); }
  }  /*if (capi_xx_tmp == NULL) ... else of xx*/
  /* End of cleaning variable xx */
  if((PyObject *)capi_grec_tmp!=grec_capi) {
    Py_XDECREF(capi_grec_tmp); }
  }  /*if (capi_grec_tmp == NULL) ... else of grec*/
  /* End of cleaning variable grec */
  if((PyObject *)capi_xrec_tmp!=xrec_capi) {
    Py_XDECREF(capi_xrec_tmp); }
  }  /*if (capi_xrec_tmp == NULL) ... else of xrec*/
  /* End of cleaning variable xrec */
  if((PyObject *)capi_xopt_tmp!=xopt_capi) {
    Py_XDECREF(capi_xopt_tmp); }
  }  /*if (capi_xopt_tmp == NULL) ... else of xopt*/
  /* End of cleaning variable xopt */
  if((PyObject *)capi_x1_tmp!=x1_capi) {
    Py_XDECREF(capi_x1_tmp); }
  }  /*if (capi_x1_tmp == NULL) ... else of x1*/
  /* End of cleaning variable x1 */
  if((PyObject *)capi_z_tmp!=z_capi) {
    Py_XDECREF(capi_z_tmp); }
  }  /*if (capi_z_tmp == NULL) ... else of z*/
  /* End of cleaning variable z */
  if((PyObject *)capi_gc_tmp!=gc_capi) {
    Py_XDECREF(capi_gc_tmp); }
  }  /*if (capi_gc_tmp == NULL) ... else of gc*/
  /* End of cleaning variable gc */
  if((PyObject *)capi_gt_tmp!=gt_capi) {
    Py_XDECREF(capi_gt_tmp); }
  }  /*if (capi_gt_tmp == NULL) ... else of gt*/
  /* End of cleaning variable gt */
  if((PyObject *)capi_g1_tmp!=g1_capi) {
    Py_XDECREF(capi_g1_tmp); }
  }  /*if (capi_g1_tmp == NULL) ... else of g1*/
  /* End of cleaning variable g1 */
  if((PyObject *)capi_g0_tmp!=g0_capi) {
    Py_XDECREF(capi_g0_tmp); }
  }  /*if (capi_g0_tmp == NULL) ... else of g0*/
  /* End of cleaning variable g0 */
  if((PyObject *)capi_g_tmp!=g_capi) {
    Py_XDECREF(capi_g_tmp); }
  }  /*if (capi_g_tmp == NULL) ... else of g*/
  /* End of cleaning variable g */
  if((PyObject *)capi_b_tmp!=b_capi) {
    Py_XDECREF(capi_b_tmp); }
  }  /*if (capi_b_tmp == NULL) ... else of b*/
  /* End of cleaning variable b */
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
    STRINGFREE(ifile);
  }  /*if (f2py_success) of ifile*/
  /* End of cleaning variable ifile */
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
    CFUNCSMESS("Restoring jmpbuf for `gradc`.\n");
    cb_gradc_in_solvopt__user__routines_capi = gradc_capi;
    Py_DECREF(cb_gradc_in_solvopt__user__routines_args_capi);
    cb_gradc_in_solvopt__user__routines_args_capi = gradc_args_capi;
    cb_gradc_in_solvopt__user__routines_nofargs = gradc_nofargs_capi;
    memcpy(&cb_gradc_in_solvopt__user__routines_jmpbuf,&gradc_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable gradc */
  } /*if (f2py_success) of flgc*/
  /* End of cleaning variable flgc */
    CFUNCSMESS("Restoring jmpbuf for `func`.\n");
    cb_func_in_solvopt__user__routines_capi = func_capi;
    Py_DECREF(cb_func_in_solvopt__user__routines_args_capi);
    cb_func_in_solvopt__user__routines_args_capi = func_args_capi;
    cb_func_in_solvopt__user__routines_nofargs = func_nofargs_capi;
    memcpy(&cb_func_in_solvopt__user__routines_jmpbuf,&func_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable func */
  } /*if (f2py_success) of flfc*/
  /* End of cleaning variable flfc */
  }  /*if (capi_options_tmp == NULL) ... else of options*/
  /* End of cleaning variable options */
    CFUNCSMESS("Restoring jmpbuf for `grad`.\n");
    cb_grad_in_solvopt__user__routines_capi = grad_capi;
    Py_DECREF(cb_grad_in_solvopt__user__routines_args_capi);
    cb_grad_in_solvopt__user__routines_args_capi = grad_args_capi;
    cb_grad_in_solvopt__user__routines_nofargs = grad_nofargs_capi;
    memcpy(&cb_grad_in_solvopt__user__routines_jmpbuf,&grad_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable grad */
  } /*if (f2py_success) of flg*/
  /* End of cleaning variable flg */
    CFUNCSMESS("Restoring jmpbuf for `fun`.\n");
    cb_fun_in_solvopt__user__routines_capi = fun_capi;
    Py_DECREF(cb_fun_in_solvopt__user__routines_args_capi);
    cb_fun_in_solvopt__user__routines_args_capi = fun_args_capi;
    cb_fun_in_solvopt__user__routines_nofargs = fun_nofargs_capi;
    memcpy(&cb_fun_in_solvopt__user__routines_jmpbuf,&fun_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable fun */
  } /*if (f2py_success) of f*/
  /* End of cleaning variable f */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of solvopt *******************************/

/********************************** openunit **********************************/
static char doc_f2py_rout_solvopt_openunit[] = "\
ierror = openunit(unitnum,filename,filestatus,fileaction)\n\nWrapper for ``openunit``.\
\n\nParameters\n----------\n"
"unitnum : input int\n"
"filename : input string(len=-1)\n"
"filestatus : input string(len=-1)\n"
"fileaction : input string(len=-1)\n"
"\nReturns\n-------\n"
"ierror : int";
/* extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout_solvopt_openunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,string,string,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  string filestatus = NULL;
  int slen(filestatus);
  PyObject *filestatus_capi = Py_None;
  string fileaction = NULL;
  int slen(fileaction);
  PyObject *fileaction_capi = Py_None;
  int ierror = 0;
  static char *capi_kwlist[] = {"unitnum","filename","filestatus","fileaction",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:solvopt.openunit",\
    capi_kwlist,&unitnum_capi,&filename_capi,&filestatus_capi,&fileaction_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"solvopt.openunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 2nd argument `filename' of solvopt.openunit to C string");
  if (f2py_success) {
  /* Processing variable filestatus */
  slen(filestatus) = -1;
  f2py_success = string_from_pyobj(&filestatus,&slen(filestatus),"",filestatus_capi,"string_from_pyobj failed in converting 3rd argument `filestatus' of solvopt.openunit to C string");
  if (f2py_success) {
  /* Processing variable fileaction */
  slen(fileaction) = -1;
  f2py_success = string_from_pyobj(&fileaction,&slen(fileaction),"",fileaction_capi,"string_from_pyobj failed in converting 4th argument `fileaction' of solvopt.openunit to C string");
  if (f2py_success) {
  /* Processing variable ierror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum,filename,filestatus,fileaction,&ierror,slen(filename),slen(filestatus),slen(fileaction));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ierror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierror */
    STRINGFREE(fileaction);
  }  /*if (f2py_success) of fileaction*/
  /* End of cleaning variable fileaction */
    STRINGFREE(filestatus);
  }  /*if (f2py_success) of filestatus*/
  /* End of cleaning variable filestatus */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of openunit ******************************/

/********************************** pyflush **********************************/
static char doc_f2py_rout_solvopt_pyflush[] = "\
pyflush(unitnum)\n\nWrapper for ``pyflush``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(pyflush,PYFLUSH)(int*); */
static PyObject *f2py_rout_solvopt_pyflush(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:solvopt.pyflush",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"solvopt.pyflush() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of pyflush *******************************/

/********************************* closeunit *********************************/
static char doc_f2py_rout_solvopt_closeunit[] = "\
closeunit(unitnum)\n\nWrapper for ``closeunit``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(closeunit,CLOSEUNIT)(int*); */
static PyObject *f2py_rout_solvopt_closeunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:solvopt.closeunit",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"solvopt.closeunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of closeunit ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"solvopt",-1,{{-1}},0,(char *)F_FUNC(solvopt,SOLVOPT),(f2py_init_func)f2py_rout_solvopt_solvopt,doc_f2py_rout_solvopt_solvopt},
  {"openunit",-1,{{-1}},0,(char *)F_FUNC(openunit,OPENUNIT),(f2py_init_func)f2py_rout_solvopt_openunit,doc_f2py_rout_solvopt_openunit},
  {"pyflush",-1,{{-1}},0,(char *)F_FUNC(pyflush,PYFLUSH),(f2py_init_func)f2py_rout_solvopt_pyflush,doc_f2py_rout_solvopt_pyflush},
  {"closeunit",-1,{{-1}},0,(char *)F_FUNC(closeunit,CLOSEUNIT),(f2py_init_func)f2py_rout_solvopt_closeunit,doc_f2py_rout_solvopt_closeunit},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "solvopt",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_solvopt(void) {
#else
#define RETVAL
PyMODINIT_FUNC initsolvopt(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = solvopt_module = PyModule_Create(&moduledef);
#else
  m = solvopt_module = Py_InitModule("solvopt", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module solvopt (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'solvopt' is auto-generated with f2py (version:2).\nFunctions:\n"
"  x,options = solvopt(n,x,f,fun,flg,grad,options,flfc,func,flgc,gradc,b,g,g0,g1,gt,gc,z,x1,xopt,xrec,grec,xx,deltax,idx,iout,ifile,fun_extra_args=(),grad_extra_args=(),func_extra_args=(),gradc_extra_args=())\n"
"  ierror = openunit(unitnum,filename,filestatus,fileaction)\n"
"  pyflush(unitnum)\n"
"  closeunit(unitnum)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  solvopt_error = PyErr_NewException ("solvopt.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"solvopt");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
