# Job configuration file for control system analyzer for inverted pendulum example

# simulation options
tspan = [0.0, 10.0]
show_status = true # show progress during simulation
plot = true # plot results on screen
