# Job configuration file for control system analyzer for inverted pendulum example
# simulation options
tspan = [0.0, 10.0]
show_status = true # show progress during simulation

# analyze options
analyze = true
max_iterations = 10 # number of iterations
initial_conditions = [0.0, 0.0, 0.0 , 0.0] # first x0
max_overshoot = 0.2 # 20% max overshoot
# rise_time = 0.5 # [s]
# steady_state_error = 0.02 #  Steady-state error of less than 2%
# settling_time = 5.0 # [s]

# display options
plot = true # plot results on screen
