# System Name
name = "inverted-pendulum"

# directory to output ROSmsg codecs
codec_dir = "codec"

# directory to send CSAF output
output_dir = "output"

# Order to Construct/Evaluate Components
evaluation_order = ["controller", "plant", "maneuver"]

# File to Log Results
log_file = "inv_pendulum.log"

# Log Level (info/debug)
log_level = "info"

[components]

  [components.controller]
    # environment to run under
    run_command = "python3"

    # path to model executable
    process = "ipcontroller.py"

    # whether to print debug diagnostics
    debug = false

    # subscribe to topic of a component (component name, topic name)
    sub = [["plant", "states"], ["maneuver", "outputs"]]

    # port to publish
    pub = 5502

  [components.plant]
    # environment to run under
    run_command = "python3"

    # path to model executable
    process = "ipplant.py"

    # whether to print debug diagnostics
    debug = false

    # subscribe to topic of a component (component name, topic name)
    sub = [["controller", "outputs"]]

    # port to publish
    pub = 5501

  [components.maneuver]
    # environment to run under
    run_command = "python3"

    # path to model executable
    process = "ipmaneuver.py"

    # whether to print debug diagnostics
    debug = false

    # subscribe to topic of a component (component name, topic name)
    sub = []

    # port to publish
    pub = 5503

