system_name = "4 Aircraft Lateral Rejoin Controller" 
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 50

is_discrete = true
is_hybrid = false


[parameters]
    rl = 4.0
    ti = 0.0
    tau = 10.0

[inputs]
  msgs = [ "dubinplant_state.msg",
  "dubinplant_state.msg",
  "dubinplant_state.msg",
  "dubinplant_state.msg" ]

[topics]

  [topics.outputs]
      msg = "controller_output.msg"