system_name = "Dubin's Aircraft 2D"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 50

is_discrete = false
is_hybrid = false


[parameters]
    idx = 0
    v = 10

[inputs]
  msgs = [ "controller_output.msg" ]

[topics]

  [topics.states]
      msg = "dubinplant_state.msg"
      initial = [0.0, 0.0, 0.0]