/* File: nlpqlpmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Apr 11 17:22:54 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *nlpqlp_error;
static PyObject *nlpqlp_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_nlgrad_in_nlpqlp__user__routines_typedef)(int *,int *,int *,double *,int *,int *,double *,double *,double *,double *);
typedef void(*cb_nlfunc_in_nlpqlp__user__routines_typedef)(int *,int *,int *,double *,int *,int *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"nlpqlp.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = nlpqlp_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = nlpqlp_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = nlpqlp_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(nlpqlp_error,errmess);
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(nlpqlp_wrap,NLPQLP_WRAP)(int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,double*,int*,int*,int*,int*,string,double*,int*,int*,int*,int*,int*,int*,int*,int*,cb_nlfunc_in_nlpqlp__user__routines_typedef,cb_nlgrad_in_nlpqlp__user__routines_typedef,size_t);
extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t);
extern void F_FUNC(pyflush,PYFLUSH)(int*);
extern void F_FUNC(closeunit,CLOSEUNIT)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/******************** cb_nlfunc_in_nlpqlp__user__routines ********************/
PyObject *cb_nlfunc_in_nlpqlp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_nlfunc_in_nlpqlp__user__routines_args_capi = NULL;
int cb_nlfunc_in_nlpqlp__user__routines_nofargs = 0;
jmp_buf cb_nlfunc_in_nlpqlp__user__routines_jmpbuf;
/*typedef void(*cb_nlfunc_in_nlpqlp__user__routines_typedef)(int *,int *,int *,double *,int *,int *,double *,double *);*/
static void cb_nlfunc_in_nlpqlp__user__routines (int *l_cb_capi,int *nmax_cb_capi,int *mmax_cb_capi,double *x,int *lactiv_cb_capi,int *active,double *f,double *g) {
  PyTupleObject *capi_arglist = cb_nlfunc_in_nlpqlp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int l=(*l_cb_capi);
  int nmax=(*nmax_cb_capi);
  int mmax=(*mmax_cb_capi);
  int lactiv=(*lactiv_cb_capi);
  npy_intp x_Dims[2] = {-1, -1};
  npy_intp active_Dims[1] = {-1};
  npy_intp f_Dims[1] = {-1};
  npy_intp g_Dims[2] = {-1, -1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_nlfunc_in_nlpqlp__user__routines (maxnofargs=8(-0))\n");
  CFUNCSMESSPY("cb:cb_nlfunc_in_nlpqlp__user__routines_capi=",cb_nlfunc_in_nlpqlp__user__routines_capi);
  if (cb_nlfunc_in_nlpqlp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_nlfunc_in_nlpqlp__user__routines_capi = PyObject_GetAttrString(nlpqlp_module,"nlfunc");
  }
  if (cb_nlfunc_in_nlpqlp__user__routines_capi==NULL) {
    PyErr_SetString(nlpqlp_error,"cb: Callback nlfunc not defined (as an argument or module nlpqlp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_nlfunc_in_nlpqlp__user__routines_capi)) {
  cb_nlfunc_in_nlpqlp__user__routines_typedef cb_nlfunc_in_nlpqlp__user__routines_cptr;
  cb_nlfunc_in_nlpqlp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_nlfunc_in_nlpqlp__user__routines_capi);
  (*cb_nlfunc_in_nlpqlp__user__routines_cptr)(l_cb_capi,nmax_cb_capi,mmax_cb_capi,x,lactiv_cb_capi,active,f,g);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(nlpqlp_module,"nlfunc_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(nlpqlp_error,"Failed to convert nlpqlp.nlfunc_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(nlpqlp_error,"Callback nlfunc argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=nmax,x_Dims[1]=l;
  active_Dims[0]=lactiv;
  f_Dims[0]=l;
  g_Dims[0]=mmax,g_Dims[1]=l;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(l)))
      goto capi_fail;
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nmax)))
      goto capi_fail;
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(mmax)))
      goto capi_fail;
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(lactiv)))
      goto capi_fail;
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_INT == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,active_Dims,NPY_INT,NULL,(char*)active,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,f_Dims,NPY_DOUBLE,NULL,(char*)f,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlfunc_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,g_Dims,NPY_DOUBLE,NULL,(char*)g,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function nlfunc.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_nlfunc_in_nlpqlp__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_nlfunc_in_nlpqlp__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,f_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(f,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,g_Dims,2,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(g,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_nlfunc_in_nlpqlp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_nlfunc_in_nlpqlp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_nlfunc_in_nlpqlp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_nlfunc_in_nlpqlp__user__routines *****************/


/******************** cb_nlgrad_in_nlpqlp__user__routines ********************/
PyObject *cb_nlgrad_in_nlpqlp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_nlgrad_in_nlpqlp__user__routines_args_capi = NULL;
int cb_nlgrad_in_nlpqlp__user__routines_nofargs = 0;
jmp_buf cb_nlgrad_in_nlpqlp__user__routines_jmpbuf;
/*typedef void(*cb_nlgrad_in_nlpqlp__user__routines_typedef)(int *,int *,int *,double *,int *,int *,double *,double *,double *,double *);*/
static void cb_nlgrad_in_nlpqlp__user__routines (int *l_cb_capi,int *nmax_cb_capi,int *mmax_cb_capi,double *x,int *lactiv_cb_capi,int *active,double *f,double *g,double *df,double *dg) {
  PyTupleObject *capi_arglist = cb_nlgrad_in_nlpqlp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int l=(*l_cb_capi);
  int nmax=(*nmax_cb_capi);
  int mmax=(*mmax_cb_capi);
  int lactiv=(*lactiv_cb_capi);
  npy_intp x_Dims[2] = {-1, -1};
  npy_intp active_Dims[1] = {-1};
  npy_intp f_Dims[1] = {-1};
  npy_intp g_Dims[2] = {-1, -1};
  npy_intp df_Dims[1] = {-1};
  npy_intp dg_Dims[2] = {-1, -1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_nlgrad_in_nlpqlp__user__routines (maxnofargs=10(-0))\n");
  CFUNCSMESSPY("cb:cb_nlgrad_in_nlpqlp__user__routines_capi=",cb_nlgrad_in_nlpqlp__user__routines_capi);
  if (cb_nlgrad_in_nlpqlp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_nlgrad_in_nlpqlp__user__routines_capi = PyObject_GetAttrString(nlpqlp_module,"nlgrad");
  }
  if (cb_nlgrad_in_nlpqlp__user__routines_capi==NULL) {
    PyErr_SetString(nlpqlp_error,"cb: Callback nlgrad not defined (as an argument or module nlpqlp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_nlgrad_in_nlpqlp__user__routines_capi)) {
  cb_nlgrad_in_nlpqlp__user__routines_typedef cb_nlgrad_in_nlpqlp__user__routines_cptr;
  cb_nlgrad_in_nlpqlp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_nlgrad_in_nlpqlp__user__routines_capi);
  (*cb_nlgrad_in_nlpqlp__user__routines_cptr)(l_cb_capi,nmax_cb_capi,mmax_cb_capi,x,lactiv_cb_capi,active,f,g,df,dg);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(nlpqlp_module,"nlgrad_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(nlpqlp_error,"Failed to convert nlpqlp.nlgrad_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(nlpqlp_error,"Callback nlgrad argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=nmax,x_Dims[1]=l;
  active_Dims[0]=lactiv;
  f_Dims[0]=l;
  g_Dims[0]=mmax,g_Dims[1]=l;
  df_Dims[0]=nmax;
  dg_Dims[0]=mmax,dg_Dims[1]=nmax;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(l)))
      goto capi_fail;
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nmax)))
      goto capi_fail;
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(mmax)))
      goto capi_fail;
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(lactiv)))
      goto capi_fail;
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_INT == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,active_Dims,NPY_INT,NULL,(char*)active,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,f_Dims,NPY_DOUBLE,NULL,(char*)f,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,g_Dims,NPY_DOUBLE,NULL,(char*)g,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,df_Dims,NPY_DOUBLE,NULL,(char*)df,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_nlgrad_in_nlpqlp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,dg_Dims,NPY_DOUBLE,NULL,(char*)dg,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function nlgrad.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_nlgrad_in_nlpqlp__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_nlgrad_in_nlpqlp__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,df_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(df,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,dg_Dims,2,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(dg,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_nlgrad_in_nlpqlp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_nlgrad_in_nlpqlp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_nlgrad_in_nlpqlp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_nlgrad_in_nlpqlp__user__routines *****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** nlpqlp_wrap ********************************/
static char doc_f2py_rout_nlpqlp_nlpqlp_wrap[] = "\
x,f,g,u,nfun,ngrd = nlpqlp_wrap(l,m,me,mmax,n,nmax,mnn2,x,f,g,df,dg,u,xl,xu,c,d,acc,accqp,stpmin,maxfun,maxit,maxnm,rhob,mode,ifail,iprint,iout,ifile,wa,lwa,kwa,lkwa,active,lactiv,lql,nfun,ngrd,nlfunc,nlgrad,[nlfunc_extra_args,nlgrad_extra_args])\n\nWrapper for ``nlpqlp_wrap``.\
\n\nParameters\n----------\n"
"l : input int\n"
"m : input int\n"
"me : input int\n"
"mmax : input int\n"
"n : input int\n"
"nmax : input int\n"
"mnn2 : input int\n"
"x : input rank-2 array('d') with bounds (nmax,l)\n"
"f : input rank-1 array('d') with bounds (l)\n"
"g : input rank-2 array('d') with bounds (mmax,l)\n"
"df : input rank-1 array('d') with bounds (nmax)\n"
"dg : input rank-2 array('d') with bounds (mmax,nmax)\n"
"u : input rank-1 array('d') with bounds (mnn2)\n"
"xl : input rank-1 array('d') with bounds (nmax)\n"
"xu : input rank-1 array('d') with bounds (nmax)\n"
"c : input rank-2 array('d') with bounds (nmax,nmax)\n"
"d : input rank-1 array('d') with bounds (nmax)\n"
"acc : input float\n"
"accqp : input float\n"
"stpmin : input float\n"
"maxfun : input int\n"
"maxit : input int\n"
"maxnm : input int\n"
"rhob : input float\n"
"mode : input int\n"
"ifail : input int\n"
"iprint : input int\n"
"iout : input int\n"
"ifile : input string(len=-1)\n"
"wa : input rank-1 array('d') with bounds (lwa)\n"
"lwa : input int\n"
"kwa : input rank-1 array('i') with bounds (lkwa)\n"
"lkwa : input int\n"
"active : input rank-1 array('i') with bounds (lactiv)\n"
"lactiv : input int\n"
"lql : input int\n"
"nfun : input int\n"
"ngrd : input int\n"
"nlfunc : call-back function\n"
"nlgrad : call-back function\n"
"\nOther Parameters\n----------------\n"
"nlfunc_extra_args : input tuple, optional\n    Default: ()\n"
"nlgrad_extra_args : input tuple, optional\n    Default: ()\n"
"\nReturns\n-------\n"
"x : rank-2 array('d') with bounds (nmax,l)\n"
"f : rank-1 array('d') with bounds (l)\n"
"g : rank-2 array('d') with bounds (mmax,l)\n"
"u : rank-1 array('d') with bounds (mnn2)\n"
"nfun : int\n"
"ngrd : int\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def nlfunc(l,nmax,mmax,x,lactiv,active,f,g): return f,g\n\
  Required arguments:\n"
"    l : input int\n"
"    nmax : input int\n"
"    mmax : input int\n"
"    x : input rank-2 array('d') with bounds (nmax,l)\n"
"    lactiv : input int\n"
"    active : input rank-1 array('i') with bounds (lactiv)\n"
"    f : input rank-1 array('d') with bounds (l)\n"
"    g : input rank-2 array('d') with bounds (mmax,l)\n"
"  Return objects:\n"
"    f : rank-1 array('d') with bounds (l)\n"
"    g : rank-2 array('d') with bounds (mmax,l)\n"
"  def nlgrad(l,nmax,mmax,x,lactiv,active,f,g,df,dg): return df,dg\n\
  Required arguments:\n"
"    l : input int\n"
"    nmax : input int\n"
"    mmax : input int\n"
"    x : input rank-2 array('d') with bounds (nmax,l)\n"
"    lactiv : input int\n"
"    active : input rank-1 array('i') with bounds (lactiv)\n"
"    f : input rank-1 array('d') with bounds (l)\n"
"    g : input rank-2 array('d') with bounds (mmax,l)\n"
"    df : input rank-1 array('d') with bounds (nmax)\n"
"    dg : input rank-2 array('d') with bounds (mmax,nmax)\n"
"  Return objects:\n"
"    df : rank-1 array('d') with bounds (nmax)\n"
"    dg : rank-2 array('d') with bounds (mmax,nmax)";
/* extern void F_FUNC_US(nlpqlp_wrap,NLPQLP_WRAP)(int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,double*,int*,int*,int*,int*,string,double*,int*,int*,int*,int*,int*,int*,int*,int*,cb_nlfunc_in_nlpqlp__user__routines_typedef,cb_nlgrad_in_nlpqlp__user__routines_typedef,size_t); */
static PyObject *f2py_rout_nlpqlp_nlpqlp_wrap(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,int*,double*,int*,int*,int*,int*,string,double*,int*,int*,int*,int*,int*,int*,int*,int*,cb_nlfunc_in_nlpqlp__user__routines_typedef,cb_nlgrad_in_nlpqlp__user__routines_typedef,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int l = 0;
  PyObject *l_capi = Py_None;
  int m = 0;
  PyObject *m_capi = Py_None;
  int me = 0;
  PyObject *me_capi = Py_None;
  int mmax = 0;
  PyObject *mmax_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int nmax = 0;
  PyObject *nmax_capi = Py_None;
  int mnn2 = 0;
  PyObject *mnn2_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[2] = {-1, -1};
  const int x_Rank = 2;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[1] = {-1};
  const int f_Rank = 1;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  double *g = NULL;
  npy_intp g_Dims[2] = {-1, -1};
  const int g_Rank = 2;
  PyArrayObject *capi_g_tmp = NULL;
  int capi_g_intent = 0;
  PyObject *g_capi = Py_None;
  double *df = NULL;
  npy_intp df_Dims[1] = {-1};
  const int df_Rank = 1;
  PyArrayObject *capi_df_tmp = NULL;
  int capi_df_intent = 0;
  PyObject *df_capi = Py_None;
  double *dg = NULL;
  npy_intp dg_Dims[2] = {-1, -1};
  const int dg_Rank = 2;
  PyArrayObject *capi_dg_tmp = NULL;
  int capi_dg_intent = 0;
  PyObject *dg_capi = Py_None;
  double *u = NULL;
  npy_intp u_Dims[1] = {-1};
  const int u_Rank = 1;
  PyArrayObject *capi_u_tmp = NULL;
  int capi_u_intent = 0;
  PyObject *u_capi = Py_None;
  double *xl = NULL;
  npy_intp xl_Dims[1] = {-1};
  const int xl_Rank = 1;
  PyArrayObject *capi_xl_tmp = NULL;
  int capi_xl_intent = 0;
  PyObject *xl_capi = Py_None;
  double *xu = NULL;
  npy_intp xu_Dims[1] = {-1};
  const int xu_Rank = 1;
  PyArrayObject *capi_xu_tmp = NULL;
  int capi_xu_intent = 0;
  PyObject *xu_capi = Py_None;
  double *c = NULL;
  npy_intp c_Dims[2] = {-1, -1};
  const int c_Rank = 2;
  PyArrayObject *capi_c_tmp = NULL;
  int capi_c_intent = 0;
  PyObject *c_capi = Py_None;
  double *d = NULL;
  npy_intp d_Dims[1] = {-1};
  const int d_Rank = 1;
  PyArrayObject *capi_d_tmp = NULL;
  int capi_d_intent = 0;
  PyObject *d_capi = Py_None;
  double acc = 0;
  PyObject *acc_capi = Py_None;
  double accqp = 0;
  PyObject *accqp_capi = Py_None;
  double stpmin = 0;
  PyObject *stpmin_capi = Py_None;
  int maxfun = 0;
  PyObject *maxfun_capi = Py_None;
  int maxit = 0;
  PyObject *maxit_capi = Py_None;
  int maxnm = 0;
  PyObject *maxnm_capi = Py_None;
  double rhob = 0;
  PyObject *rhob_capi = Py_None;
  int mode = 0;
  PyObject *mode_capi = Py_None;
  int ifail = 0;
  PyObject *ifail_capi = Py_None;
  int iprint = 0;
  PyObject *iprint_capi = Py_None;
  int iout = 0;
  PyObject *iout_capi = Py_None;
  string ifile = NULL;
  int slen(ifile);
  PyObject *ifile_capi = Py_None;
  double *wa = NULL;
  npy_intp wa_Dims[1] = {-1};
  const int wa_Rank = 1;
  PyArrayObject *capi_wa_tmp = NULL;
  int capi_wa_intent = 0;
  PyObject *wa_capi = Py_None;
  int lwa = 0;
  PyObject *lwa_capi = Py_None;
  int *kwa = NULL;
  npy_intp kwa_Dims[1] = {-1};
  const int kwa_Rank = 1;
  PyArrayObject *capi_kwa_tmp = NULL;
  int capi_kwa_intent = 0;
  PyObject *kwa_capi = Py_None;
  int lkwa = 0;
  PyObject *lkwa_capi = Py_None;
  int *active = NULL;
  npy_intp active_Dims[1] = {-1};
  const int active_Rank = 1;
  PyArrayObject *capi_active_tmp = NULL;
  int capi_active_intent = 0;
  PyObject *active_capi = Py_None;
  int lactiv = 0;
  PyObject *lactiv_capi = Py_None;
  int lql = 0;
  PyObject *lql_capi = Py_None;
  int nfun = 0;
  PyObject *nfun_capi = Py_None;
  int ngrd = 0;
  PyObject *ngrd_capi = Py_None;
  PyObject *nlfunc_capi = Py_None;
  PyTupleObject *nlfunc_xa_capi = NULL;
  PyTupleObject *nlfunc_args_capi = NULL;
  int nlfunc_nofargs_capi = 0;
  cb_nlfunc_in_nlpqlp__user__routines_typedef nlfunc_cptr;
  PyObject *nlgrad_capi = Py_None;
  PyTupleObject *nlgrad_xa_capi = NULL;
  PyTupleObject *nlgrad_args_capi = NULL;
  int nlgrad_nofargs_capi = 0;
  cb_nlgrad_in_nlpqlp__user__routines_typedef nlgrad_cptr;
  static char *capi_kwlist[] = {"l","m","me","mmax","n","nmax","mnn2","x","f","g","df","dg","u","xl","xu","c","d","acc","accqp","stpmin","maxfun","maxit","maxnm","rhob","mode","ifail","iprint","iout","ifile","wa","lwa","kwa","lkwa","active","lactiv","lql","nfun","ngrd","nlfunc","nlgrad","nlfunc_extra_args","nlgrad_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOOO|O!O!:nlpqlp.nlpqlp_wrap",\
    capi_kwlist,&l_capi,&m_capi,&me_capi,&mmax_capi,&n_capi,&nmax_capi,&mnn2_capi,&x_capi,&f_capi,&g_capi,&df_capi,&dg_capi,&u_capi,&xl_capi,&xu_capi,&c_capi,&d_capi,&acc_capi,&accqp_capi,&stpmin_capi,&maxfun_capi,&maxit_capi,&maxnm_capi,&rhob_capi,&mode_capi,&ifail_capi,&iprint_capi,&iout_capi,&ifile_capi,&wa_capi,&lwa_capi,&kwa_capi,&lkwa_capi,&active_capi,&lactiv_capi,&lql_capi,&nfun_capi,&ngrd_capi,&nlfunc_capi,&nlgrad_capi,&PyTuple_Type,&nlfunc_xa_capi,&PyTuple_Type,&nlgrad_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable l */
    f2py_success = int_from_pyobj(&l,l_capi,"nlpqlp.nlpqlp_wrap() 1st argument (l) can't be converted to int");
  if (f2py_success) {
  /* Processing variable m */
    f2py_success = int_from_pyobj(&m,m_capi,"nlpqlp.nlpqlp_wrap() 2nd argument (m) can't be converted to int");
  if (f2py_success) {
  /* Processing variable me */
    f2py_success = int_from_pyobj(&me,me_capi,"nlpqlp.nlpqlp_wrap() 3rd argument (me) can't be converted to int");
  if (f2py_success) {
  /* Processing variable mmax */
    f2py_success = int_from_pyobj(&mmax,mmax_capi,"nlpqlp.nlpqlp_wrap() 4th argument (mmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"nlpqlp.nlpqlp_wrap() 5th argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nmax */
    f2py_success = int_from_pyobj(&nmax,nmax_capi,"nlpqlp.nlpqlp_wrap() 6th argument (nmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable mnn2 */
    f2py_success = int_from_pyobj(&mnn2,mnn2_capi,"nlpqlp.nlpqlp_wrap() 7th argument (mnn2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable acc */
    f2py_success = double_from_pyobj(&acc,acc_capi,"nlpqlp.nlpqlp_wrap() 18th argument (acc) can't be converted to double");
  if (f2py_success) {
  /* Processing variable accqp */
    f2py_success = double_from_pyobj(&accqp,accqp_capi,"nlpqlp.nlpqlp_wrap() 19th argument (accqp) can't be converted to double");
  if (f2py_success) {
  /* Processing variable stpmin */
    f2py_success = double_from_pyobj(&stpmin,stpmin_capi,"nlpqlp.nlpqlp_wrap() 20th argument (stpmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable maxfun */
    f2py_success = int_from_pyobj(&maxfun,maxfun_capi,"nlpqlp.nlpqlp_wrap() 21st argument (maxfun) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxit */
    f2py_success = int_from_pyobj(&maxit,maxit_capi,"nlpqlp.nlpqlp_wrap() 22nd argument (maxit) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxnm */
    f2py_success = int_from_pyobj(&maxnm,maxnm_capi,"nlpqlp.nlpqlp_wrap() 23rd argument (maxnm) can't be converted to int");
  if (f2py_success) {
  /* Processing variable rhob */
    f2py_success = double_from_pyobj(&rhob,rhob_capi,"nlpqlp.nlpqlp_wrap() 24th argument (rhob) can't be converted to double");
  if (f2py_success) {
  /* Processing variable mode */
    f2py_success = int_from_pyobj(&mode,mode_capi,"nlpqlp.nlpqlp_wrap() 25th argument (mode) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifail */
    f2py_success = int_from_pyobj(&ifail,ifail_capi,"nlpqlp.nlpqlp_wrap() 26th argument (ifail) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iprint */
    f2py_success = int_from_pyobj(&iprint,iprint_capi,"nlpqlp.nlpqlp_wrap() 27th argument (iprint) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iout */
    f2py_success = int_from_pyobj(&iout,iout_capi,"nlpqlp.nlpqlp_wrap() 28th argument (iout) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifile */
  slen(ifile) = -1;
  f2py_success = string_from_pyobj(&ifile,&slen(ifile),"",ifile_capi,"string_from_pyobj failed in converting 29th argument `ifile' of nlpqlp.nlpqlp_wrap to C string");
  if (f2py_success) {
  /* Processing variable lwa */
    f2py_success = int_from_pyobj(&lwa,lwa_capi,"nlpqlp.nlpqlp_wrap() 31st argument (lwa) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lkwa */
    f2py_success = int_from_pyobj(&lkwa,lkwa_capi,"nlpqlp.nlpqlp_wrap() 33rd argument (lkwa) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lactiv */
    f2py_success = int_from_pyobj(&lactiv,lactiv_capi,"nlpqlp.nlpqlp_wrap() 35th argument (lactiv) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lql */
    lql = (int)PyObject_IsTrue(lql_capi);
    f2py_success = 1;
  if (f2py_success) {
  /* Processing variable nfun */
    f2py_success = int_from_pyobj(&nfun,nfun_capi,"nlpqlp.nlpqlp_wrap() 37th argument (nfun) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ngrd */
    f2py_success = int_from_pyobj(&ngrd,ngrd_capi,"nlpqlp.nlpqlp_wrap() 38th argument (ngrd) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nlfunc */
if(F2PyCapsule_Check(nlfunc_capi)) {
  nlfunc_cptr = F2PyCapsule_AsVoidPtr(nlfunc_capi);
} else {
  nlfunc_cptr = cb_nlfunc_in_nlpqlp__user__routines;
}

  nlfunc_nofargs_capi = cb_nlfunc_in_nlpqlp__user__routines_nofargs;
  if (create_cb_arglist(nlfunc_capi,nlfunc_xa_capi,8,0,&cb_nlfunc_in_nlpqlp__user__routines_nofargs,&nlfunc_args_capi,"failed in processing argument list for call-back nlfunc.")) {
    jmp_buf nlfunc_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `nlfunc`.\n");
    SWAP(nlfunc_capi,cb_nlfunc_in_nlpqlp__user__routines_capi,PyObject);
    SWAP(nlfunc_args_capi,cb_nlfunc_in_nlpqlp__user__routines_args_capi,PyTupleObject);
    memcpy(&nlfunc_jmpbuf,&cb_nlfunc_in_nlpqlp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable nlgrad */
if(F2PyCapsule_Check(nlgrad_capi)) {
  nlgrad_cptr = F2PyCapsule_AsVoidPtr(nlgrad_capi);
} else {
  nlgrad_cptr = cb_nlgrad_in_nlpqlp__user__routines;
}

  nlgrad_nofargs_capi = cb_nlgrad_in_nlpqlp__user__routines_nofargs;
  if (create_cb_arglist(nlgrad_capi,nlgrad_xa_capi,10,0,&cb_nlgrad_in_nlpqlp__user__routines_nofargs,&nlgrad_args_capi,"failed in processing argument list for call-back nlgrad.")) {
    jmp_buf nlgrad_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `nlgrad`.\n");
    SWAP(nlgrad_capi,cb_nlgrad_in_nlpqlp__user__routines_capi,PyObject);
    SWAP(nlgrad_args_capi,cb_nlgrad_in_nlpqlp__user__routines_args_capi,PyTupleObject);
    memcpy(&nlgrad_jmpbuf,&cb_nlgrad_in_nlpqlp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable x */
  x_Dims[0]=nmax,x_Dims[1]=l;
  capi_x_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 8th argument `x' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable f */
  f_Dims[0]=l;
  capi_f_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 9th argument `f' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable g */
  g_Dims[0]=mmax,g_Dims[1]=l;
  capi_g_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_g_tmp = array_from_pyobj(NPY_DOUBLE,g_Dims,g_Rank,capi_g_intent,g_capi);
  if (capi_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 10th argument `g' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    g = (double *)(PyArray_DATA(capi_g_tmp));

  /* Processing variable df */
  df_Dims[0]=nmax;
  capi_df_intent |= F2PY_INTENT_IN;
  capi_df_tmp = array_from_pyobj(NPY_DOUBLE,df_Dims,df_Rank,capi_df_intent,df_capi);
  if (capi_df_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 11st argument `df' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    df = (double *)(PyArray_DATA(capi_df_tmp));

  /* Processing variable dg */
  dg_Dims[0]=mmax,dg_Dims[1]=nmax;
  capi_dg_intent |= F2PY_INTENT_IN;
  capi_dg_tmp = array_from_pyobj(NPY_DOUBLE,dg_Dims,dg_Rank,capi_dg_intent,dg_capi);
  if (capi_dg_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 12nd argument `dg' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    dg = (double *)(PyArray_DATA(capi_dg_tmp));

  /* Processing variable u */
  u_Dims[0]=mnn2;
  capi_u_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_u_tmp = array_from_pyobj(NPY_DOUBLE,u_Dims,u_Rank,capi_u_intent,u_capi);
  if (capi_u_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 13rd argument `u' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    u = (double *)(PyArray_DATA(capi_u_tmp));

  /* Processing variable xl */
  xl_Dims[0]=nmax;
  capi_xl_intent |= F2PY_INTENT_IN;
  capi_xl_tmp = array_from_pyobj(NPY_DOUBLE,xl_Dims,xl_Rank,capi_xl_intent,xl_capi);
  if (capi_xl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 14th argument `xl' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    xl = (double *)(PyArray_DATA(capi_xl_tmp));

  /* Processing variable xu */
  xu_Dims[0]=nmax;
  capi_xu_intent |= F2PY_INTENT_IN;
  capi_xu_tmp = array_from_pyobj(NPY_DOUBLE,xu_Dims,xu_Rank,capi_xu_intent,xu_capi);
  if (capi_xu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 15th argument `xu' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    xu = (double *)(PyArray_DATA(capi_xu_tmp));

  /* Processing variable c */
  c_Dims[0]=nmax,c_Dims[1]=nmax;
  capi_c_intent |= F2PY_INTENT_IN;
  capi_c_tmp = array_from_pyobj(NPY_DOUBLE,c_Dims,c_Rank,capi_c_intent,c_capi);
  if (capi_c_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 16th argument `c' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    c = (double *)(PyArray_DATA(capi_c_tmp));

  /* Processing variable d */
  d_Dims[0]=nmax;
  capi_d_intent |= F2PY_INTENT_IN;
  capi_d_tmp = array_from_pyobj(NPY_DOUBLE,d_Dims,d_Rank,capi_d_intent,d_capi);
  if (capi_d_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 17th argument `d' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    d = (double *)(PyArray_DATA(capi_d_tmp));

  /* Processing variable wa */
  wa_Dims[0]=lwa;
  capi_wa_intent |= F2PY_INTENT_IN;
  capi_wa_tmp = array_from_pyobj(NPY_DOUBLE,wa_Dims,wa_Rank,capi_wa_intent,wa_capi);
  if (capi_wa_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 30th argument `wa' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    wa = (double *)(PyArray_DATA(capi_wa_tmp));

  /* Processing variable kwa */
  kwa_Dims[0]=lkwa;
  capi_kwa_intent |= F2PY_INTENT_IN;
  capi_kwa_tmp = array_from_pyobj(NPY_INT,kwa_Dims,kwa_Rank,capi_kwa_intent,kwa_capi);
  if (capi_kwa_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 32nd argument `kwa' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    kwa = (int *)(PyArray_DATA(capi_kwa_tmp));

  /* Processing variable active */
  active_Dims[0]=lactiv;
  capi_active_intent |= F2PY_INTENT_IN;
  capi_active_tmp = array_from_pyobj(NPY_INT,active_Dims,active_Rank,capi_active_intent,active_capi);
  if (capi_active_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(nlpqlp_error,"failed in converting 34th argument `active' of nlpqlp.nlpqlp_wrap to C/Fortran array" );
  } else {
    active = (int *)(PyArray_DATA(capi_active_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_nlfunc_in_nlpqlp__user__routines_jmpbuf)) || (setjmp(cb_nlgrad_in_nlpqlp__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&l,&m,&me,&mmax,&n,&nmax,&mnn2,x,f,g,df,dg,u,xl,xu,c,d,&acc,&accqp,&stpmin,&maxfun,&maxit,&maxnm,&rhob,&mode,&ifail,&iprint,&iout,ifile,wa,&lwa,kwa,&lkwa,active,&lactiv,&lql,&nfun,&ngrd,nlfunc_cptr,nlgrad_cptr,slen(ifile));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("NNNNii",capi_x_tmp,capi_f_tmp,capi_g_tmp,capi_u_tmp,nfun,ngrd);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_active_tmp!=active_capi) {
    Py_XDECREF(capi_active_tmp); }
  }  /*if (capi_active_tmp == NULL) ... else of active*/
  /* End of cleaning variable active */
  if((PyObject *)capi_kwa_tmp!=kwa_capi) {
    Py_XDECREF(capi_kwa_tmp); }
  }  /*if (capi_kwa_tmp == NULL) ... else of kwa*/
  /* End of cleaning variable kwa */
  if((PyObject *)capi_wa_tmp!=wa_capi) {
    Py_XDECREF(capi_wa_tmp); }
  }  /*if (capi_wa_tmp == NULL) ... else of wa*/
  /* End of cleaning variable wa */
  if((PyObject *)capi_d_tmp!=d_capi) {
    Py_XDECREF(capi_d_tmp); }
  }  /*if (capi_d_tmp == NULL) ... else of d*/
  /* End of cleaning variable d */
  if((PyObject *)capi_c_tmp!=c_capi) {
    Py_XDECREF(capi_c_tmp); }
  }  /*if (capi_c_tmp == NULL) ... else of c*/
  /* End of cleaning variable c */
  if((PyObject *)capi_xu_tmp!=xu_capi) {
    Py_XDECREF(capi_xu_tmp); }
  }  /*if (capi_xu_tmp == NULL) ... else of xu*/
  /* End of cleaning variable xu */
  if((PyObject *)capi_xl_tmp!=xl_capi) {
    Py_XDECREF(capi_xl_tmp); }
  }  /*if (capi_xl_tmp == NULL) ... else of xl*/
  /* End of cleaning variable xl */
  }  /*if (capi_u_tmp == NULL) ... else of u*/
  /* End of cleaning variable u */
  if((PyObject *)capi_dg_tmp!=dg_capi) {
    Py_XDECREF(capi_dg_tmp); }
  }  /*if (capi_dg_tmp == NULL) ... else of dg*/
  /* End of cleaning variable dg */
  if((PyObject *)capi_df_tmp!=df_capi) {
    Py_XDECREF(capi_df_tmp); }
  }  /*if (capi_df_tmp == NULL) ... else of df*/
  /* End of cleaning variable df */
  }  /*if (capi_g_tmp == NULL) ... else of g*/
  /* End of cleaning variable g */
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
    CFUNCSMESS("Restoring jmpbuf for `nlgrad`.\n");
    cb_nlgrad_in_nlpqlp__user__routines_capi = nlgrad_capi;
    Py_DECREF(cb_nlgrad_in_nlpqlp__user__routines_args_capi);
    cb_nlgrad_in_nlpqlp__user__routines_args_capi = nlgrad_args_capi;
    cb_nlgrad_in_nlpqlp__user__routines_nofargs = nlgrad_nofargs_capi;
    memcpy(&cb_nlgrad_in_nlpqlp__user__routines_jmpbuf,&nlgrad_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable nlgrad */
    CFUNCSMESS("Restoring jmpbuf for `nlfunc`.\n");
    cb_nlfunc_in_nlpqlp__user__routines_capi = nlfunc_capi;
    Py_DECREF(cb_nlfunc_in_nlpqlp__user__routines_args_capi);
    cb_nlfunc_in_nlpqlp__user__routines_args_capi = nlfunc_args_capi;
    cb_nlfunc_in_nlpqlp__user__routines_nofargs = nlfunc_nofargs_capi;
    memcpy(&cb_nlfunc_in_nlpqlp__user__routines_jmpbuf,&nlfunc_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable nlfunc */
  } /*if (f2py_success) of ngrd*/
  /* End of cleaning variable ngrd */
  } /*if (f2py_success) of nfun*/
  /* End of cleaning variable nfun */
  } /*if (f2py_success) of lql*/
  /* End of cleaning variable lql */
  } /*if (f2py_success) of lactiv*/
  /* End of cleaning variable lactiv */
  } /*if (f2py_success) of lkwa*/
  /* End of cleaning variable lkwa */
  } /*if (f2py_success) of lwa*/
  /* End of cleaning variable lwa */
    STRINGFREE(ifile);
  }  /*if (f2py_success) of ifile*/
  /* End of cleaning variable ifile */
  } /*if (f2py_success) of iout*/
  /* End of cleaning variable iout */
  } /*if (f2py_success) of iprint*/
  /* End of cleaning variable iprint */
  } /*if (f2py_success) of ifail*/
  /* End of cleaning variable ifail */
  } /*if (f2py_success) of mode*/
  /* End of cleaning variable mode */
  } /*if (f2py_success) of rhob*/
  /* End of cleaning variable rhob */
  } /*if (f2py_success) of maxnm*/
  /* End of cleaning variable maxnm */
  } /*if (f2py_success) of maxit*/
  /* End of cleaning variable maxit */
  } /*if (f2py_success) of maxfun*/
  /* End of cleaning variable maxfun */
  } /*if (f2py_success) of stpmin*/
  /* End of cleaning variable stpmin */
  } /*if (f2py_success) of accqp*/
  /* End of cleaning variable accqp */
  } /*if (f2py_success) of acc*/
  /* End of cleaning variable acc */
  } /*if (f2py_success) of mnn2*/
  /* End of cleaning variable mnn2 */
  } /*if (f2py_success) of nmax*/
  /* End of cleaning variable nmax */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of mmax*/
  /* End of cleaning variable mmax */
  } /*if (f2py_success) of me*/
  /* End of cleaning variable me */
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of nlpqlp_wrap *****************************/

/********************************** openunit **********************************/
static char doc_f2py_rout_nlpqlp_openunit[] = "\
ierror = openunit(unitnum,filename,filestatus,fileaction)\n\nWrapper for ``openunit``.\
\n\nParameters\n----------\n"
"unitnum : input int\n"
"filename : input string(len=-1)\n"
"filestatus : input string(len=-1)\n"
"fileaction : input string(len=-1)\n"
"\nReturns\n-------\n"
"ierror : int";
/* extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout_nlpqlp_openunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,string,string,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  string filestatus = NULL;
  int slen(filestatus);
  PyObject *filestatus_capi = Py_None;
  string fileaction = NULL;
  int slen(fileaction);
  PyObject *fileaction_capi = Py_None;
  int ierror = 0;
  static char *capi_kwlist[] = {"unitnum","filename","filestatus","fileaction",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:nlpqlp.openunit",\
    capi_kwlist,&unitnum_capi,&filename_capi,&filestatus_capi,&fileaction_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"nlpqlp.openunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 2nd argument `filename' of nlpqlp.openunit to C string");
  if (f2py_success) {
  /* Processing variable filestatus */
  slen(filestatus) = -1;
  f2py_success = string_from_pyobj(&filestatus,&slen(filestatus),"",filestatus_capi,"string_from_pyobj failed in converting 3rd argument `filestatus' of nlpqlp.openunit to C string");
  if (f2py_success) {
  /* Processing variable fileaction */
  slen(fileaction) = -1;
  f2py_success = string_from_pyobj(&fileaction,&slen(fileaction),"",fileaction_capi,"string_from_pyobj failed in converting 4th argument `fileaction' of nlpqlp.openunit to C string");
  if (f2py_success) {
  /* Processing variable ierror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum,filename,filestatus,fileaction,&ierror,slen(filename),slen(filestatus),slen(fileaction));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ierror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierror */
    STRINGFREE(fileaction);
  }  /*if (f2py_success) of fileaction*/
  /* End of cleaning variable fileaction */
    STRINGFREE(filestatus);
  }  /*if (f2py_success) of filestatus*/
  /* End of cleaning variable filestatus */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of openunit ******************************/

/********************************** pyflush **********************************/
static char doc_f2py_rout_nlpqlp_pyflush[] = "\
pyflush(unitnum)\n\nWrapper for ``pyflush``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(pyflush,PYFLUSH)(int*); */
static PyObject *f2py_rout_nlpqlp_pyflush(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:nlpqlp.pyflush",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"nlpqlp.pyflush() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of pyflush *******************************/

/********************************* closeunit *********************************/
static char doc_f2py_rout_nlpqlp_closeunit[] = "\
closeunit(unitnum)\n\nWrapper for ``closeunit``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(closeunit,CLOSEUNIT)(int*); */
static PyObject *f2py_rout_nlpqlp_closeunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:nlpqlp.closeunit",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"nlpqlp.closeunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of closeunit ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"nlpqlp_wrap",-1,{{-1}},0,(char *)F_FUNC_US(nlpqlp_wrap,NLPQLP_WRAP),(f2py_init_func)f2py_rout_nlpqlp_nlpqlp_wrap,doc_f2py_rout_nlpqlp_nlpqlp_wrap},
  {"openunit",-1,{{-1}},0,(char *)F_FUNC(openunit,OPENUNIT),(f2py_init_func)f2py_rout_nlpqlp_openunit,doc_f2py_rout_nlpqlp_openunit},
  {"pyflush",-1,{{-1}},0,(char *)F_FUNC(pyflush,PYFLUSH),(f2py_init_func)f2py_rout_nlpqlp_pyflush,doc_f2py_rout_nlpqlp_pyflush},
  {"closeunit",-1,{{-1}},0,(char *)F_FUNC(closeunit,CLOSEUNIT),(f2py_init_func)f2py_rout_nlpqlp_closeunit,doc_f2py_rout_nlpqlp_closeunit},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "nlpqlp",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_nlpqlp(void) {
#else
#define RETVAL
PyMODINIT_FUNC initnlpqlp(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = nlpqlp_module = PyModule_Create(&moduledef);
#else
  m = nlpqlp_module = Py_InitModule("nlpqlp", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module nlpqlp (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'nlpqlp' is auto-generated with f2py (version:2).\nFunctions:\n"
"  x,f,g,u,nfun,ngrd = nlpqlp_wrap(l,m,me,mmax,n,nmax,mnn2,x,f,g,df,dg,u,xl,xu,c,d,acc,accqp,stpmin,maxfun,maxit,maxnm,rhob,mode,ifail,iprint,iout,ifile,wa,lwa,kwa,lkwa,active,lactiv,lql,nfun,ngrd,nlfunc,nlgrad,nlfunc_extra_args=(),nlgrad_extra_args=())\n"
"  ierror = openunit(unitnum,filename,filestatus,fileaction)\n"
"  pyflush(unitnum)\n"
"  closeunit(unitnum)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  nlpqlp_error = PyErr_NewException ("nlpqlp.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"nlpqlp");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
