name = "f16-heidlauf"

global_config = "./global_config.toml"

evaluation_order = ["controller", "plant", "autopilot"]

log_file = "f16run.log"
log_level = "debug"

[devices]
  [devices.controller]
    run_command = "python3"
    process = "../components/f16llc.py"
    config = "../components/f16llc.toml"
    debug = true
    sub = [["plant", "states"], ["plant", "outputs"], ["autopilot", "outputs"]]
    pub = 5502

  [devices.plant]
    run_command = "python3"
    process = "../components/f16plant.py"
    config = "../components/f16plant.toml"
    debug = true
    sub = [["controller", "outputs"]]
    pub = 5501

  [devices.autopilot]
    run_command = "python3"
    process = "../components/autopilot.py"
    debug = true
    sub = [["plant", "states"], ["plant", "outputs"]]
    pub = 5503
