/* File: midacomodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Apr 11 17:22:54 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *midaco_error;
static PyObject *midaco_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_objfun_in_midaco__user__routines_typedef)(int *,int *,int *,double *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"midaco.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(signed char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int try_pyarr_from_int(PyObject* obj,int* v) {
    TRYPYARRAYTEMPLATE(int,'i');
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = midaco_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = midaco_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(midaco_error,errmess);
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC_US(midaco_wrap,MIDACO_WRAP)(int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,string,string,string,int*,int*,int*,double*,cb_objfun_in_midaco__user__routines_typedef,size_t,size_t,size_t);
extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t);
extern void F_FUNC(pyflush,PYFLUSH)(int*);
extern void F_FUNC(closeunit,CLOSEUNIT)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/******************** cb_objfun_in_midaco__user__routines ********************/
PyObject *cb_objfun_in_midaco__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_objfun_in_midaco__user__routines_args_capi = NULL;
int cb_objfun_in_midaco__user__routines_nofargs = 0;
jmp_buf cb_objfun_in_midaco__user__routines_jmpbuf;
/*typedef void(*cb_objfun_in_midaco__user__routines_typedef)(int *,int *,int *,double *,double *,double *);*/
static void cb_objfun_in_midaco__user__routines (int *l_cb_capi,int *n_cb_capi,int *m_cb_capi,double *x,double *f,double *g) {
  PyTupleObject *capi_arglist = cb_objfun_in_midaco__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int l=(*l_cb_capi);
  int n=(*n_cb_capi);
  int m=(*m_cb_capi);
  npy_intp x_Dims[1] = {-1};
  npy_intp f_Dims[1] = {-1};
  npy_intp g_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_objfun_in_midaco__user__routines (maxnofargs=6(-0))\n");
  CFUNCSMESSPY("cb:cb_objfun_in_midaco__user__routines_capi=",cb_objfun_in_midaco__user__routines_capi);
  if (cb_objfun_in_midaco__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_objfun_in_midaco__user__routines_capi = PyObject_GetAttrString(midaco_module,"objfun");
  }
  if (cb_objfun_in_midaco__user__routines_capi==NULL) {
    PyErr_SetString(midaco_error,"cb: Callback objfun not defined (as an argument or module midaco attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_objfun_in_midaco__user__routines_capi)) {
  cb_objfun_in_midaco__user__routines_typedef cb_objfun_in_midaco__user__routines_cptr;
  cb_objfun_in_midaco__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_objfun_in_midaco__user__routines_capi);
  (*cb_objfun_in_midaco__user__routines_cptr)(l_cb_capi,n_cb_capi,m_cb_capi,x,f,g);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(midaco_module,"objfun_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(midaco_error,"Failed to convert midaco.objfun_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(midaco_error,"Callback objfun argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=l*n;
  f_Dims[0]=l;
  g_Dims[0]=l*m;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_objfun_in_midaco__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(l)))
      goto capi_fail;
  if (cb_objfun_in_midaco__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(n)))
      goto capi_fail;
  if (cb_objfun_in_midaco__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(m)))
      goto capi_fail;
  if (cb_objfun_in_midaco__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_objfun_in_midaco__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,f_Dims,NPY_DOUBLE,NULL,(char*)f,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_objfun_in_midaco__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,g_Dims,NPY_DOUBLE,NULL,(char*)g,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function objfun.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_objfun_in_midaco__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_objfun_in_midaco__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,f_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(f,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,g_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(g,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_objfun_in_midaco__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_objfun_in_midaco__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_objfun_in_midaco__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_objfun_in_midaco__user__routines *****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/******************************** midaco_wrap ********************************/
static char doc_f2py_rout_midaco_midaco_wrap[] = "\
iw = midaco_wrap(l,n,nint,m,me,x,xl,xu,f,g,param,maxeval,maxtime,ifail,neval,iprint,printeval,iout1,iout2,ifile1,ifile2,license_key,liw,iw,lrw,rw,objfun,[objfun_extra_args])\n\nWrapper for ``midaco_wrap``.\
\n\nParameters\n----------\n"
"l : input int\n"
"n : input int\n"
"nint : input int\n"
"m : input int\n"
"me : input int\n"
"x : in/output rank-1 array('d') with bounds (l*n)\n"
"xl : input rank-1 array('d') with bounds (n)\n"
"xu : input rank-1 array('d') with bounds (n)\n"
"f : in/output rank-1 array('d') with bounds (l)\n"
"g : in/output rank-1 array('d') with bounds (l*m)\n"
"param : input rank-1 array('d') with bounds (9)\n"
"maxeval : input int\n"
"maxtime : input int\n"
"ifail : in/output rank-0 array(int,'i')\n"
"neval : in/output rank-0 array(int,'i')\n"
"iprint : input int\n"
"printeval : input int\n"
"iout1 : input int\n"
"iout2 : input int\n"
"ifile1 : input string(len=-1)\n"
"ifile2 : input string(len=-1)\n"
"license_key : input string(len=60)\n"
"liw : input int\n"
"iw : input rank-1 array('i') with bounds (liw)\n"
"lrw : input int\n"
"rw : in/output rank-1 array('d') with bounds (lrw)\n"
"objfun : call-back function\n"
"\nOther Parameters\n----------------\n"
"objfun_extra_args : input tuple, optional\n    Default: ()\n"
"\nReturns\n-------\n"
"iw : rank-1 array('i') with bounds (liw)\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def objfun(l,n,m,x,f,g): return f,g\n\
  Required arguments:\n"
"    l : input int\n"
"    n : input int\n"
"    m : input int\n"
"    x : input rank-1 array('d') with bounds (l*n)\n"
"    f : input rank-1 array('d') with bounds (l)\n"
"    g : input rank-1 array('d') with bounds (l*m)\n"
"  Return objects:\n"
"    f : rank-1 array('d') with bounds (l)\n"
"    g : rank-1 array('d') with bounds (l*m)";
/* extern void F_FUNC_US(midaco_wrap,MIDACO_WRAP)(int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,string,string,string,int*,int*,int*,double*,cb_objfun_in_midaco__user__routines_typedef,size_t,size_t,size_t); */
static PyObject *f2py_rout_midaco_midaco_wrap(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,int*,int*,int*,int*,string,string,string,int*,int*,int*,double*,cb_objfun_in_midaco__user__routines_typedef,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int l = 0;
  PyObject *l_capi = Py_None;
  int n = 0;
  PyObject *n_capi = Py_None;
  int nint = 0;
  PyObject *nint_capi = Py_None;
  int m = 0;
  PyObject *m_capi = Py_None;
  int me = 0;
  PyObject *me_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *xl = NULL;
  npy_intp xl_Dims[1] = {-1};
  const int xl_Rank = 1;
  PyArrayObject *capi_xl_tmp = NULL;
  int capi_xl_intent = 0;
  PyObject *xl_capi = Py_None;
  double *xu = NULL;
  npy_intp xu_Dims[1] = {-1};
  const int xu_Rank = 1;
  PyArrayObject *capi_xu_tmp = NULL;
  int capi_xu_intent = 0;
  PyObject *xu_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[1] = {-1};
  const int f_Rank = 1;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  double *g = NULL;
  npy_intp g_Dims[1] = {-1};
  const int g_Rank = 1;
  PyArrayObject *capi_g_tmp = NULL;
  int capi_g_intent = 0;
  PyObject *g_capi = Py_None;
  double *param = NULL;
  npy_intp param_Dims[1] = {-1};
  const int param_Rank = 1;
  PyArrayObject *capi_param_tmp = NULL;
  int capi_param_intent = 0;
  PyObject *param_capi = Py_None;
  int maxeval = 0;
  PyObject *maxeval_capi = Py_None;
  int maxtime = 0;
  PyObject *maxtime_capi = Py_None;
  int ifail = 0;
  PyObject *ifail_capi = Py_None;
  int neval = 0;
  PyObject *neval_capi = Py_None;
  int iprint = 0;
  PyObject *iprint_capi = Py_None;
  int printeval = 0;
  PyObject *printeval_capi = Py_None;
  int iout1 = 0;
  PyObject *iout1_capi = Py_None;
  int iout2 = 0;
  PyObject *iout2_capi = Py_None;
  string ifile1 = NULL;
  int slen(ifile1);
  PyObject *ifile1_capi = Py_None;
  string ifile2 = NULL;
  int slen(ifile2);
  PyObject *ifile2_capi = Py_None;
  string license_key = NULL;
  int slen(license_key);
  PyObject *license_key_capi = Py_None;
  int liw = 0;
  PyObject *liw_capi = Py_None;
  int *iw = NULL;
  npy_intp iw_Dims[1] = {-1};
  const int iw_Rank = 1;
  PyArrayObject *capi_iw_tmp = NULL;
  int capi_iw_intent = 0;
  PyObject *iw_capi = Py_None;
  int lrw = 0;
  PyObject *lrw_capi = Py_None;
  double *rw = NULL;
  npy_intp rw_Dims[1] = {-1};
  const int rw_Rank = 1;
  PyArrayObject *capi_rw_tmp = NULL;
  int capi_rw_intent = 0;
  PyObject *rw_capi = Py_None;
  PyObject *objfun_capi = Py_None;
  PyTupleObject *objfun_xa_capi = NULL;
  PyTupleObject *objfun_args_capi = NULL;
  int objfun_nofargs_capi = 0;
  cb_objfun_in_midaco__user__routines_typedef objfun_cptr;
  static char *capi_kwlist[] = {"l","n","nint","m","me","x","xl","xu","f","g","param","maxeval","maxtime","ifail","neval","iprint","printeval","iout1","iout2","ifile1","ifile2","license_key","liw","iw","lrw","rw","objfun","objfun_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOO|O!:midaco.midaco_wrap",\
    capi_kwlist,&l_capi,&n_capi,&nint_capi,&m_capi,&me_capi,&x_capi,&xl_capi,&xu_capi,&f_capi,&g_capi,&param_capi,&maxeval_capi,&maxtime_capi,&ifail_capi,&neval_capi,&iprint_capi,&printeval_capi,&iout1_capi,&iout2_capi,&ifile1_capi,&ifile2_capi,&license_key_capi,&liw_capi,&iw_capi,&lrw_capi,&rw_capi,&objfun_capi,&PyTuple_Type,&objfun_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable l */
    f2py_success = int_from_pyobj(&l,l_capi,"midaco.midaco_wrap() 1st argument (l) can't be converted to int");
  if (f2py_success) {
  /* Processing variable n */
    f2py_success = int_from_pyobj(&n,n_capi,"midaco.midaco_wrap() 2nd argument (n) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nint */
    f2py_success = int_from_pyobj(&nint,nint_capi,"midaco.midaco_wrap() 3rd argument (nint) can't be converted to int");
  if (f2py_success) {
  /* Processing variable m */
    f2py_success = int_from_pyobj(&m,m_capi,"midaco.midaco_wrap() 4th argument (m) can't be converted to int");
  if (f2py_success) {
  /* Processing variable me */
    f2py_success = int_from_pyobj(&me,me_capi,"midaco.midaco_wrap() 5th argument (me) can't be converted to int");
  if (f2py_success) {
  /* Processing variable param */
  param_Dims[0]=9;
  capi_param_intent |= F2PY_INTENT_IN;
  capi_param_tmp = array_from_pyobj(NPY_DOUBLE,param_Dims,param_Rank,capi_param_intent,param_capi);
  if (capi_param_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 11st argument `param' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    param = (double *)(PyArray_DATA(capi_param_tmp));

  /* Processing variable maxeval */
    f2py_success = int_from_pyobj(&maxeval,maxeval_capi,"midaco.midaco_wrap() 12nd argument (maxeval) can't be converted to int");
  if (f2py_success) {
  /* Processing variable maxtime */
    f2py_success = int_from_pyobj(&maxtime,maxtime_capi,"midaco.midaco_wrap() 13rd argument (maxtime) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifail */
    f2py_success = int_from_pyobj(&ifail,ifail_capi,"midaco.midaco_wrap() 14th argument (ifail) can't be converted to int");
  if (f2py_success) {
  /* Processing variable neval */
    f2py_success = int_from_pyobj(&neval,neval_capi,"midaco.midaco_wrap() 15th argument (neval) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iprint */
    f2py_success = int_from_pyobj(&iprint,iprint_capi,"midaco.midaco_wrap() 16th argument (iprint) can't be converted to int");
  if (f2py_success) {
  /* Processing variable printeval */
    f2py_success = int_from_pyobj(&printeval,printeval_capi,"midaco.midaco_wrap() 17th argument (printeval) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iout1 */
    f2py_success = int_from_pyobj(&iout1,iout1_capi,"midaco.midaco_wrap() 18th argument (iout1) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iout2 */
    f2py_success = int_from_pyobj(&iout2,iout2_capi,"midaco.midaco_wrap() 19th argument (iout2) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifile1 */
  slen(ifile1) = -1;
  f2py_success = string_from_pyobj(&ifile1,&slen(ifile1),"",ifile1_capi,"string_from_pyobj failed in converting 20th argument `ifile1' of midaco.midaco_wrap to C string");
  if (f2py_success) {
  /* Processing variable ifile2 */
  slen(ifile2) = -1;
  f2py_success = string_from_pyobj(&ifile2,&slen(ifile2),"",ifile2_capi,"string_from_pyobj failed in converting 21st argument `ifile2' of midaco.midaco_wrap to C string");
  if (f2py_success) {
  /* Processing variable license_key */
  slen(license_key) = 60;
  f2py_success = string_from_pyobj(&license_key,&slen(license_key),"",license_key_capi,"string_from_pyobj failed in converting 22nd argument `license_key' of midaco.midaco_wrap to C string");
  if (f2py_success) {
  /* Processing variable liw */
    f2py_success = int_from_pyobj(&liw,liw_capi,"midaco.midaco_wrap() 23rd argument (liw) can't be converted to int");
  if (f2py_success) {
  /* Processing variable lrw */
    f2py_success = int_from_pyobj(&lrw,lrw_capi,"midaco.midaco_wrap() 25th argument (lrw) can't be converted to int");
  if (f2py_success) {
  /* Processing variable objfun */
if(F2PyCapsule_Check(objfun_capi)) {
  objfun_cptr = F2PyCapsule_AsVoidPtr(objfun_capi);
} else {
  objfun_cptr = cb_objfun_in_midaco__user__routines;
}

  objfun_nofargs_capi = cb_objfun_in_midaco__user__routines_nofargs;
  if (create_cb_arglist(objfun_capi,objfun_xa_capi,6,0,&cb_objfun_in_midaco__user__routines_nofargs,&objfun_args_capi,"failed in processing argument list for call-back objfun.")) {
    jmp_buf objfun_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `objfun`.\n");
    SWAP(objfun_capi,cb_objfun_in_midaco__user__routines_capi,PyObject);
    SWAP(objfun_args_capi,cb_objfun_in_midaco__user__routines_args_capi,PyTupleObject);
    memcpy(&objfun_jmpbuf,&cb_objfun_in_midaco__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable x */
  x_Dims[0]=l*n;
  capi_x_intent |= F2PY_INTENT_INOUT;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 6th argument `x' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable xl */
  xl_Dims[0]=n;
  capi_xl_intent |= F2PY_INTENT_IN;
  capi_xl_tmp = array_from_pyobj(NPY_DOUBLE,xl_Dims,xl_Rank,capi_xl_intent,xl_capi);
  if (capi_xl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 7th argument `xl' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    xl = (double *)(PyArray_DATA(capi_xl_tmp));

  /* Processing variable xu */
  xu_Dims[0]=n;
  capi_xu_intent |= F2PY_INTENT_IN;
  capi_xu_tmp = array_from_pyobj(NPY_DOUBLE,xu_Dims,xu_Rank,capi_xu_intent,xu_capi);
  if (capi_xu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 8th argument `xu' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    xu = (double *)(PyArray_DATA(capi_xu_tmp));

  /* Processing variable f */
  f_Dims[0]=l;
  capi_f_intent |= F2PY_INTENT_INOUT;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 9th argument `f' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable g */
  g_Dims[0]=l*m;
  capi_g_intent |= F2PY_INTENT_INOUT;
  capi_g_tmp = array_from_pyobj(NPY_DOUBLE,g_Dims,g_Rank,capi_g_intent,g_capi);
  if (capi_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 10th argument `g' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    g = (double *)(PyArray_DATA(capi_g_tmp));

  /* Processing variable iw */
  iw_Dims[0]=liw;
  capi_iw_intent |= F2PY_INTENT_IN|F2PY_INTENT_OUT;
  capi_iw_tmp = array_from_pyobj(NPY_INT,iw_Dims,iw_Rank,capi_iw_intent,iw_capi);
  if (capi_iw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 24th argument `iw' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    iw = (int *)(PyArray_DATA(capi_iw_tmp));

  /* Processing variable rw */
  rw_Dims[0]=lrw;
  capi_rw_intent |= F2PY_INTENT_INOUT;
  capi_rw_tmp = array_from_pyobj(NPY_DOUBLE,rw_Dims,rw_Rank,capi_rw_intent,rw_capi);
  if (capi_rw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(midaco_error,"failed in converting 26th argument `rw' of midaco.midaco_wrap to C/Fortran array" );
  } else {
    rw = (double *)(PyArray_DATA(capi_rw_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_objfun_in_midaco__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&l,&n,&nint,&m,&me,x,xl,xu,f,g,param,&maxeval,&maxtime,&ifail,&neval,&iprint,&printeval,&iout1,&iout2,ifile1,ifile2,license_key,&liw,iw,&lrw,rw,objfun_cptr,slen(ifile1),slen(ifile2),slen(license_key));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_int(ifail_capi,&ifail);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(neval_capi,&neval);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("N",capi_iw_tmp);
/*closepyobjfrom*/
  } /*if (f2py_success) of neval pyobjfrom*/
  } /*if (f2py_success) of ifail pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_rw_tmp!=rw_capi) {
    Py_XDECREF(capi_rw_tmp); }
  }  /*if (capi_rw_tmp == NULL) ... else of rw*/
  /* End of cleaning variable rw */
  }  /*if (capi_iw_tmp == NULL) ... else of iw*/
  /* End of cleaning variable iw */
  if((PyObject *)capi_g_tmp!=g_capi) {
    Py_XDECREF(capi_g_tmp); }
  }  /*if (capi_g_tmp == NULL) ... else of g*/
  /* End of cleaning variable g */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  if((PyObject *)capi_xu_tmp!=xu_capi) {
    Py_XDECREF(capi_xu_tmp); }
  }  /*if (capi_xu_tmp == NULL) ... else of xu*/
  /* End of cleaning variable xu */
  if((PyObject *)capi_xl_tmp!=xl_capi) {
    Py_XDECREF(capi_xl_tmp); }
  }  /*if (capi_xl_tmp == NULL) ... else of xl*/
  /* End of cleaning variable xl */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
    CFUNCSMESS("Restoring jmpbuf for `objfun`.\n");
    cb_objfun_in_midaco__user__routines_capi = objfun_capi;
    Py_DECREF(cb_objfun_in_midaco__user__routines_args_capi);
    cb_objfun_in_midaco__user__routines_args_capi = objfun_args_capi;
    cb_objfun_in_midaco__user__routines_nofargs = objfun_nofargs_capi;
    memcpy(&cb_objfun_in_midaco__user__routines_jmpbuf,&objfun_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable objfun */
  } /*if (f2py_success) of lrw*/
  /* End of cleaning variable lrw */
  } /*if (f2py_success) of liw*/
  /* End of cleaning variable liw */
    STRINGFREE(license_key);
  }  /*if (f2py_success) of license_key*/
  /* End of cleaning variable license_key */
    STRINGFREE(ifile2);
  }  /*if (f2py_success) of ifile2*/
  /* End of cleaning variable ifile2 */
    STRINGFREE(ifile1);
  }  /*if (f2py_success) of ifile1*/
  /* End of cleaning variable ifile1 */
  } /*if (f2py_success) of iout2*/
  /* End of cleaning variable iout2 */
  } /*if (f2py_success) of iout1*/
  /* End of cleaning variable iout1 */
  } /*if (f2py_success) of printeval*/
  /* End of cleaning variable printeval */
  } /*if (f2py_success) of iprint*/
  /* End of cleaning variable iprint */
  } /*if (f2py_success) of neval*/
  /* End of cleaning variable neval */
  } /*if (f2py_success) of ifail*/
  /* End of cleaning variable ifail */
  } /*if (f2py_success) of maxtime*/
  /* End of cleaning variable maxtime */
  } /*if (f2py_success) of maxeval*/
  /* End of cleaning variable maxeval */
  if((PyObject *)capi_param_tmp!=param_capi) {
    Py_XDECREF(capi_param_tmp); }
  }  /*if (capi_param_tmp == NULL) ... else of param*/
  /* End of cleaning variable param */
  } /*if (f2py_success) of me*/
  /* End of cleaning variable me */
  } /*if (f2py_success) of m*/
  /* End of cleaning variable m */
  } /*if (f2py_success) of nint*/
  /* End of cleaning variable nint */
  } /*if (f2py_success) of n*/
  /* End of cleaning variable n */
  } /*if (f2py_success) of l*/
  /* End of cleaning variable l */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/***************************** end of midaco_wrap *****************************/

/********************************** openunit **********************************/
static char doc_f2py_rout_midaco_openunit[] = "\
ierror = openunit(unitnum,filename,filestatus,fileaction)\n\nWrapper for ``openunit``.\
\n\nParameters\n----------\n"
"unitnum : input int\n"
"filename : input string(len=-1)\n"
"filestatus : input string(len=-1)\n"
"fileaction : input string(len=-1)\n"
"\nReturns\n-------\n"
"ierror : int";
/* extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout_midaco_openunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,string,string,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  string filestatus = NULL;
  int slen(filestatus);
  PyObject *filestatus_capi = Py_None;
  string fileaction = NULL;
  int slen(fileaction);
  PyObject *fileaction_capi = Py_None;
  int ierror = 0;
  static char *capi_kwlist[] = {"unitnum","filename","filestatus","fileaction",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:midaco.openunit",\
    capi_kwlist,&unitnum_capi,&filename_capi,&filestatus_capi,&fileaction_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"midaco.openunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 2nd argument `filename' of midaco.openunit to C string");
  if (f2py_success) {
  /* Processing variable filestatus */
  slen(filestatus) = -1;
  f2py_success = string_from_pyobj(&filestatus,&slen(filestatus),"",filestatus_capi,"string_from_pyobj failed in converting 3rd argument `filestatus' of midaco.openunit to C string");
  if (f2py_success) {
  /* Processing variable fileaction */
  slen(fileaction) = -1;
  f2py_success = string_from_pyobj(&fileaction,&slen(fileaction),"",fileaction_capi,"string_from_pyobj failed in converting 4th argument `fileaction' of midaco.openunit to C string");
  if (f2py_success) {
  /* Processing variable ierror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum,filename,filestatus,fileaction,&ierror,slen(filename),slen(filestatus),slen(fileaction));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ierror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierror */
    STRINGFREE(fileaction);
  }  /*if (f2py_success) of fileaction*/
  /* End of cleaning variable fileaction */
    STRINGFREE(filestatus);
  }  /*if (f2py_success) of filestatus*/
  /* End of cleaning variable filestatus */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of openunit ******************************/

/********************************** pyflush **********************************/
static char doc_f2py_rout_midaco_pyflush[] = "\
pyflush(unitnum)\n\nWrapper for ``pyflush``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(pyflush,PYFLUSH)(int*); */
static PyObject *f2py_rout_midaco_pyflush(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:midaco.pyflush",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"midaco.pyflush() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of pyflush *******************************/

/********************************* closeunit *********************************/
static char doc_f2py_rout_midaco_closeunit[] = "\
closeunit(unitnum)\n\nWrapper for ``closeunit``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(closeunit,CLOSEUNIT)(int*); */
static PyObject *f2py_rout_midaco_closeunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:midaco.closeunit",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"midaco.closeunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of closeunit ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"midaco_wrap",-1,{{-1}},0,(char *)F_FUNC_US(midaco_wrap,MIDACO_WRAP),(f2py_init_func)f2py_rout_midaco_midaco_wrap,doc_f2py_rout_midaco_midaco_wrap},
  {"openunit",-1,{{-1}},0,(char *)F_FUNC(openunit,OPENUNIT),(f2py_init_func)f2py_rout_midaco_openunit,doc_f2py_rout_midaco_openunit},
  {"pyflush",-1,{{-1}},0,(char *)F_FUNC(pyflush,PYFLUSH),(f2py_init_func)f2py_rout_midaco_pyflush,doc_f2py_rout_midaco_pyflush},
  {"closeunit",-1,{{-1}},0,(char *)F_FUNC(closeunit,CLOSEUNIT),(f2py_init_func)f2py_rout_midaco_closeunit,doc_f2py_rout_midaco_closeunit},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "midaco",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_midaco(void) {
#else
#define RETVAL
PyMODINIT_FUNC initmidaco(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = midaco_module = PyModule_Create(&moduledef);
#else
  m = midaco_module = Py_InitModule("midaco", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module midaco (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'midaco' is auto-generated with f2py (version:2).\nFunctions:\n"
"  iw = midaco_wrap(l,n,nint,m,me,x,xl,xu,f,g,param,maxeval,maxtime,ifail,neval,iprint,printeval,iout1,iout2,ifile1,ifile2,license_key,liw,iw,lrw,rw,objfun,objfun_extra_args=())\n"
"  ierror = openunit(unitnum,filename,filestatus,fileaction)\n"
"  pyflush(unitnum)\n"
"  closeunit(unitnum)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  midaco_error = PyErr_NewException ("midaco.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"midaco");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
