C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitoutdat(setupfunc)
      external setupfunc
      logical iprintctl(7)
      integer iprintinn
      integer iprintout
      integer nprint
      integer mprint
      common /outdat/ iprintctl,iprintinn,iprintout,nprint,mprint
      call setupfunc(iprintctl,iprintinn,iprintout,nprint,mprint)
      end

      subroutine f2pyinitmachcon(setupfunc)
      external setupfunc
      double precision bignum
      double precision macheps
      double precision macheps12
      double precision macheps13
      double precision macheps23
      common /machcon/ bignum,macheps,macheps12,macheps13,macheps2
     &3
      call setupfunc(bignum,macheps,macheps12,macheps13,macheps23)
      end

      subroutine f2pyinitsladat(setupfunc)
      external setupfunc
      integer slaind(5000)
      integer nws
      logical slacks
      common /sladat/ slaind,nws,slacks
      call setupfunc(slaind,nws,slacks)
      end

      subroutine f2pyinitfixvar(setupfunc)
      external setupfunc
      double precision y(5000)
      integer ycor(5000)
      integer yind(5001)
      logical yset
      logical rmfixv
      common /fixvar/ y,ycor,yind,yset,rmfixv
      call setupfunc(y,ycor,yind,yset,rmfixv)
      end

      subroutine f2pyinitalgparam(setupfunc)
      external setupfunc
      logical fcoded
      logical gcoded
      logical hcoded
      logical ccoded
      logical jaccoded
      logical hccoded
      logical hlcoded
      logical hlpcoded
      logical fccoded
      logical gjaccoded
      logical firstde
      logical truehl
      logical ignoref
      logical skipacc
      logical sclsys
      logical innercall
      logical useustp
      character innslvr
      character hptype
      logical safemode
      common /algparam/ fcoded,gcoded,hcoded,ccoded,jaccoded,hccod
     &ed,hlcoded,hlpcoded,fccoded,gjaccoded,firstde,truehl,ignoref,skipa
     &cc,sclsys,innercall,useustp,innslvr,hptype,safemode
      call setupfunc(fcoded,gcoded,hcoded,ccoded,jaccoded,hccoded,
     &hlcoded,hlpcoded,fccoded,gjaccoded,firstde,truehl,ignoref,skipacc,
     &sclsys,innercall,useustp,innslvr,hptype,safemode)
      end

      subroutine f2pyinitscadat(setupfunc)
      external setupfunc
      double precision sc(5000)
      double precision usc(5000)
      double precision sf
      double precision usf
      logical scale
      common /scadat/ sc,usc,sf,usf,scale
      call setupfunc(sc,usc,sf,usf,scale)
      end

      subroutine f2pyinitcounters(setupfunc)
      external setupfunc
      integer eccnt(5000)
      integer ehccnt(5000)
      integer ejccnt(5000)
      integer efcnt
      integer efccnt
      integer egcnt
      integer egjccnt
      integer ehcnt
      integer ehlcnt
      integer ehlpcnt
      integer fcnt
      common /counters/ eccnt,ehccnt,ejccnt,efcnt,efccnt,egcnt,egj
     &ccnt,ehcnt,ehlcnt,ehlpcnt,fcnt
      call setupfunc(eccnt,ehccnt,ejccnt,efcnt,efccnt,egcnt,egjccn
     &t,ehcnt,ehlcnt,ehlpcnt,fcnt)
      end

      subroutine f2pyinithdata(setupfunc)
      external setupfunc
      double precision hval(100000)
      integer hlin(100000)
      integer hcol(100000)
      integer hnnz
      common /hdata/ hval,hlin,hcol,hnnz
      call setupfunc(hval,hlin,hcol,hnnz)
      end


