system_name = "Signal Generator"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 10

is_discrete = true
is_hybrid = false

[parameters]
  # step | impulse | sin
  response_type = "step"
  # Nz | ps
  output_to_excite = "Nz"

[topics]
  [topics.outputs]
      msg = "autopilot_output.msg"
