C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitcmache(setupfunc)
      external setupfunc
      double precision qleps
      common /cmache/ qleps
      call setupfunc(qleps)
      end

      subroutine f2pyinitfsqpp1(setupfunc)
      external setupfunc
      integer nnineq
      integer m
      integer ncallg
      integer ncallf
      integer modd
      integer lstype
      integer nstop
      common /fsqpp1/ nnineq,m,ncallg,ncallf,modd,lstype,nstop
      call setupfunc(nnineq,m,ncallg,ncallf,modd,lstype,nstop)
      end

      subroutine f2pyinitfsqpp2(setupfunc)
      external setupfunc
      integer io
      integer ipp
      integer ipsp
      integer ipyes
      integer info
      integer idummy
      integer iter
      integer initvl
      common /fsqpp2/ io,ipp,ipsp,ipyes,info,idummy,iter,initvl
      call setupfunc(io,ipp,ipsp,ipyes,info,idummy,iter,initvl)
      end

      subroutine f2pyinitfsqpp3(setupfunc)
      external setupfunc
      double precision epsmac
      double precision rteps
      double precision upert
      double precision valnom
      common /fsqpp3/ epsmac,rteps,upert,valnom
      call setupfunc(epsmac,rteps,upert,valnom)
      end

      subroutine f2pyinitfsqpp4(setupfunc)
      external setupfunc
      logical rolis1
      logical d0is0
      common /fsqpp4/ rolis1,d0is0
      call setupfunc(rolis1,d0is0)
      end

      subroutine f2pyinitfsqpq2(setupfunc)
      external setupfunc
      integer maxit
      common /fsqpq2/ maxit
      call setupfunc(maxit)
      end

      subroutine f2pyinitfsqpq1(setupfunc)
      external setupfunc
      double precision big
      double precision tolfea
      common /fsqpq1/ big,tolfea
      call setupfunc(big,tolfea)
      end


