/* File: ffsqpmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Apr 11 17:22:54 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *ffsqp_error;
static PyObject *ffsqp_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_gradcn_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);
typedef void(*cb_gradob_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);
typedef void(*cb_constr_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);
typedef void(*cb_obj_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"ffsqp.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(signed char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = ffsqp_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int try_pyarr_from_int(PyObject* obj,int* v) {
    TRYPYARRAYTEMPLATE(int,'i');
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = ffsqp_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(ffsqp_error,errmess);
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = ffsqp_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(ffsqp,FFSQP)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,double*,int*,cb_obj_in_ffsqp__user__routines_typedef,cb_constr_in_ffsqp__user__routines_typedef,cb_gradob_in_ffsqp__user__routines_typedef,cb_gradcn_in_ffsqp__user__routines_typedef,int*,string,size_t);
extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t);
extern void F_FUNC(pyflush,PYFLUSH)(int*);
extern void F_FUNC(closeunit,CLOSEUNIT)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************** cb_obj_in_ffsqp__user__routines **********************/
PyObject *cb_obj_in_ffsqp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_obj_in_ffsqp__user__routines_args_capi = NULL;
int cb_obj_in_ffsqp__user__routines_nofargs = 0;
jmp_buf cb_obj_in_ffsqp__user__routines_jmpbuf;
/*typedef void(*cb_obj_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);*/
static void cb_obj_in_ffsqp__user__routines (int *nparam_cb_capi,int *j_cb_capi,double *x,double *fj_cb_capi) {
  PyTupleObject *capi_arglist = cb_obj_in_ffsqp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int nparam=(*nparam_cb_capi);
  int j=(*j_cb_capi);
  double fj=(*fj_cb_capi);
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_obj_in_ffsqp__user__routines (maxnofargs=4(-0))\n");
  CFUNCSMESSPY("cb:cb_obj_in_ffsqp__user__routines_capi=",cb_obj_in_ffsqp__user__routines_capi);
  if (cb_obj_in_ffsqp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_obj_in_ffsqp__user__routines_capi = PyObject_GetAttrString(ffsqp_module,"obj");
  }
  if (cb_obj_in_ffsqp__user__routines_capi==NULL) {
    PyErr_SetString(ffsqp_error,"cb: Callback obj not defined (as an argument or module ffsqp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_obj_in_ffsqp__user__routines_capi)) {
  cb_obj_in_ffsqp__user__routines_typedef cb_obj_in_ffsqp__user__routines_cptr;
  cb_obj_in_ffsqp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_obj_in_ffsqp__user__routines_capi);
  (*cb_obj_in_ffsqp__user__routines_cptr)(nparam_cb_capi,j_cb_capi,x,fj_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(ffsqp_module,"obj_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(ffsqp_error,"Failed to convert ffsqp.obj_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(ffsqp_error,"Callback obj argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=nparam;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_obj_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nparam)))
      goto capi_fail;
  if (cb_obj_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(j)))
      goto capi_fail;
  if (cb_obj_in_ffsqp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_obj_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(fj)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function obj.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_obj_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_obj_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,fj_cb_capi,double,"double_from_pyobj failed in converting argument fj of call-back function cb_obj_in_ffsqp__user__routines to C double\n");
  CFUNCSMESS("cb:cb_obj_in_ffsqp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_obj_in_ffsqp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_obj_in_ffsqp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/******************* end of cb_obj_in_ffsqp__user__routines *******************/


/********************* cb_constr_in_ffsqp__user__routines *********************/
PyObject *cb_constr_in_ffsqp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_constr_in_ffsqp__user__routines_args_capi = NULL;
int cb_constr_in_ffsqp__user__routines_nofargs = 0;
jmp_buf cb_constr_in_ffsqp__user__routines_jmpbuf;
/*typedef void(*cb_constr_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);*/
static void cb_constr_in_ffsqp__user__routines (int *nparam_cb_capi,int *j_cb_capi,double *x,double *gj_cb_capi) {
  PyTupleObject *capi_arglist = cb_constr_in_ffsqp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int nparam=(*nparam_cb_capi);
  int j=(*j_cb_capi);
  double gj=(*gj_cb_capi);
  npy_intp x_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_constr_in_ffsqp__user__routines (maxnofargs=4(-0))\n");
  CFUNCSMESSPY("cb:cb_constr_in_ffsqp__user__routines_capi=",cb_constr_in_ffsqp__user__routines_capi);
  if (cb_constr_in_ffsqp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_constr_in_ffsqp__user__routines_capi = PyObject_GetAttrString(ffsqp_module,"constr");
  }
  if (cb_constr_in_ffsqp__user__routines_capi==NULL) {
    PyErr_SetString(ffsqp_error,"cb: Callback constr not defined (as an argument or module ffsqp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_constr_in_ffsqp__user__routines_capi)) {
  cb_constr_in_ffsqp__user__routines_typedef cb_constr_in_ffsqp__user__routines_cptr;
  cb_constr_in_ffsqp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_constr_in_ffsqp__user__routines_capi);
  (*cb_constr_in_ffsqp__user__routines_cptr)(nparam_cb_capi,j_cb_capi,x,gj_cb_capi);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(ffsqp_module,"constr_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(ffsqp_error,"Failed to convert ffsqp.constr_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(ffsqp_error,"Callback constr argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=nparam;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_constr_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nparam)))
      goto capi_fail;
  if (cb_constr_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(j)))
      goto capi_fail;
  if (cb_constr_in_ffsqp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_constr_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(gj)))
      goto capi_fail;
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function constr.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_constr_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_constr_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,gj_cb_capi,double,"double_from_pyobj failed in converting argument gj of call-back function cb_constr_in_ffsqp__user__routines to C double\n");
  CFUNCSMESS("cb:cb_constr_in_ffsqp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_constr_in_ffsqp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_constr_in_ffsqp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_constr_in_ffsqp__user__routines *****************/


/********************* cb_gradob_in_ffsqp__user__routines *********************/
PyObject *cb_gradob_in_ffsqp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_gradob_in_ffsqp__user__routines_args_capi = NULL;
int cb_gradob_in_ffsqp__user__routines_nofargs = 0;
jmp_buf cb_gradob_in_ffsqp__user__routines_jmpbuf;
/*typedef void(*cb_gradob_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);*/
static void cb_gradob_in_ffsqp__user__routines (int *nparam_cb_capi,int *j_cb_capi,double *x,double *gradfj) {
  PyTupleObject *capi_arglist = cb_gradob_in_ffsqp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int nparam=(*nparam_cb_capi);
  int j=(*j_cb_capi);
  npy_intp x_Dims[1] = {-1};
  npy_intp gradfj_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_gradob_in_ffsqp__user__routines (maxnofargs=5(-0))\n");
  CFUNCSMESSPY("cb:cb_gradob_in_ffsqp__user__routines_capi=",cb_gradob_in_ffsqp__user__routines_capi);
  if (cb_gradob_in_ffsqp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_gradob_in_ffsqp__user__routines_capi = PyObject_GetAttrString(ffsqp_module,"gradob");
  }
  if (cb_gradob_in_ffsqp__user__routines_capi==NULL) {
    PyErr_SetString(ffsqp_error,"cb: Callback gradob not defined (as an argument or module ffsqp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_gradob_in_ffsqp__user__routines_capi)) {
  cb_gradob_in_ffsqp__user__routines_typedef cb_gradob_in_ffsqp__user__routines_cptr;
  cb_gradob_in_ffsqp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_gradob_in_ffsqp__user__routines_capi);
  (*cb_gradob_in_ffsqp__user__routines_cptr)(nparam_cb_capi,j_cb_capi,x,gradfj);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(ffsqp_module,"gradob_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(ffsqp_error,"Failed to convert ffsqp.gradob_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(ffsqp_error,"Callback gradob argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=nparam;
  gradfj_Dims[0]=nparam;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_gradob_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nparam)))
      goto capi_fail;
  if (cb_gradob_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(j)))
      goto capi_fail;
  if (cb_gradob_in_ffsqp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_gradob_in_ffsqp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,gradfj_Dims,NPY_DOUBLE,NULL,(char*)gradfj,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function gradob.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_gradob_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_gradob_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,gradfj_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(gradfj,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_gradob_in_ffsqp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_gradob_in_ffsqp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_gradob_in_ffsqp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_gradob_in_ffsqp__user__routines *****************/


/********************* cb_gradcn_in_ffsqp__user__routines *********************/
PyObject *cb_gradcn_in_ffsqp__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_gradcn_in_ffsqp__user__routines_args_capi = NULL;
int cb_gradcn_in_ffsqp__user__routines_nofargs = 0;
jmp_buf cb_gradcn_in_ffsqp__user__routines_jmpbuf;
/*typedef void(*cb_gradcn_in_ffsqp__user__routines_typedef)(int *,int *,double *,double *);*/
static void cb_gradcn_in_ffsqp__user__routines (int *nparam_cb_capi,int *j_cb_capi,double *x,double *gradgj) {
  PyTupleObject *capi_arglist = cb_gradcn_in_ffsqp__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int nparam=(*nparam_cb_capi);
  int j=(*j_cb_capi);
  npy_intp x_Dims[1] = {-1};
  npy_intp gradgj_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_gradcn_in_ffsqp__user__routines (maxnofargs=5(-0))\n");
  CFUNCSMESSPY("cb:cb_gradcn_in_ffsqp__user__routines_capi=",cb_gradcn_in_ffsqp__user__routines_capi);
  if (cb_gradcn_in_ffsqp__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_gradcn_in_ffsqp__user__routines_capi = PyObject_GetAttrString(ffsqp_module,"gradcn");
  }
  if (cb_gradcn_in_ffsqp__user__routines_capi==NULL) {
    PyErr_SetString(ffsqp_error,"cb: Callback gradcn not defined (as an argument or module ffsqp attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_gradcn_in_ffsqp__user__routines_capi)) {
  cb_gradcn_in_ffsqp__user__routines_typedef cb_gradcn_in_ffsqp__user__routines_cptr;
  cb_gradcn_in_ffsqp__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_gradcn_in_ffsqp__user__routines_capi);
  (*cb_gradcn_in_ffsqp__user__routines_cptr)(nparam_cb_capi,j_cb_capi,x,gradgj);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(ffsqp_module,"gradcn_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(ffsqp_error,"Failed to convert ffsqp.gradcn_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(ffsqp_error,"Callback gradcn argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  x_Dims[0]=nparam;
  gradgj_Dims[0]=nparam;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_gradcn_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(nparam)))
      goto capi_fail;
  if (cb_gradcn_in_ffsqp__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(j)))
      goto capi_fail;
  if (cb_gradcn_in_ffsqp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,x_Dims,NPY_DOUBLE,NULL,(char*)x,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_gradcn_in_ffsqp__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,gradgj_Dims,NPY_DOUBLE,NULL,(char*)gradgj,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function gradcn.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_gradcn_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_gradcn_in_ffsqp__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,gradgj_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(gradgj,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_gradcn_in_ffsqp__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_gradcn_in_ffsqp__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_gradcn_in_ffsqp__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/***************** end of cb_gradcn_in_ffsqp__user__routines *****************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/*********************************** ffsqp ***********************************/
static char doc_f2py_rout_ffsqp_ffsqp[] = "\
ffsqp(nparam,nf,nineqn,nineq,neqn,neq,mode,iprint,miter,inform,bigbnd,eps,epseqn,udelta,bl,bu,x,f,g,iw,iwsize,w,nwsize,obj,constr,gradob,gradcn,iounit,ifile,[obj_extra_args,constr_extra_args,gradob_extra_args,gradcn_extra_args])\n\nWrapper for ``ffsqp``.\
\n\nParameters\n----------\n"
"nparam : input int\n"
"nf : input int\n"
"nineqn : input int\n"
"nineq : input int\n"
"neqn : input int\n"
"neq : input int\n"
"mode : input int\n"
"iprint : input int\n"
"miter : input int\n"
"inform : in/output rank-0 array(int,'i')\n"
"bigbnd : input float\n"
"eps : input float\n"
"epseqn : input float\n"
"udelta : input float\n"
"bl : input rank-1 array('d') with bounds (nparam)\n"
"bu : input rank-1 array('d') with bounds (nparam)\n"
"x : in/output rank-1 array('d') with bounds (nparam)\n"
"f : in/output rank-1 array('d') with bounds (nf)\n"
"g : in/output rank-1 array('d') with bounds (nineq+neq)\n"
"iw : input rank-1 array('i') with bounds (iwsize)\n"
"iwsize : input int\n"
"w : in/output rank-1 array('d') with bounds (nwsize)\n"
"nwsize : input int\n"
"obj : call-back function\n"
"constr : call-back function\n"
"gradob : call-back function\n"
"gradcn : call-back function\n"
"iounit : input int\n"
"ifile : input string(len=-1)\n"
"\nOther Parameters\n----------------\n"
"obj_extra_args : input tuple, optional\n    Default: ()\n"
"constr_extra_args : input tuple, optional\n    Default: ()\n"
"gradob_extra_args : input tuple, optional\n    Default: ()\n"
"gradcn_extra_args : input tuple, optional\n    Default: ()\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def obj(nparam,j,x,fj): return fj\n\
  Required arguments:\n"
"    nparam : input int\n"
"    j : input int\n"
"    x : input rank-1 array('d') with bounds (nparam)\n"
"    fj : input float\n"
"  Return objects:\n"
"    fj : float\n"
"  def constr(nparam,j,x,gj): return gj\n\
  Required arguments:\n"
"    nparam : input int\n"
"    j : input int\n"
"    x : input rank-1 array('d') with bounds (nparam)\n"
"    gj : input float\n"
"  Return objects:\n"
"    gj : float\n"
"  def gradob(nparam,j,x,gradfj,obj): return gradfj\n\
  Required arguments:\n"
"    nparam : input int\n"
"    j : input int\n"
"    x : input rank-1 array('d') with bounds (nparam)\n"
"    gradfj : input rank-1 array('d') with bounds (nparam)\n"
"    obj : call-back function\n"
"  Return objects:\n"
"    gradfj : rank-1 array('d') with bounds (nparam)\n"
"  def gradcn(nparam,j,x,gradgj,obj): return gradgj\n\
  Required arguments:\n"
"    nparam : input int\n"
"    j : input int\n"
"    x : input rank-1 array('d') with bounds (nparam)\n"
"    gradgj : input rank-1 array('d') with bounds (nparam)\n"
"    obj : call-back function\n"
"  Return objects:\n"
"    gradgj : rank-1 array('d') with bounds (nparam)";
/* extern void F_FUNC(ffsqp,FFSQP)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,double*,int*,cb_obj_in_ffsqp__user__routines_typedef,cb_constr_in_ffsqp__user__routines_typedef,cb_gradob_in_ffsqp__user__routines_typedef,cb_gradcn_in_ffsqp__user__routines_typedef,int*,string,size_t); */
static PyObject *f2py_rout_ffsqp_ffsqp(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,double*,double*,double*,double*,int*,int*,double*,int*,cb_obj_in_ffsqp__user__routines_typedef,cb_constr_in_ffsqp__user__routines_typedef,cb_gradob_in_ffsqp__user__routines_typedef,cb_gradcn_in_ffsqp__user__routines_typedef,int*,string,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int nparam = 0;
  PyObject *nparam_capi = Py_None;
  int nf = 0;
  PyObject *nf_capi = Py_None;
  int nineqn = 0;
  PyObject *nineqn_capi = Py_None;
  int nineq = 0;
  PyObject *nineq_capi = Py_None;
  int neqn = 0;
  PyObject *neqn_capi = Py_None;
  int neq = 0;
  PyObject *neq_capi = Py_None;
  int mode = 0;
  PyObject *mode_capi = Py_None;
  int iprint = 0;
  PyObject *iprint_capi = Py_None;
  int miter = 0;
  PyObject *miter_capi = Py_None;
  int inform = 0;
  PyObject *inform_capi = Py_None;
  double bigbnd = 0;
  PyObject *bigbnd_capi = Py_None;
  double eps = 0;
  PyObject *eps_capi = Py_None;
  double epseqn = 0;
  PyObject *epseqn_capi = Py_None;
  double udelta = 0;
  PyObject *udelta_capi = Py_None;
  double *bl = NULL;
  npy_intp bl_Dims[1] = {-1};
  const int bl_Rank = 1;
  PyArrayObject *capi_bl_tmp = NULL;
  int capi_bl_intent = 0;
  PyObject *bl_capi = Py_None;
  double *bu = NULL;
  npy_intp bu_Dims[1] = {-1};
  const int bu_Rank = 1;
  PyArrayObject *capi_bu_tmp = NULL;
  int capi_bu_intent = 0;
  PyObject *bu_capi = Py_None;
  double *x = NULL;
  npy_intp x_Dims[1] = {-1};
  const int x_Rank = 1;
  PyArrayObject *capi_x_tmp = NULL;
  int capi_x_intent = 0;
  PyObject *x_capi = Py_None;
  double *f = NULL;
  npy_intp f_Dims[1] = {-1};
  const int f_Rank = 1;
  PyArrayObject *capi_f_tmp = NULL;
  int capi_f_intent = 0;
  PyObject *f_capi = Py_None;
  double *g = NULL;
  npy_intp g_Dims[1] = {-1};
  const int g_Rank = 1;
  PyArrayObject *capi_g_tmp = NULL;
  int capi_g_intent = 0;
  PyObject *g_capi = Py_None;
  int *iw = NULL;
  npy_intp iw_Dims[1] = {-1};
  const int iw_Rank = 1;
  PyArrayObject *capi_iw_tmp = NULL;
  int capi_iw_intent = 0;
  PyObject *iw_capi = Py_None;
  int iwsize = 0;
  PyObject *iwsize_capi = Py_None;
  double *w = NULL;
  npy_intp w_Dims[1] = {-1};
  const int w_Rank = 1;
  PyArrayObject *capi_w_tmp = NULL;
  int capi_w_intent = 0;
  PyObject *w_capi = Py_None;
  int nwsize = 0;
  PyObject *nwsize_capi = Py_None;
  PyObject *obj_capi = Py_None;
  PyTupleObject *obj_xa_capi = NULL;
  PyTupleObject *obj_args_capi = NULL;
  int obj_nofargs_capi = 0;
  cb_obj_in_ffsqp__user__routines_typedef obj_cptr;
  PyObject *constr_capi = Py_None;
  PyTupleObject *constr_xa_capi = NULL;
  PyTupleObject *constr_args_capi = NULL;
  int constr_nofargs_capi = 0;
  cb_constr_in_ffsqp__user__routines_typedef constr_cptr;
  PyObject *gradob_capi = Py_None;
  PyTupleObject *gradob_xa_capi = NULL;
  PyTupleObject *gradob_args_capi = NULL;
  int gradob_nofargs_capi = 0;
  cb_gradob_in_ffsqp__user__routines_typedef gradob_cptr;
  PyObject *gradcn_capi = Py_None;
  PyTupleObject *gradcn_xa_capi = NULL;
  PyTupleObject *gradcn_args_capi = NULL;
  int gradcn_nofargs_capi = 0;
  cb_gradcn_in_ffsqp__user__routines_typedef gradcn_cptr;
  int iounit = 0;
  PyObject *iounit_capi = Py_None;
  string ifile = NULL;
  int slen(ifile);
  PyObject *ifile_capi = Py_None;
  static char *capi_kwlist[] = {"nparam","nf","nineqn","nineq","neqn","neq","mode","iprint","miter","inform","bigbnd","eps","epseqn","udelta","bl","bu","x","f","g","iw","iwsize","w","nwsize","obj","constr","gradob","gradcn","iounit","ifile","obj_extra_args","constr_extra_args","gradob_extra_args","gradcn_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOOO|O!O!O!O!:ffsqp.ffsqp",\
    capi_kwlist,&nparam_capi,&nf_capi,&nineqn_capi,&nineq_capi,&neqn_capi,&neq_capi,&mode_capi,&iprint_capi,&miter_capi,&inform_capi,&bigbnd_capi,&eps_capi,&epseqn_capi,&udelta_capi,&bl_capi,&bu_capi,&x_capi,&f_capi,&g_capi,&iw_capi,&iwsize_capi,&w_capi,&nwsize_capi,&obj_capi,&constr_capi,&gradob_capi,&gradcn_capi,&iounit_capi,&ifile_capi,&PyTuple_Type,&obj_xa_capi,&PyTuple_Type,&constr_xa_capi,&PyTuple_Type,&gradob_xa_capi,&PyTuple_Type,&gradcn_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable nparam */
    f2py_success = int_from_pyobj(&nparam,nparam_capi,"ffsqp.ffsqp() 1st argument (nparam) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nf */
    f2py_success = int_from_pyobj(&nf,nf_capi,"ffsqp.ffsqp() 2nd argument (nf) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nineqn */
    f2py_success = int_from_pyobj(&nineqn,nineqn_capi,"ffsqp.ffsqp() 3rd argument (nineqn) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nineq */
    f2py_success = int_from_pyobj(&nineq,nineq_capi,"ffsqp.ffsqp() 4th argument (nineq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable neqn */
    f2py_success = int_from_pyobj(&neqn,neqn_capi,"ffsqp.ffsqp() 5th argument (neqn) can't be converted to int");
  if (f2py_success) {
  /* Processing variable neq */
    f2py_success = int_from_pyobj(&neq,neq_capi,"ffsqp.ffsqp() 6th argument (neq) can't be converted to int");
  if (f2py_success) {
  /* Processing variable mode */
    f2py_success = int_from_pyobj(&mode,mode_capi,"ffsqp.ffsqp() 7th argument (mode) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iprint */
    f2py_success = int_from_pyobj(&iprint,iprint_capi,"ffsqp.ffsqp() 8th argument (iprint) can't be converted to int");
  if (f2py_success) {
  /* Processing variable miter */
    f2py_success = int_from_pyobj(&miter,miter_capi,"ffsqp.ffsqp() 9th argument (miter) can't be converted to int");
  if (f2py_success) {
  /* Processing variable inform */
    f2py_success = int_from_pyobj(&inform,inform_capi,"ffsqp.ffsqp() 10th argument (inform) can't be converted to int");
  if (f2py_success) {
  /* Processing variable bigbnd */
    f2py_success = double_from_pyobj(&bigbnd,bigbnd_capi,"ffsqp.ffsqp() 11st argument (bigbnd) can't be converted to double");
  if (f2py_success) {
  /* Processing variable eps */
    f2py_success = double_from_pyobj(&eps,eps_capi,"ffsqp.ffsqp() 12nd argument (eps) can't be converted to double");
  if (f2py_success) {
  /* Processing variable epseqn */
    f2py_success = double_from_pyobj(&epseqn,epseqn_capi,"ffsqp.ffsqp() 13rd argument (epseqn) can't be converted to double");
  if (f2py_success) {
  /* Processing variable udelta */
    f2py_success = double_from_pyobj(&udelta,udelta_capi,"ffsqp.ffsqp() 14th argument (udelta) can't be converted to double");
  if (f2py_success) {
  /* Processing variable iwsize */
    f2py_success = int_from_pyobj(&iwsize,iwsize_capi,"ffsqp.ffsqp() 21st argument (iwsize) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nwsize */
    f2py_success = int_from_pyobj(&nwsize,nwsize_capi,"ffsqp.ffsqp() 23rd argument (nwsize) can't be converted to int");
  if (f2py_success) {
  /* Processing variable obj */
if(F2PyCapsule_Check(obj_capi)) {
  obj_cptr = F2PyCapsule_AsVoidPtr(obj_capi);
} else {
  obj_cptr = cb_obj_in_ffsqp__user__routines;
}

  obj_nofargs_capi = cb_obj_in_ffsqp__user__routines_nofargs;
  if (create_cb_arglist(obj_capi,obj_xa_capi,4,0,&cb_obj_in_ffsqp__user__routines_nofargs,&obj_args_capi,"failed in processing argument list for call-back obj.")) {
    jmp_buf obj_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `obj`.\n");
    SWAP(obj_capi,cb_obj_in_ffsqp__user__routines_capi,PyObject);
    SWAP(obj_args_capi,cb_obj_in_ffsqp__user__routines_args_capi,PyTupleObject);
    memcpy(&obj_jmpbuf,&cb_obj_in_ffsqp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable constr */
if(F2PyCapsule_Check(constr_capi)) {
  constr_cptr = F2PyCapsule_AsVoidPtr(constr_capi);
} else {
  constr_cptr = cb_constr_in_ffsqp__user__routines;
}

  constr_nofargs_capi = cb_constr_in_ffsqp__user__routines_nofargs;
  if (create_cb_arglist(constr_capi,constr_xa_capi,4,0,&cb_constr_in_ffsqp__user__routines_nofargs,&constr_args_capi,"failed in processing argument list for call-back constr.")) {
    jmp_buf constr_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `constr`.\n");
    SWAP(constr_capi,cb_constr_in_ffsqp__user__routines_capi,PyObject);
    SWAP(constr_args_capi,cb_constr_in_ffsqp__user__routines_args_capi,PyTupleObject);
    memcpy(&constr_jmpbuf,&cb_constr_in_ffsqp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable gradob */
if(F2PyCapsule_Check(gradob_capi)) {
  gradob_cptr = F2PyCapsule_AsVoidPtr(gradob_capi);
} else {
  gradob_cptr = cb_gradob_in_ffsqp__user__routines;
}

  gradob_nofargs_capi = cb_gradob_in_ffsqp__user__routines_nofargs;
  if (create_cb_arglist(gradob_capi,gradob_xa_capi,5,0,&cb_gradob_in_ffsqp__user__routines_nofargs,&gradob_args_capi,"failed in processing argument list for call-back gradob.")) {
    jmp_buf gradob_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `gradob`.\n");
    SWAP(gradob_capi,cb_gradob_in_ffsqp__user__routines_capi,PyObject);
    SWAP(gradob_args_capi,cb_gradob_in_ffsqp__user__routines_args_capi,PyTupleObject);
    memcpy(&gradob_jmpbuf,&cb_gradob_in_ffsqp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable gradcn */
if(F2PyCapsule_Check(gradcn_capi)) {
  gradcn_cptr = F2PyCapsule_AsVoidPtr(gradcn_capi);
} else {
  gradcn_cptr = cb_gradcn_in_ffsqp__user__routines;
}

  gradcn_nofargs_capi = cb_gradcn_in_ffsqp__user__routines_nofargs;
  if (create_cb_arglist(gradcn_capi,gradcn_xa_capi,5,0,&cb_gradcn_in_ffsqp__user__routines_nofargs,&gradcn_args_capi,"failed in processing argument list for call-back gradcn.")) {
    jmp_buf gradcn_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `gradcn`.\n");
    SWAP(gradcn_capi,cb_gradcn_in_ffsqp__user__routines_capi,PyObject);
    SWAP(gradcn_args_capi,cb_gradcn_in_ffsqp__user__routines_args_capi,PyTupleObject);
    memcpy(&gradcn_jmpbuf,&cb_gradcn_in_ffsqp__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable iounit */
    f2py_success = int_from_pyobj(&iounit,iounit_capi,"ffsqp.ffsqp() 28th argument (iounit) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifile */
  slen(ifile) = -1;
  f2py_success = string_from_pyobj(&ifile,&slen(ifile),"",ifile_capi,"string_from_pyobj failed in converting 29th argument `ifile' of ffsqp.ffsqp to C string");
  if (f2py_success) {
  /* Processing variable bl */
  bl_Dims[0]=nparam;
  capi_bl_intent |= F2PY_INTENT_IN;
  capi_bl_tmp = array_from_pyobj(NPY_DOUBLE,bl_Dims,bl_Rank,capi_bl_intent,bl_capi);
  if (capi_bl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ffsqp_error,"failed in converting 15th argument `bl' of ffsqp.ffsqp to C/Fortran array" );
  } else {
    bl = (double *)(PyArray_DATA(capi_bl_tmp));

  /* Processing variable bu */
  bu_Dims[0]=nparam;
  capi_bu_intent |= F2PY_INTENT_IN;
  capi_bu_tmp = array_from_pyobj(NPY_DOUBLE,bu_Dims,bu_Rank,capi_bu_intent,bu_capi);
  if (capi_bu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ffsqp_error,"failed in converting 16th argument `bu' of ffsqp.ffsqp to C/Fortran array" );
  } else {
    bu = (double *)(PyArray_DATA(capi_bu_tmp));

  /* Processing variable x */
  x_Dims[0]=nparam;
  capi_x_intent |= F2PY_INTENT_INOUT;
  capi_x_tmp = array_from_pyobj(NPY_DOUBLE,x_Dims,x_Rank,capi_x_intent,x_capi);
  if (capi_x_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ffsqp_error,"failed in converting 17th argument `x' of ffsqp.ffsqp to C/Fortran array" );
  } else {
    x = (double *)(PyArray_DATA(capi_x_tmp));

  /* Processing variable f */
  f_Dims[0]=nf;
  capi_f_intent |= F2PY_INTENT_INOUT;
  capi_f_tmp = array_from_pyobj(NPY_DOUBLE,f_Dims,f_Rank,capi_f_intent,f_capi);
  if (capi_f_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ffsqp_error,"failed in converting 18th argument `f' of ffsqp.ffsqp to C/Fortran array" );
  } else {
    f = (double *)(PyArray_DATA(capi_f_tmp));

  /* Processing variable g */
  g_Dims[0]=nineq+neq;
  capi_g_intent |= F2PY_INTENT_INOUT;
  capi_g_tmp = array_from_pyobj(NPY_DOUBLE,g_Dims,g_Rank,capi_g_intent,g_capi);
  if (capi_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ffsqp_error,"failed in converting 19th argument `g' of ffsqp.ffsqp to C/Fortran array" );
  } else {
    g = (double *)(PyArray_DATA(capi_g_tmp));

  /* Processing variable iw */
  iw_Dims[0]=iwsize;
  capi_iw_intent |= F2PY_INTENT_IN;
  capi_iw_tmp = array_from_pyobj(NPY_INT,iw_Dims,iw_Rank,capi_iw_intent,iw_capi);
  if (capi_iw_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ffsqp_error,"failed in converting 20th argument `iw' of ffsqp.ffsqp to C/Fortran array" );
  } else {
    iw = (int *)(PyArray_DATA(capi_iw_tmp));

  /* Processing variable w */
  w_Dims[0]=nwsize;
  capi_w_intent |= F2PY_INTENT_INOUT;
  capi_w_tmp = array_from_pyobj(NPY_DOUBLE,w_Dims,w_Rank,capi_w_intent,w_capi);
  if (capi_w_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(ffsqp_error,"failed in converting 22nd argument `w' of ffsqp.ffsqp to C/Fortran array" );
  } else {
    w = (double *)(PyArray_DATA(capi_w_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_obj_in_ffsqp__user__routines_jmpbuf)) || (setjmp(cb_constr_in_ffsqp__user__routines_jmpbuf)) || (setjmp(cb_gradob_in_ffsqp__user__routines_jmpbuf)) || (setjmp(cb_gradcn_in_ffsqp__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&nparam,&nf,&nineqn,&nineq,&neqn,&neq,&mode,&iprint,&miter,&inform,&bigbnd,&eps,&epseqn,&udelta,bl,bu,x,f,g,iw,&iwsize,w,&nwsize,obj_cptr,constr_cptr,gradob_cptr,gradcn_cptr,&iounit,ifile,slen(ifile));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_int(inform_capi,&inform);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
  } /*if (f2py_success) of inform pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_w_tmp!=w_capi) {
    Py_XDECREF(capi_w_tmp); }
  }  /*if (capi_w_tmp == NULL) ... else of w*/
  /* End of cleaning variable w */
  if((PyObject *)capi_iw_tmp!=iw_capi) {
    Py_XDECREF(capi_iw_tmp); }
  }  /*if (capi_iw_tmp == NULL) ... else of iw*/
  /* End of cleaning variable iw */
  if((PyObject *)capi_g_tmp!=g_capi) {
    Py_XDECREF(capi_g_tmp); }
  }  /*if (capi_g_tmp == NULL) ... else of g*/
  /* End of cleaning variable g */
  if((PyObject *)capi_f_tmp!=f_capi) {
    Py_XDECREF(capi_f_tmp); }
  }  /*if (capi_f_tmp == NULL) ... else of f*/
  /* End of cleaning variable f */
  if((PyObject *)capi_x_tmp!=x_capi) {
    Py_XDECREF(capi_x_tmp); }
  }  /*if (capi_x_tmp == NULL) ... else of x*/
  /* End of cleaning variable x */
  if((PyObject *)capi_bu_tmp!=bu_capi) {
    Py_XDECREF(capi_bu_tmp); }
  }  /*if (capi_bu_tmp == NULL) ... else of bu*/
  /* End of cleaning variable bu */
  if((PyObject *)capi_bl_tmp!=bl_capi) {
    Py_XDECREF(capi_bl_tmp); }
  }  /*if (capi_bl_tmp == NULL) ... else of bl*/
  /* End of cleaning variable bl */
    STRINGFREE(ifile);
  }  /*if (f2py_success) of ifile*/
  /* End of cleaning variable ifile */
  } /*if (f2py_success) of iounit*/
  /* End of cleaning variable iounit */
    CFUNCSMESS("Restoring jmpbuf for `gradcn`.\n");
    cb_gradcn_in_ffsqp__user__routines_capi = gradcn_capi;
    Py_DECREF(cb_gradcn_in_ffsqp__user__routines_args_capi);
    cb_gradcn_in_ffsqp__user__routines_args_capi = gradcn_args_capi;
    cb_gradcn_in_ffsqp__user__routines_nofargs = gradcn_nofargs_capi;
    memcpy(&cb_gradcn_in_ffsqp__user__routines_jmpbuf,&gradcn_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable gradcn */
    CFUNCSMESS("Restoring jmpbuf for `gradob`.\n");
    cb_gradob_in_ffsqp__user__routines_capi = gradob_capi;
    Py_DECREF(cb_gradob_in_ffsqp__user__routines_args_capi);
    cb_gradob_in_ffsqp__user__routines_args_capi = gradob_args_capi;
    cb_gradob_in_ffsqp__user__routines_nofargs = gradob_nofargs_capi;
    memcpy(&cb_gradob_in_ffsqp__user__routines_jmpbuf,&gradob_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable gradob */
    CFUNCSMESS("Restoring jmpbuf for `constr`.\n");
    cb_constr_in_ffsqp__user__routines_capi = constr_capi;
    Py_DECREF(cb_constr_in_ffsqp__user__routines_args_capi);
    cb_constr_in_ffsqp__user__routines_args_capi = constr_args_capi;
    cb_constr_in_ffsqp__user__routines_nofargs = constr_nofargs_capi;
    memcpy(&cb_constr_in_ffsqp__user__routines_jmpbuf,&constr_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable constr */
    CFUNCSMESS("Restoring jmpbuf for `obj`.\n");
    cb_obj_in_ffsqp__user__routines_capi = obj_capi;
    Py_DECREF(cb_obj_in_ffsqp__user__routines_args_capi);
    cb_obj_in_ffsqp__user__routines_args_capi = obj_args_capi;
    cb_obj_in_ffsqp__user__routines_nofargs = obj_nofargs_capi;
    memcpy(&cb_obj_in_ffsqp__user__routines_jmpbuf,&obj_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable obj */
  } /*if (f2py_success) of nwsize*/
  /* End of cleaning variable nwsize */
  } /*if (f2py_success) of iwsize*/
  /* End of cleaning variable iwsize */
  } /*if (f2py_success) of udelta*/
  /* End of cleaning variable udelta */
  } /*if (f2py_success) of epseqn*/
  /* End of cleaning variable epseqn */
  } /*if (f2py_success) of eps*/
  /* End of cleaning variable eps */
  } /*if (f2py_success) of bigbnd*/
  /* End of cleaning variable bigbnd */
  } /*if (f2py_success) of inform*/
  /* End of cleaning variable inform */
  } /*if (f2py_success) of miter*/
  /* End of cleaning variable miter */
  } /*if (f2py_success) of iprint*/
  /* End of cleaning variable iprint */
  } /*if (f2py_success) of mode*/
  /* End of cleaning variable mode */
  } /*if (f2py_success) of neq*/
  /* End of cleaning variable neq */
  } /*if (f2py_success) of neqn*/
  /* End of cleaning variable neqn */
  } /*if (f2py_success) of nineq*/
  /* End of cleaning variable nineq */
  } /*if (f2py_success) of nineqn*/
  /* End of cleaning variable nineqn */
  } /*if (f2py_success) of nf*/
  /* End of cleaning variable nf */
  } /*if (f2py_success) of nparam*/
  /* End of cleaning variable nparam */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of ffsqp ********************************/

/********************************** openunit **********************************/
static char doc_f2py_rout_ffsqp_openunit[] = "\
ierror = openunit(unitnum,filename,filestatus,fileaction)\n\nWrapper for ``openunit``.\
\n\nParameters\n----------\n"
"unitnum : input int\n"
"filename : input string(len=-1)\n"
"filestatus : input string(len=-1)\n"
"fileaction : input string(len=-1)\n"
"\nReturns\n-------\n"
"ierror : int";
/* extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout_ffsqp_openunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,string,string,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  string filestatus = NULL;
  int slen(filestatus);
  PyObject *filestatus_capi = Py_None;
  string fileaction = NULL;
  int slen(fileaction);
  PyObject *fileaction_capi = Py_None;
  int ierror = 0;
  static char *capi_kwlist[] = {"unitnum","filename","filestatus","fileaction",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:ffsqp.openunit",\
    capi_kwlist,&unitnum_capi,&filename_capi,&filestatus_capi,&fileaction_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"ffsqp.openunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 2nd argument `filename' of ffsqp.openunit to C string");
  if (f2py_success) {
  /* Processing variable filestatus */
  slen(filestatus) = -1;
  f2py_success = string_from_pyobj(&filestatus,&slen(filestatus),"",filestatus_capi,"string_from_pyobj failed in converting 3rd argument `filestatus' of ffsqp.openunit to C string");
  if (f2py_success) {
  /* Processing variable fileaction */
  slen(fileaction) = -1;
  f2py_success = string_from_pyobj(&fileaction,&slen(fileaction),"",fileaction_capi,"string_from_pyobj failed in converting 4th argument `fileaction' of ffsqp.openunit to C string");
  if (f2py_success) {
  /* Processing variable ierror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum,filename,filestatus,fileaction,&ierror,slen(filename),slen(filestatus),slen(fileaction));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ierror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierror */
    STRINGFREE(fileaction);
  }  /*if (f2py_success) of fileaction*/
  /* End of cleaning variable fileaction */
    STRINGFREE(filestatus);
  }  /*if (f2py_success) of filestatus*/
  /* End of cleaning variable filestatus */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of openunit ******************************/

/********************************** pyflush **********************************/
static char doc_f2py_rout_ffsqp_pyflush[] = "\
pyflush(unitnum)\n\nWrapper for ``pyflush``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(pyflush,PYFLUSH)(int*); */
static PyObject *f2py_rout_ffsqp_pyflush(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:ffsqp.pyflush",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"ffsqp.pyflush() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of pyflush *******************************/

/********************************* closeunit *********************************/
static char doc_f2py_rout_ffsqp_closeunit[] = "\
closeunit(unitnum)\n\nWrapper for ``closeunit``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(closeunit,CLOSEUNIT)(int*); */
static PyObject *f2py_rout_ffsqp_closeunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:ffsqp.closeunit",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"ffsqp.closeunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of closeunit ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

static FortranDataDef f2py_cmache_def[] = {
  {"qleps",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_cmache(char *qleps) {
  int i_f2py=0;
  f2py_cmache_def[i_f2py++].data = qleps;
}
extern void F_FUNC(f2pyinitcmache,F2PYINITCMACHE)(void(*)(char*));
static void f2py_init_cmache(void) {
  F_FUNC(f2pyinitcmache,F2PYINITCMACHE)(f2py_setup_cmache);
}

static FortranDataDef f2py_fsqpp1_def[] = {
  {"nnineq",0,{{-1}},NPY_INT},
  {"m",0,{{-1}},NPY_INT},
  {"ncallg",0,{{-1}},NPY_INT},
  {"ncallf",0,{{-1}},NPY_INT},
  {"modd",0,{{-1}},NPY_INT},
  {"lstype",0,{{-1}},NPY_INT},
  {"nstop",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_fsqpp1(char *nnineq,char *m,char *ncallg,char *ncallf,char *modd,char *lstype,char *nstop) {
  int i_f2py=0;
  f2py_fsqpp1_def[i_f2py++].data = nnineq;
  f2py_fsqpp1_def[i_f2py++].data = m;
  f2py_fsqpp1_def[i_f2py++].data = ncallg;
  f2py_fsqpp1_def[i_f2py++].data = ncallf;
  f2py_fsqpp1_def[i_f2py++].data = modd;
  f2py_fsqpp1_def[i_f2py++].data = lstype;
  f2py_fsqpp1_def[i_f2py++].data = nstop;
}
extern void F_FUNC(f2pyinitfsqpp1,F2PYINITFSQPP1)(void(*)(char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_fsqpp1(void) {
  F_FUNC(f2pyinitfsqpp1,F2PYINITFSQPP1)(f2py_setup_fsqpp1);
}

static FortranDataDef f2py_fsqpp2_def[] = {
  {"io",0,{{-1}},NPY_INT},
  {"ipp",0,{{-1}},NPY_INT},
  {"ipsp",0,{{-1}},NPY_INT},
  {"ipyes",0,{{-1}},NPY_INT},
  {"info",0,{{-1}},NPY_INT},
  {"idummy",0,{{-1}},NPY_INT},
  {"iter",0,{{-1}},NPY_INT},
  {"initvl",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_fsqpp2(char *io,char *ipp,char *ipsp,char *ipyes,char *info,char *idummy,char *iter,char *initvl) {
  int i_f2py=0;
  f2py_fsqpp2_def[i_f2py++].data = io;
  f2py_fsqpp2_def[i_f2py++].data = ipp;
  f2py_fsqpp2_def[i_f2py++].data = ipsp;
  f2py_fsqpp2_def[i_f2py++].data = ipyes;
  f2py_fsqpp2_def[i_f2py++].data = info;
  f2py_fsqpp2_def[i_f2py++].data = idummy;
  f2py_fsqpp2_def[i_f2py++].data = iter;
  f2py_fsqpp2_def[i_f2py++].data = initvl;
}
extern void F_FUNC(f2pyinitfsqpp2,F2PYINITFSQPP2)(void(*)(char*,char*,char*,char*,char*,char*,char*,char*));
static void f2py_init_fsqpp2(void) {
  F_FUNC(f2pyinitfsqpp2,F2PYINITFSQPP2)(f2py_setup_fsqpp2);
}

static FortranDataDef f2py_fsqpp3_def[] = {
  {"epsmac",0,{{-1}},NPY_DOUBLE},
  {"rteps",0,{{-1}},NPY_DOUBLE},
  {"upert",0,{{-1}},NPY_DOUBLE},
  {"valnom",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_fsqpp3(char *epsmac,char *rteps,char *upert,char *valnom) {
  int i_f2py=0;
  f2py_fsqpp3_def[i_f2py++].data = epsmac;
  f2py_fsqpp3_def[i_f2py++].data = rteps;
  f2py_fsqpp3_def[i_f2py++].data = upert;
  f2py_fsqpp3_def[i_f2py++].data = valnom;
}
extern void F_FUNC(f2pyinitfsqpp3,F2PYINITFSQPP3)(void(*)(char*,char*,char*,char*));
static void f2py_init_fsqpp3(void) {
  F_FUNC(f2pyinitfsqpp3,F2PYINITFSQPP3)(f2py_setup_fsqpp3);
}

static FortranDataDef f2py_fsqpp4_def[] = {
  {"rolis1",0,{{-1}},NPY_INT},
  {"d0is0",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_fsqpp4(char *rolis1,char *d0is0) {
  int i_f2py=0;
  f2py_fsqpp4_def[i_f2py++].data = rolis1;
  f2py_fsqpp4_def[i_f2py++].data = d0is0;
}
extern void F_FUNC(f2pyinitfsqpp4,F2PYINITFSQPP4)(void(*)(char*,char*));
static void f2py_init_fsqpp4(void) {
  F_FUNC(f2pyinitfsqpp4,F2PYINITFSQPP4)(f2py_setup_fsqpp4);
}

static FortranDataDef f2py_fsqpq2_def[] = {
  {"maxit",0,{{-1}},NPY_INT},
  {NULL}
};
static void f2py_setup_fsqpq2(char *maxit) {
  int i_f2py=0;
  f2py_fsqpq2_def[i_f2py++].data = maxit;
}
extern void F_FUNC(f2pyinitfsqpq2,F2PYINITFSQPQ2)(void(*)(char*));
static void f2py_init_fsqpq2(void) {
  F_FUNC(f2pyinitfsqpq2,F2PYINITFSQPQ2)(f2py_setup_fsqpq2);
}

static FortranDataDef f2py_fsqpq1_def[] = {
  {"big",0,{{-1}},NPY_DOUBLE},
  {"tolfea",0,{{-1}},NPY_DOUBLE},
  {NULL}
};
static void f2py_setup_fsqpq1(char *big,char *tolfea) {
  int i_f2py=0;
  f2py_fsqpq1_def[i_f2py++].data = big;
  f2py_fsqpq1_def[i_f2py++].data = tolfea;
}
extern void F_FUNC(f2pyinitfsqpq1,F2PYINITFSQPQ1)(void(*)(char*,char*));
static void f2py_init_fsqpq1(void) {
  F_FUNC(f2pyinitfsqpq1,F2PYINITFSQPQ1)(f2py_setup_fsqpq1);
}

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"ffsqp",-1,{{-1}},0,(char *)F_FUNC(ffsqp,FFSQP),(f2py_init_func)f2py_rout_ffsqp_ffsqp,doc_f2py_rout_ffsqp_ffsqp},
  {"openunit",-1,{{-1}},0,(char *)F_FUNC(openunit,OPENUNIT),(f2py_init_func)f2py_rout_ffsqp_openunit,doc_f2py_rout_ffsqp_openunit},
  {"pyflush",-1,{{-1}},0,(char *)F_FUNC(pyflush,PYFLUSH),(f2py_init_func)f2py_rout_ffsqp_pyflush,doc_f2py_rout_ffsqp_pyflush},
  {"closeunit",-1,{{-1}},0,(char *)F_FUNC(closeunit,CLOSEUNIT),(f2py_init_func)f2py_rout_ffsqp_closeunit,doc_f2py_rout_ffsqp_closeunit},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "ffsqp",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_ffsqp(void) {
#else
#define RETVAL
PyMODINIT_FUNC initffsqp(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = ffsqp_module = PyModule_Create(&moduledef);
#else
  m = ffsqp_module = Py_InitModule("ffsqp", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module ffsqp (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'ffsqp' is auto-generated with f2py (version:2).\nFunctions:\n"
"  ffsqp(nparam,nf,nineqn,nineq,neqn,neq,mode,iprint,miter,inform,bigbnd,eps,epseqn,udelta,bl,bu,x,f,g,iw,iwsize,w,nwsize,obj,constr,gradob,gradcn,iounit,ifile,obj_extra_args=(),constr_extra_args=(),gradob_extra_args=(),gradcn_extra_args=())\n"
"  ierror = openunit(unitnum,filename,filestatus,fileaction)\n"
"  pyflush(unitnum)\n"
"  closeunit(unitnum)\n"
"COMMON blocks:\n""  /cmache/ qleps\n""  /fsqpp1/ nnineq,m,ncallg,ncallf,modd,lstype,nstop\n""  /fsqpp2/ io,ipp,ipsp,ipyes,info,idummy,iter,initvl\n""  /fsqpp3/ epsmac,rteps,upert,valnom\n""  /fsqpp4/ rolis1,d0is0\n""  /fsqpq2/ maxit\n""  /fsqpq1/ big,tolfea\n"".");
  PyDict_SetItemString(d, "__doc__", s);
  ffsqp_error = PyErr_NewException ("ffsqp.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

  F2PyDict_SetItemString(d, "cmache", PyFortranObject_New(f2py_cmache_def,f2py_init_cmache));
  F2PyDict_SetItemString(d, "fsqpp1", PyFortranObject_New(f2py_fsqpp1_def,f2py_init_fsqpp1));
  F2PyDict_SetItemString(d, "fsqpp2", PyFortranObject_New(f2py_fsqpp2_def,f2py_init_fsqpp2));
  F2PyDict_SetItemString(d, "fsqpp3", PyFortranObject_New(f2py_fsqpp3_def,f2py_init_fsqpp3));
  F2PyDict_SetItemString(d, "fsqpp4", PyFortranObject_New(f2py_fsqpp4_def,f2py_init_fsqpp4));
  F2PyDict_SetItemString(d, "fsqpq2", PyFortranObject_New(f2py_fsqpq2_def,f2py_init_fsqpq2));
  F2PyDict_SetItemString(d, "fsqpq1", PyFortranObject_New(f2py_fsqpq1_def,f2py_init_fsqpq1));
/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"ffsqp");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
