C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitnlpql3(setupfunc)
      external setupfunc
      double precision f1
      double precision acc1
      double precision scbou1
      double precision dbdfac
      double precision zefac
      double precision rpeno
      double precision rpens
      double precision rpenu
      double precision zefacu
      double precision delta
      double precision beta
      double precision amue
      double precision alm
      integer mm1
      integer me1
      integer maxfu1
      integer maxit1
      integer iprin1
      integer mode1
      integer ifail1
      logical llise1
      logical lql1
      logical lmer
      integer iout1
      common /nlpql3/ f1,acc1,scbou1,dbdfac,zefac,rpeno,rpens,rpen
     &u,zefacu,delta,beta,amue,alm,mm1,me1,maxfu1,maxit1,iprin1,mode1,if
     &ail1,llise1,lql1,lmer,iout1
      call setupfunc(f1,acc1,scbou1,dbdfac,zefac,rpeno,rpens,rpenu
     &,zefacu,delta,beta,amue,alm,mm1,me1,maxfu1,maxit1,iprin1,mode1,ifa
     &il1,llise1,lql1,lmer,iout1)
      end

      subroutine f2pyinitcmache(setupfunc)
      external setupfunc
      double precision eps0
      common /cmache/ eps0
      call setupfunc(eps0)
      end


