system_name = "Learjet Model"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 100

is_discrete = false
is_hybrid = false


[parameters]
    load_type = "light"

[inputs]
  msgs = [ "controller_output.msg" ]

[topics]
  [topics.states]
      msg = "jetplant_state.msg"

  [topics.outputs]
      msg = "jetplant_output.msg"