/* File: mmfdmodule.c
 * This file is auto-generated with f2py (version:2).
 * f2py is a Fortran to Python Interface Generator (FPIG), Second Edition,
 * written by Pearu Peterson <pearu@cens.ioc.ee>.
 * Generation date: Sun Apr 11 17:22:54 2021
 * Do not edit this file directly unless you know what you are doing!!!
 */

#ifdef __cplusplus
extern "C" {
#endif

/*********************** See f2py2e/cfuncs.py: includes ***********************/
#include "Python.h"
#include <stdarg.h>
#include "fortranobject.h"
#include <string.h>
#include <setjmp.h>

/**************** See f2py2e/rules.py: mod_rules['modulebody'] ****************/
static PyObject *mmfd_error;
static PyObject *mmfd_module;

/*********************** See f2py2e/cfuncs.py: typedefs ***********************/
typedef char * string;
typedef signed char signed_char;

/****************** See f2py2e/cfuncs.py: typedefs_generated ******************/
typedef void(*cb_objgrd_in_mmfd__user__routines_typedef)(int *,int *,double *,double *,double *,double *,double *);
typedef void(*cb_objfun_in_mmfd__user__routines_typedef)(int *,int *,double *,double *,double *);

/********************** See f2py2e/cfuncs.py: cppmacros **********************/
#ifndef max
#define max(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef min
#define min(a,b) ((a < b) ? (a) : (b))
#endif
#ifndef MAX
#define MAX(a,b) ((a > b) ? (a) : (b))
#endif
#ifndef MIN
#define MIN(a,b) ((a < b) ? (a) : (b))
#endif

#define STRINGMALLOC(str,len)\
    if ((str = (string)malloc(sizeof(char)*(len+1))) == NULL) {\
        PyErr_SetString(PyExc_MemoryError, "out of memory");\
        goto capi_fail;\
    } else {\
        (str)[len] = '\0';\
    }

#define PRINTPYOBJERR(obj)\
    fprintf(stderr,"mmfd.error is related to ");\
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");

\
#define FAILNULL(p) do {                                            \
    if ((p) == NULL) {                                              \
        PyErr_SetString(PyExc_MemoryError, "NULL pointer found");   \
        goto capi_fail;                                             \
    }                                                               \
} while (0)

#define pyobj_from_int1(v) (PyInt_FromLong(v))
#define GETSCALARFROMPYTUPLE(tuple,index,var,ctype,mess) {\
        if ((capi_tmp = PyTuple_GetItem((tuple),(index)))==NULL) goto capi_fail;\
        if (!(ctype ## _from_pyobj((var),capi_tmp,mess)))\
            goto capi_fail;\
    }

#define pyobj_from_double1(v) (PyFloat_FromDouble(v))
#define MEMCOPY(to,from,n)\
    do { FAILNULL(to); FAILNULL(from); (void)memcpy(to,from,n); } while (0)

#ifdef DEBUGCFUNCS
#define CFUNCSMESS(mess) fprintf(stderr,"debug-capi:"mess);
#define CFUNCSMESSPY(mess,obj) CFUNCSMESS(mess) \
    PyObject_Print((PyObject *)obj,stderr,Py_PRINT_RAW);\
    fprintf(stderr,"\n");
#else
#define CFUNCSMESS(mess)
#define CFUNCSMESSPY(mess,obj)
#endif

#if defined(PREPEND_FORTRAN)
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F
#else
#define F_FUNC(f,F) _##f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) _##F##_
#else
#define F_FUNC(f,F) _##f##_
#endif
#endif
#else
#if defined(NO_APPEND_FORTRAN)
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F
#else
#define F_FUNC(f,F) f
#endif
#else
#if defined(UPPERCASE_FORTRAN)
#define F_FUNC(f,F) F##_
#else
#define F_FUNC(f,F) f##_
#endif
#endif
#endif
#if defined(UNDERSCORE_G77)
#define F_FUNC_US(f,F) F_FUNC(f##_,F##_)
#else
#define F_FUNC_US(f,F) F_FUNC(f,F)
#endif

#define rank(var) var ## _Rank
#define shape(var,dim) var ## _Dims[dim]
#define old_rank(var) (PyArray_NDIM((PyArrayObject *)(capi_ ## var ## _tmp)))
#define old_shape(var,dim) PyArray_DIM(((PyArrayObject *)(capi_ ## var ## _tmp)),dim)
#define fshape(var,dim) shape(var,rank(var)-dim-1)
#define len(var) shape(var,0)
#define flen(var) fshape(var,0)
#define old_size(var) PyArray_SIZE((PyArrayObject *)(capi_ ## var ## _tmp))
/* #define index(i) capi_i ## i */
#define slen(var) capi_ ## var ## _len
#define size(var, ...) f2py_size((PyArrayObject *)(capi_ ## var ## _tmp), ## __VA_ARGS__, -1)

#define STRINGFREE(str) do {if (!(str == NULL)) free(str);} while (0)

#define SWAP(a,b,t) {\
    t *c;\
    c = a;\
    a = b;\
    b = c;}

#define STRINGCOPYN(to,from,buf_size)                           \
    do {                                                        \
        int _m = (buf_size);                                    \
        char *_to = (to);                                       \
        char *_from = (from);                                   \
        FAILNULL(_to); FAILNULL(_from);                         \
        (void)strncpy(_to, _from, sizeof(char)*_m);             \
        _to[_m-1] = '\0';                                      \
        /* Padding with spaces instead of nulls */              \
        for (_m -= 2; _m >= 0 && _to[_m] == '\0'; _m--) {      \
            _to[_m] = ' ';                                      \
        }                                                       \
    } while (0)

/* New SciPy */
#define TRYPYARRAYTEMPLATECHAR case NPY_STRING: *(char *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATELONG case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;
#define TRYPYARRAYTEMPLATEOBJECT case NPY_OBJECT: PyArray_SETITEM(arr,PyArray_DATA(arr),pyobj_from_ ## ctype ## 1(*v)); break;

#define TRYPYARRAYTEMPLATE(ctype,typecode) \
        PyArrayObject *arr = NULL;\
        if (!obj) return -2;\
        if (!PyArray_Check(obj)) return -1;\
        if (!(arr=(PyArrayObject *)obj)) {fprintf(stderr,"TRYPYARRAYTEMPLATE:");PRINTPYOBJERR(obj);return 0;}\
        if (PyArray_DESCR(arr)->type==typecode)  {*(ctype *)(PyArray_DATA(arr))=*v; return 1;}\
        switch (PyArray_TYPE(arr)) {\
                case NPY_DOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_INT: *(int *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONG: *(long *)(PyArray_DATA(arr))=*v; break;\
                case NPY_FLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CDOUBLE: *(double *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CFLOAT: *(float *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BOOL: *(npy_bool *)(PyArray_DATA(arr))=(*v!=0); break;\
                case NPY_UBYTE: *(unsigned char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_BYTE: *(signed char *)(PyArray_DATA(arr))=*v; break;\
                case NPY_SHORT: *(short *)(PyArray_DATA(arr))=*v; break;\
                case NPY_USHORT: *(npy_ushort *)(PyArray_DATA(arr))=*v; break;\
                case NPY_UINT: *(npy_uint *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONG: *(npy_ulong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGLONG: *(npy_longlong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_ULONGLONG: *(npy_ulonglong *)(PyArray_DATA(arr))=*v; break;\
                case NPY_LONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_CLONGDOUBLE: *(npy_longdouble *)(PyArray_DATA(arr))=*v; break;\
                case NPY_OBJECT: PyArray_SETITEM(arr, PyArray_DATA(arr), pyobj_from_ ## ctype ## 1(*v)); break;\
        default: return -2;\
        };\
        return 1


/************************ See f2py2e/cfuncs.py: cfuncs ************************/
static int f2py_size(PyArrayObject* var, ...)
{
  npy_int sz = 0;
  npy_int dim;
  npy_int rank;
  va_list argp;
  va_start(argp, var);
  dim = va_arg(argp, npy_int);
  if (dim==-1)
    {
      sz = PyArray_SIZE(var);
    }
  else
    {
      rank = PyArray_NDIM(var);
      if (dim>=1 && dim<=rank)
        sz = PyArray_DIM(var, dim-1);
      else
        fprintf(stderr, "f2py_size: 2nd argument value=%d fails to satisfy 1<=value<=%d. Result will be 0.\n", dim, rank);
    }
  va_end(argp);
  return sz;
}

static int double_from_pyobj(double* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyFloat_Check(obj)) {
#ifdef __sgi
        *v = PyFloat_AsDouble(obj);
#else
        *v = PyFloat_AS_DOUBLE(obj);
#endif
        return 1;
    }
    tmp = PyNumber_Float(obj);
    if (tmp) {
#ifdef __sgi
        *v = PyFloat_AsDouble(tmp);
#else
        *v = PyFloat_AS_DOUBLE(tmp);
#endif
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (double_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = mmfd_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int try_pyarr_from_double(PyObject* obj,double* v) {
    TRYPYARRAYTEMPLATE(double,'d');
}

static int try_pyarr_from_int(PyObject* obj,int* v) {
    TRYPYARRAYTEMPLATE(int,'i');
}

static int int_from_pyobj(int* v,PyObject *obj,const char *errmess) {
    PyObject* tmp = NULL;
    if (PyInt_Check(obj)) {
        *v = (int)PyInt_AS_LONG(obj);
        return 1;
    }
    tmp = PyNumber_Int(obj);
    if (tmp) {
        *v = PyInt_AS_LONG(tmp);
        Py_DECREF(tmp);
        return 1;
    }
    if (PyComplex_Check(obj))
        tmp = PyObject_GetAttrString(obj,"real");
    else if (PyString_Check(obj) || PyUnicode_Check(obj))
        /*pass*/;
    else if (PySequence_Check(obj))
        tmp = PySequence_GetItem(obj,0);
    if (tmp) {
        PyErr_Clear();
        if (int_from_pyobj(v,tmp,errmess)) {Py_DECREF(tmp); return 1;}
        Py_DECREF(tmp);
    }
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = mmfd_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int string_from_pyobj(string *str,int *len,const string inistr,PyObject *obj,const char *errmess) {
    PyArrayObject *arr = NULL;
    PyObject *tmp = NULL;
#ifdef DEBUGCFUNCS
fprintf(stderr,"string_from_pyobj(str='%s',len=%d,inistr='%s',obj=%p)\n",(char*)str,*len,(char *)inistr,obj);
#endif
    if (obj == Py_None) {
        if (*len == -1)
            *len = strlen(inistr); /* Will this cause problems? */
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,inistr,*len+1);
        return 1;
    }
    if (PyArray_Check(obj)) {
        if ((arr = (PyArrayObject *)obj) == NULL)
            goto capi_fail;
        if (!ISCONTIGUOUS(arr)) {
            PyErr_SetString(PyExc_ValueError,"array object is non-contiguous.");
            goto capi_fail;
        }
        if (*len == -1)
            *len = (PyArray_ITEMSIZE(arr))*PyArray_SIZE(arr);
        STRINGMALLOC(*str,*len);
        STRINGCOPYN(*str,PyArray_DATA(arr),*len+1);
        return 1;
    }
    if (PyString_Check(obj)) {
        tmp = obj;
        Py_INCREF(tmp);
    }
#if PY_VERSION_HEX >= 0x03000000
    else if (PyUnicode_Check(obj)) {
        tmp = PyUnicode_AsASCIIString(obj);
    }
    else {
        PyObject *tmp2;
        tmp2 = PyObject_Str(obj);
        if (tmp2) {
            tmp = PyUnicode_AsASCIIString(tmp2);
            Py_DECREF(tmp2);
        }
        else {
            tmp = NULL;
        }
    }
#else
    else {
        tmp = PyObject_Str(obj);
    }
#endif
    if (tmp == NULL) goto capi_fail;
    if (*len == -1)
        *len = PyString_GET_SIZE(tmp);
    STRINGMALLOC(*str,*len);
    STRINGCOPYN(*str,PyString_AS_STRING(tmp),*len+1);
    Py_DECREF(tmp);
    return 1;
capi_fail:
    Py_XDECREF(tmp);
    {
        PyObject* err = PyErr_Occurred();
        if (err==NULL) err = mmfd_error;
        PyErr_SetString(err,errmess);
    }
    return 0;
}

static int create_cb_arglist(PyObject* fun,PyTupleObject* xa,const int maxnofargs,const int nofoptargs,int *nofargs,PyTupleObject **args,const char *errmess) {
    PyObject *tmp = NULL;
    PyObject *tmp_fun = NULL;
    int tot,opt,ext,siz,i,di=0;
    CFUNCSMESS("create_cb_arglist\n");
    tot=opt=ext=siz=0;
    /* Get the total number of arguments */
    if (PyFunction_Check(fun))
        tmp_fun = fun;
    else {
        di = 1;
        if (PyObject_HasAttrString(fun,"im_func")) {
            tmp_fun = PyObject_GetAttrString(fun,"im_func");
        }
        else if (PyObject_HasAttrString(fun,"__call__")) {
            tmp = PyObject_GetAttrString(fun,"__call__");
            if (PyObject_HasAttrString(tmp,"im_func"))
                tmp_fun = PyObject_GetAttrString(tmp,"im_func");
            else {
                tmp_fun = fun; /* built-in function */
                tot = maxnofargs;
                if (xa != NULL)
                    tot += PyTuple_Size((PyObject *)xa);
            }
            Py_XDECREF(tmp);
        }
        else if (PyFortran_Check(fun) || PyFortran_Check1(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                tot += PyTuple_Size((PyObject *)xa);
            tmp_fun = fun;
        }
        else if (F2PyCapsule_Check(fun)) {
            tot = maxnofargs;
            if (xa != NULL)
                ext = PyTuple_Size((PyObject *)xa);
            if(ext>0) {
                fprintf(stderr,"extra arguments tuple cannot be used with CObject call-back\n");
                goto capi_fail;
            }
            tmp_fun = fun;
        }
    }
if (tmp_fun==NULL) {
fprintf(stderr,"Call-back argument must be function|instance|instance.__call__|f2py-function but got %s.\n",(fun==NULL?"NULL":Py_TYPE(fun)->tp_name));
goto capi_fail;
}
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__code__")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"__code__"),"co_argcount"))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_code")) {
        if (PyObject_HasAttrString(tmp = PyObject_GetAttrString(tmp_fun,"func_code"),"co_argcount"))
#endif
            tot = PyInt_AsLong(PyObject_GetAttrString(tmp,"co_argcount")) - di;
        Py_XDECREF(tmp);
    }
    /* Get the number of optional arguments */
#if PY_VERSION_HEX >= 0x03000000
    if (PyObject_HasAttrString(tmp_fun,"__defaults__")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"__defaults__")))
#else
    if (PyObject_HasAttrString(tmp_fun,"func_defaults")) {
        if (PyTuple_Check(tmp = PyObject_GetAttrString(tmp_fun,"func_defaults")))
#endif
            opt = PyTuple_Size(tmp);
        Py_XDECREF(tmp);
    }
    /* Get the number of extra arguments */
    if (xa != NULL)
        ext = PyTuple_Size((PyObject *)xa);
    /* Calculate the size of call-backs argument list */
    siz = MIN(maxnofargs+ext,tot);
    *nofargs = MAX(0,siz-ext);
#ifdef DEBUGCFUNCS
    fprintf(stderr,"debug-capi:create_cb_arglist:maxnofargs(-nofoptargs),tot,opt,ext,siz,nofargs=%d(-%d),%d,%d,%d,%d,%d\n",maxnofargs,nofoptargs,tot,opt,ext,siz,*nofargs);
#endif
    if (siz<tot-opt) {
        fprintf(stderr,"create_cb_arglist: Failed to build argument list (siz) with enough arguments (tot-opt) required by user-supplied function (siz,tot,opt=%d,%d,%d).\n",siz,tot,opt);
        goto capi_fail;
    }
    /* Initialize argument list */
    *args = (PyTupleObject *)PyTuple_New(siz);
    for (i=0;i<*nofargs;i++) {
        Py_INCREF(Py_None);
        PyTuple_SET_ITEM((PyObject *)(*args),i,Py_None);
    }
    if (xa != NULL)
        for (i=(*nofargs);i<siz;i++) {
            tmp = PyTuple_GetItem((PyObject *)xa,i-(*nofargs));
            Py_INCREF(tmp);
            PyTuple_SET_ITEM(*args,i,tmp);
        }
    CFUNCSMESS("create_cb_arglist-end\n");
    return 1;
capi_fail:
    if ((PyErr_Occurred())==NULL)
        PyErr_SetString(mmfd_error,errmess);
    return 0;
}


/********************* See f2py2e/cfuncs.py: userincludes *********************/
/*need_userincludes*/

/********************* See f2py2e/capi_rules.py: usercode *********************/


/* See f2py2e/rules.py */
extern void F_FUNC(mmfd,MMFD)(int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,double*,int*,int*,int*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,cb_objfun_in_mmfd__user__routines_typedef,cb_objgrd_in_mmfd__user__routines_typedef,size_t);
extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t);
extern void F_FUNC(pyflush,PYFLUSH)(int*);
extern void F_FUNC(closeunit,CLOSEUNIT)(int*);
/*eof externroutines*/

/******************** See f2py2e/capi_rules.py: usercode1 ********************/


/******************* See f2py2e/cb_rules.py: buildcallback *******************/

/********************* cb_objfun_in_mmfd__user__routines *********************/
PyObject *cb_objfun_in_mmfd__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_objfun_in_mmfd__user__routines_args_capi = NULL;
int cb_objfun_in_mmfd__user__routines_nofargs = 0;
jmp_buf cb_objfun_in_mmfd__user__routines_jmpbuf;
/*typedef void(*cb_objfun_in_mmfd__user__routines_typedef)(int *,int *,double *,double *,double *);*/
static void cb_objfun_in_mmfd__user__routines (int *ndv_cb_capi,int *ncon_cb_capi,double *xx,double *obj_cb_capi,double *g) {
  PyTupleObject *capi_arglist = cb_objfun_in_mmfd__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int ndv=(*ndv_cb_capi);
  int ncon=(*ncon_cb_capi);
  double obj=(*obj_cb_capi);
  npy_intp xx_Dims[1] = {-1};
  npy_intp g_Dims[1] = {-1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_objfun_in_mmfd__user__routines (maxnofargs=5(-0))\n");
  CFUNCSMESSPY("cb:cb_objfun_in_mmfd__user__routines_capi=",cb_objfun_in_mmfd__user__routines_capi);
  if (cb_objfun_in_mmfd__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_objfun_in_mmfd__user__routines_capi = PyObject_GetAttrString(mmfd_module,"objfun");
  }
  if (cb_objfun_in_mmfd__user__routines_capi==NULL) {
    PyErr_SetString(mmfd_error,"cb: Callback objfun not defined (as an argument or module mmfd attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_objfun_in_mmfd__user__routines_capi)) {
  cb_objfun_in_mmfd__user__routines_typedef cb_objfun_in_mmfd__user__routines_cptr;
  cb_objfun_in_mmfd__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_objfun_in_mmfd__user__routines_capi);
  (*cb_objfun_in_mmfd__user__routines_cptr)(ndv_cb_capi,ncon_cb_capi,xx,obj_cb_capi,g);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(mmfd_module,"objfun_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(mmfd_error,"Failed to convert mmfd.objfun_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(mmfd_error,"Callback objfun argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  xx_Dims[0]=ndv;
  g_Dims[0]=ncon;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_objfun_in_mmfd__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(ndv)))
      goto capi_fail;
  if (cb_objfun_in_mmfd__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(ncon)))
      goto capi_fail;
  if (cb_objfun_in_mmfd__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,xx_Dims,NPY_DOUBLE,NULL,(char*)xx,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_objfun_in_mmfd__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(obj)))
      goto capi_fail;
  if (cb_objfun_in_mmfd__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,g_Dims,NPY_DOUBLE,NULL,(char*)g,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function objfun.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_objfun_in_mmfd__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_objfun_in_mmfd__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i)
    GETSCALARFROMPYTUPLE(capi_return,capi_i++,obj_cb_capi,double,"double_from_pyobj failed in converting argument obj of call-back function cb_objfun_in_mmfd__user__routines to C double\n");
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,g_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(g,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_objfun_in_mmfd__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_objfun_in_mmfd__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_objfun_in_mmfd__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/****************** end of cb_objfun_in_mmfd__user__routines ******************/


/********************* cb_objgrd_in_mmfd__user__routines *********************/
PyObject *cb_objgrd_in_mmfd__user__routines_capi = NULL;/*was Py_None*/
PyTupleObject *cb_objgrd_in_mmfd__user__routines_args_capi = NULL;
int cb_objgrd_in_mmfd__user__routines_nofargs = 0;
jmp_buf cb_objgrd_in_mmfd__user__routines_jmpbuf;
/*typedef void(*cb_objgrd_in_mmfd__user__routines_typedef)(int *,int *,double *,double *,double *,double *,double *);*/
static void cb_objgrd_in_mmfd__user__routines (int *ndv_cb_capi,int *ncon_cb_capi,double *xx,double *obj_cb_capi,double *g,double *ddf,double *b) {
  PyTupleObject *capi_arglist = cb_objgrd_in_mmfd__user__routines_args_capi;
  PyObject *capi_return = NULL;
  PyObject *capi_tmp = NULL;
  PyObject *capi_arglist_list = NULL;
  int capi_j,capi_i = 0;
  int capi_longjmp_ok = 1;
/*decl*/
  int ndv=(*ndv_cb_capi);
  int ncon=(*ncon_cb_capi);
  double obj=(*obj_cb_capi);
  npy_intp xx_Dims[1] = {-1};
  npy_intp g_Dims[1] = {-1};
  npy_intp ddf_Dims[1] = {-1};
  npy_intp b_Dims[2] = {-1, -1};
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_clock();
#endif
  CFUNCSMESS("cb:Call-back function cb_objgrd_in_mmfd__user__routines (maxnofargs=7(-0))\n");
  CFUNCSMESSPY("cb:cb_objgrd_in_mmfd__user__routines_capi=",cb_objgrd_in_mmfd__user__routines_capi);
  if (cb_objgrd_in_mmfd__user__routines_capi==NULL) {
    capi_longjmp_ok = 0;
    cb_objgrd_in_mmfd__user__routines_capi = PyObject_GetAttrString(mmfd_module,"objgrd");
  }
  if (cb_objgrd_in_mmfd__user__routines_capi==NULL) {
    PyErr_SetString(mmfd_error,"cb: Callback objgrd not defined (as an argument or module mmfd attribute).\n");
    goto capi_fail;
  }
  if (F2PyCapsule_Check(cb_objgrd_in_mmfd__user__routines_capi)) {
  cb_objgrd_in_mmfd__user__routines_typedef cb_objgrd_in_mmfd__user__routines_cptr;
  cb_objgrd_in_mmfd__user__routines_cptr = F2PyCapsule_AsVoidPtr(cb_objgrd_in_mmfd__user__routines_capi);
  (*cb_objgrd_in_mmfd__user__routines_cptr)(ndv_cb_capi,ncon_cb_capi,xx,obj_cb_capi,g,ddf,b);
  return;
  }
  if (capi_arglist==NULL) {
    capi_longjmp_ok = 0;
    capi_tmp = PyObject_GetAttrString(mmfd_module,"objgrd_extra_args");
    if (capi_tmp) {
      capi_arglist = (PyTupleObject *)PySequence_Tuple(capi_tmp);
      if (capi_arglist==NULL) {
        PyErr_SetString(mmfd_error,"Failed to convert mmfd.objgrd_extra_args to tuple.\n");
        goto capi_fail;
      }
    } else {
      PyErr_Clear();
      capi_arglist = (PyTupleObject *)Py_BuildValue("()");
    }
  }
  if (capi_arglist == NULL) {
    PyErr_SetString(mmfd_error,"Callback objgrd argument list is not set.\n");
    goto capi_fail;
  }
/*setdims*/
  xx_Dims[0]=ndv;
  g_Dims[0]=ncon;
  ddf_Dims[0]=ndv;
  b_Dims[0]=ndv,b_Dims[1]=ncon;
#ifdef PYPY_VERSION
#define CAPI_ARGLIST_SETITEM(idx, value) PyList_SetItem((PyObject *)capi_arglist_list, idx, value)
  capi_arglist_list = PySequence_List(capi_arglist);
  if (capi_arglist_list == NULL) goto capi_fail;
#else
#define CAPI_ARGLIST_SETITEM(idx, value) PyTuple_SetItem((PyObject *)capi_arglist, idx, value)
#endif
/*pyobjfrom*/
  if (cb_objgrd_in_mmfd__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(ndv)))
      goto capi_fail;
  if (cb_objgrd_in_mmfd__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_int1(ncon)))
      goto capi_fail;
  if (cb_objgrd_in_mmfd__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,xx_Dims,NPY_DOUBLE,NULL,(char*)xx,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_objgrd_in_mmfd__user__routines_nofargs>capi_i)
    if (CAPI_ARGLIST_SETITEM(capi_i++,pyobj_from_double1(obj)))
      goto capi_fail;
  if (cb_objgrd_in_mmfd__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,g_Dims,NPY_DOUBLE,NULL,(char*)g,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_objgrd_in_mmfd__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,1,ddf_Dims,NPY_DOUBLE,NULL,(char*)ddf,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
  if (cb_objgrd_in_mmfd__user__routines_nofargs>capi_i) {
    int itemsize_ = NPY_DOUBLE == NPY_STRING ? 1 : 0;
    /*XXX: Hmm, what will destroy this array??? */
    PyArrayObject *tmp_arr = (PyArrayObject *)PyArray_New(&PyArray_Type,2,b_Dims,NPY_DOUBLE,NULL,(char*)b,itemsize_,NPY_ARRAY_FARRAY,NULL);


    if (tmp_arr==NULL)
      goto capi_fail;
    if (CAPI_ARGLIST_SETITEM(capi_i++,(PyObject *)tmp_arr))
      goto capi_fail;
}
#undef CAPI_ARGLIST_SETITEM
#ifdef PYPY_VERSION
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist_list);
#else
  CFUNCSMESSPY("cb:capi_arglist=",capi_arglist);
#endif
  CFUNCSMESS("cb:Call-back calling Python function objgrd.\n");
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_start_call_clock();
#endif
#ifdef PYPY_VERSION
  capi_return = PyObject_CallObject(cb_objgrd_in_mmfd__user__routines_capi,(PyObject *)capi_arglist_list);
  Py_DECREF(capi_arglist_list);
  capi_arglist_list = NULL;
#else
  capi_return = PyObject_CallObject(cb_objgrd_in_mmfd__user__routines_capi,(PyObject *)capi_arglist);
#endif
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_call_clock();
#endif
  CFUNCSMESSPY("cb:capi_return=",capi_return);
  if (capi_return == NULL) {
    fprintf(stderr,"capi_return is NULL\n");
    goto capi_fail;
  }
  if (capi_return == Py_None) {
    Py_DECREF(capi_return);
    capi_return = Py_BuildValue("()");
  }
  else if (!PyTuple_Check(capi_return)) {
    capi_return = Py_BuildValue("(N)",capi_return);
  }
  capi_j = PyTuple_Size(capi_return);
  capi_i = 0;
/*frompyobj*/
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,ddf_Dims,1,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(ddf,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  if (capi_j>capi_i) {
    PyArrayObject *rv_cb_arr = NULL;
    if ((capi_tmp = PyTuple_GetItem(capi_return,capi_i++))==NULL) goto capi_fail;
    rv_cb_arr =  array_from_pyobj(NPY_DOUBLE,b_Dims,2,F2PY_INTENT_IN
,capi_tmp);
    if (rv_cb_arr == NULL) {
      fprintf(stderr,"rv_cb_arr is NULL\n");
      goto capi_fail;
    }
    MEMCOPY(b,PyArray_DATA(rv_cb_arr),PyArray_NBYTES(rv_cb_arr));
    if (capi_tmp != (PyObject *)rv_cb_arr) {
      Py_DECREF(rv_cb_arr);
    }
  }
  CFUNCSMESS("cb:cb_objgrd_in_mmfd__user__routines:successful\n");
  Py_DECREF(capi_return);
#ifdef F2PY_REPORT_ATEXIT
f2py_cb_stop_clock();
#endif
  goto capi_return_pt;
capi_fail:
  fprintf(stderr,"Call-back cb_objgrd_in_mmfd__user__routines failed.\n");
  Py_XDECREF(capi_return);
  Py_XDECREF(capi_arglist_list);
  if (capi_longjmp_ok)
    longjmp(cb_objgrd_in_mmfd__user__routines_jmpbuf,-1);
capi_return_pt:
  ;
return;
}
/****************** end of cb_objgrd_in_mmfd__user__routines ******************/


/*********************** See f2py2e/rules.py: buildapi ***********************/

/************************************ mmfd ************************************/
static char doc_f2py_rout_mmfd_mmfd[] = "\
mmfd(iiopt,iioned,iiprint,ndv,ncon,xx,xl,xu,obj,g,idg,wk,nrwk,iwk,nriwk,ifile,ct,ctmin,dabobj,delobj,thetaz,pmlt,itmax,itrmop,nfun,ngrd,objfun,objgrd,[objfun_extra_args,objgrd_extra_args])\n\nWrapper for ``mmfd``.\
\n\nParameters\n----------\n"
"iiopt : input int\n"
"iioned : input int\n"
"iiprint : input int\n"
"ndv : input int\n"
"ncon : input int\n"
"xx : in/output rank-1 array('d') with bounds (ndv)\n"
"xl : input rank-1 array('d') with bounds (ndv)\n"
"xu : input rank-1 array('d') with bounds (ndv)\n"
"obj : in/output rank-0 array(float,'d')\n"
"g : in/output rank-1 array('d') with bounds (ncon)\n"
"idg : input rank-1 array('i') with bounds (ncon)\n"
"wk : input rank-1 array('d') with bounds (nrwk)\n"
"nrwk : input int\n"
"iwk : input rank-1 array('i') with bounds (nriwk)\n"
"nriwk : input int\n"
"ifile : input string(len=-1)\n"
"ct : input float\n"
"ctmin : input float\n"
"dabobj : input float\n"
"delobj : input float\n"
"thetaz : input float\n"
"pmlt : input float\n"
"itmax : input int\n"
"itrmop : input int\n"
"nfun : in/output rank-0 array(int,'i')\n"
"ngrd : in/output rank-0 array(int,'i')\n"
"objfun : call-back function\n"
"objgrd : call-back function\n"
"\nOther Parameters\n----------------\n"
"objfun_extra_args : input tuple, optional\n    Default: ()\n"
"objgrd_extra_args : input tuple, optional\n    Default: ()\n"
"\nNotes\n-----\nCall-back functions::\n\n"
"  def objfun(ndv,ncon,xx,obj,g): return obj,g\n\
  Required arguments:\n"
"    ndv : input int\n"
"    ncon : input int\n"
"    xx : input rank-1 array('d') with bounds (ndv)\n"
"    obj : input float\n"
"    g : input rank-1 array('d') with bounds (ncon)\n"
"  Return objects:\n"
"    obj : float\n"
"    g : rank-1 array('d') with bounds (ncon)\n"
"  def objgrd(ndv,ncon,xx,obj,g,ddf,b): return ddf,b\n\
  Required arguments:\n"
"    ndv : input int\n"
"    ncon : input int\n"
"    xx : input rank-1 array('d') with bounds (ndv)\n"
"    obj : input float\n"
"    g : input rank-1 array('d') with bounds (ncon)\n"
"    ddf : input rank-1 array('d') with bounds (ndv)\n"
"    b : input rank-2 array('d') with bounds (ndv,ncon)\n"
"  Return objects:\n"
"    ddf : rank-1 array('d') with bounds (ndv)\n"
"    b : rank-2 array('d') with bounds (ndv,ncon)";
/* extern void F_FUNC(mmfd,MMFD)(int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,double*,int*,int*,int*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,cb_objfun_in_mmfd__user__routines_typedef,cb_objgrd_in_mmfd__user__routines_typedef,size_t); */
static PyObject *f2py_rout_mmfd_mmfd(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,int*,int*,int*,int*,double*,double*,double*,double*,double*,int*,double*,int*,int*,int*,string,double*,double*,double*,double*,double*,double*,int*,int*,int*,int*,cb_objfun_in_mmfd__user__routines_typedef,cb_objgrd_in_mmfd__user__routines_typedef,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int iiopt = 0;
  PyObject *iiopt_capi = Py_None;
  int iioned = 0;
  PyObject *iioned_capi = Py_None;
  int iiprint = 0;
  PyObject *iiprint_capi = Py_None;
  int ndv = 0;
  PyObject *ndv_capi = Py_None;
  int ncon = 0;
  PyObject *ncon_capi = Py_None;
  double *xx = NULL;
  npy_intp xx_Dims[1] = {-1};
  const int xx_Rank = 1;
  PyArrayObject *capi_xx_tmp = NULL;
  int capi_xx_intent = 0;
  PyObject *xx_capi = Py_None;
  double *xl = NULL;
  npy_intp xl_Dims[1] = {-1};
  const int xl_Rank = 1;
  PyArrayObject *capi_xl_tmp = NULL;
  int capi_xl_intent = 0;
  PyObject *xl_capi = Py_None;
  double *xu = NULL;
  npy_intp xu_Dims[1] = {-1};
  const int xu_Rank = 1;
  PyArrayObject *capi_xu_tmp = NULL;
  int capi_xu_intent = 0;
  PyObject *xu_capi = Py_None;
  double obj = 0;
  PyObject *obj_capi = Py_None;
  double *g = NULL;
  npy_intp g_Dims[1] = {-1};
  const int g_Rank = 1;
  PyArrayObject *capi_g_tmp = NULL;
  int capi_g_intent = 0;
  PyObject *g_capi = Py_None;
  int *idg = NULL;
  npy_intp idg_Dims[1] = {-1};
  const int idg_Rank = 1;
  PyArrayObject *capi_idg_tmp = NULL;
  int capi_idg_intent = 0;
  PyObject *idg_capi = Py_None;
  double *wk = NULL;
  npy_intp wk_Dims[1] = {-1};
  const int wk_Rank = 1;
  PyArrayObject *capi_wk_tmp = NULL;
  int capi_wk_intent = 0;
  PyObject *wk_capi = Py_None;
  int nrwk = 0;
  PyObject *nrwk_capi = Py_None;
  int *iwk = NULL;
  npy_intp iwk_Dims[1] = {-1};
  const int iwk_Rank = 1;
  PyArrayObject *capi_iwk_tmp = NULL;
  int capi_iwk_intent = 0;
  PyObject *iwk_capi = Py_None;
  int nriwk = 0;
  PyObject *nriwk_capi = Py_None;
  string ifile = NULL;
  int slen(ifile);
  PyObject *ifile_capi = Py_None;
  double ct = 0;
  PyObject *ct_capi = Py_None;
  double ctmin = 0;
  PyObject *ctmin_capi = Py_None;
  double dabobj = 0;
  PyObject *dabobj_capi = Py_None;
  double delobj = 0;
  PyObject *delobj_capi = Py_None;
  double thetaz = 0;
  PyObject *thetaz_capi = Py_None;
  double pmlt = 0;
  PyObject *pmlt_capi = Py_None;
  int itmax = 0;
  PyObject *itmax_capi = Py_None;
  int itrmop = 0;
  PyObject *itrmop_capi = Py_None;
  int nfun = 0;
  PyObject *nfun_capi = Py_None;
  int ngrd = 0;
  PyObject *ngrd_capi = Py_None;
  PyObject *objfun_capi = Py_None;
  PyTupleObject *objfun_xa_capi = NULL;
  PyTupleObject *objfun_args_capi = NULL;
  int objfun_nofargs_capi = 0;
  cb_objfun_in_mmfd__user__routines_typedef objfun_cptr;
  PyObject *objgrd_capi = Py_None;
  PyTupleObject *objgrd_xa_capi = NULL;
  PyTupleObject *objgrd_args_capi = NULL;
  int objgrd_nofargs_capi = 0;
  cb_objgrd_in_mmfd__user__routines_typedef objgrd_cptr;
  static char *capi_kwlist[] = {"iiopt","iioned","iiprint","ndv","ncon","xx","xl","xu","obj","g","idg","wk","nrwk","iwk","nriwk","ifile","ct","ctmin","dabobj","delobj","thetaz","pmlt","itmax","itrmop","nfun","ngrd","objfun","objgrd","objfun_extra_args","objgrd_extra_args",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOOOOOOOOOOOOOOOOOOOOOOOOOO|O!O!:mmfd.mmfd",\
    capi_kwlist,&iiopt_capi,&iioned_capi,&iiprint_capi,&ndv_capi,&ncon_capi,&xx_capi,&xl_capi,&xu_capi,&obj_capi,&g_capi,&idg_capi,&wk_capi,&nrwk_capi,&iwk_capi,&nriwk_capi,&ifile_capi,&ct_capi,&ctmin_capi,&dabobj_capi,&delobj_capi,&thetaz_capi,&pmlt_capi,&itmax_capi,&itrmop_capi,&nfun_capi,&ngrd_capi,&objfun_capi,&objgrd_capi,&PyTuple_Type,&objfun_xa_capi,&PyTuple_Type,&objgrd_xa_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable iiopt */
    f2py_success = int_from_pyobj(&iiopt,iiopt_capi,"mmfd.mmfd() 1st argument (iiopt) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iioned */
    f2py_success = int_from_pyobj(&iioned,iioned_capi,"mmfd.mmfd() 2nd argument (iioned) can't be converted to int");
  if (f2py_success) {
  /* Processing variable iiprint */
    f2py_success = int_from_pyobj(&iiprint,iiprint_capi,"mmfd.mmfd() 3rd argument (iiprint) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ndv */
    f2py_success = int_from_pyobj(&ndv,ndv_capi,"mmfd.mmfd() 4th argument (ndv) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ncon */
    f2py_success = int_from_pyobj(&ncon,ncon_capi,"mmfd.mmfd() 5th argument (ncon) can't be converted to int");
  if (f2py_success) {
  /* Processing variable obj */
    f2py_success = double_from_pyobj(&obj,obj_capi,"mmfd.mmfd() 9th argument (obj) can't be converted to double");
  if (f2py_success) {
  /* Processing variable nrwk */
    f2py_success = int_from_pyobj(&nrwk,nrwk_capi,"mmfd.mmfd() 13rd argument (nrwk) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nriwk */
    f2py_success = int_from_pyobj(&nriwk,nriwk_capi,"mmfd.mmfd() 15th argument (nriwk) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ifile */
  slen(ifile) = -1;
  f2py_success = string_from_pyobj(&ifile,&slen(ifile),"",ifile_capi,"string_from_pyobj failed in converting 16th argument `ifile' of mmfd.mmfd to C string");
  if (f2py_success) {
  /* Processing variable ct */
    f2py_success = double_from_pyobj(&ct,ct_capi,"mmfd.mmfd() 17th argument (ct) can't be converted to double");
  if (f2py_success) {
  /* Processing variable ctmin */
    f2py_success = double_from_pyobj(&ctmin,ctmin_capi,"mmfd.mmfd() 18th argument (ctmin) can't be converted to double");
  if (f2py_success) {
  /* Processing variable dabobj */
    f2py_success = double_from_pyobj(&dabobj,dabobj_capi,"mmfd.mmfd() 19th argument (dabobj) can't be converted to double");
  if (f2py_success) {
  /* Processing variable delobj */
    f2py_success = double_from_pyobj(&delobj,delobj_capi,"mmfd.mmfd() 20th argument (delobj) can't be converted to double");
  if (f2py_success) {
  /* Processing variable thetaz */
    f2py_success = double_from_pyobj(&thetaz,thetaz_capi,"mmfd.mmfd() 21st argument (thetaz) can't be converted to double");
  if (f2py_success) {
  /* Processing variable pmlt */
    f2py_success = double_from_pyobj(&pmlt,pmlt_capi,"mmfd.mmfd() 22nd argument (pmlt) can't be converted to double");
  if (f2py_success) {
  /* Processing variable itmax */
    f2py_success = int_from_pyobj(&itmax,itmax_capi,"mmfd.mmfd() 23rd argument (itmax) can't be converted to int");
  if (f2py_success) {
  /* Processing variable itrmop */
    f2py_success = int_from_pyobj(&itrmop,itrmop_capi,"mmfd.mmfd() 24th argument (itrmop) can't be converted to int");
  if (f2py_success) {
  /* Processing variable nfun */
    f2py_success = int_from_pyobj(&nfun,nfun_capi,"mmfd.mmfd() 25th argument (nfun) can't be converted to int");
  if (f2py_success) {
  /* Processing variable ngrd */
    f2py_success = int_from_pyobj(&ngrd,ngrd_capi,"mmfd.mmfd() 26th argument (ngrd) can't be converted to int");
  if (f2py_success) {
  /* Processing variable objfun */
if(F2PyCapsule_Check(objfun_capi)) {
  objfun_cptr = F2PyCapsule_AsVoidPtr(objfun_capi);
} else {
  objfun_cptr = cb_objfun_in_mmfd__user__routines;
}

  objfun_nofargs_capi = cb_objfun_in_mmfd__user__routines_nofargs;
  if (create_cb_arglist(objfun_capi,objfun_xa_capi,5,0,&cb_objfun_in_mmfd__user__routines_nofargs,&objfun_args_capi,"failed in processing argument list for call-back objfun.")) {
    jmp_buf objfun_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `objfun`.\n");
    SWAP(objfun_capi,cb_objfun_in_mmfd__user__routines_capi,PyObject);
    SWAP(objfun_args_capi,cb_objfun_in_mmfd__user__routines_args_capi,PyTupleObject);
    memcpy(&objfun_jmpbuf,&cb_objfun_in_mmfd__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable objgrd */
if(F2PyCapsule_Check(objgrd_capi)) {
  objgrd_cptr = F2PyCapsule_AsVoidPtr(objgrd_capi);
} else {
  objgrd_cptr = cb_objgrd_in_mmfd__user__routines;
}

  objgrd_nofargs_capi = cb_objgrd_in_mmfd__user__routines_nofargs;
  if (create_cb_arglist(objgrd_capi,objgrd_xa_capi,7,0,&cb_objgrd_in_mmfd__user__routines_nofargs,&objgrd_args_capi,"failed in processing argument list for call-back objgrd.")) {
    jmp_buf objgrd_jmpbuf;
    CFUNCSMESS("Saving jmpbuf for `objgrd`.\n");
    SWAP(objgrd_capi,cb_objgrd_in_mmfd__user__routines_capi,PyObject);
    SWAP(objgrd_args_capi,cb_objgrd_in_mmfd__user__routines_args_capi,PyTupleObject);
    memcpy(&objgrd_jmpbuf,&cb_objgrd_in_mmfd__user__routines_jmpbuf,sizeof(jmp_buf));
  /* Processing variable xx */
  xx_Dims[0]=ndv;
  capi_xx_intent |= F2PY_INTENT_INOUT;
  capi_xx_tmp = array_from_pyobj(NPY_DOUBLE,xx_Dims,xx_Rank,capi_xx_intent,xx_capi);
  if (capi_xx_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(mmfd_error,"failed in converting 6th argument `xx' of mmfd.mmfd to C/Fortran array" );
  } else {
    xx = (double *)(PyArray_DATA(capi_xx_tmp));

  /* Processing variable xl */
  xl_Dims[0]=ndv;
  capi_xl_intent |= F2PY_INTENT_IN;
  capi_xl_tmp = array_from_pyobj(NPY_DOUBLE,xl_Dims,xl_Rank,capi_xl_intent,xl_capi);
  if (capi_xl_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(mmfd_error,"failed in converting 7th argument `xl' of mmfd.mmfd to C/Fortran array" );
  } else {
    xl = (double *)(PyArray_DATA(capi_xl_tmp));

  /* Processing variable xu */
  xu_Dims[0]=ndv;
  capi_xu_intent |= F2PY_INTENT_IN;
  capi_xu_tmp = array_from_pyobj(NPY_DOUBLE,xu_Dims,xu_Rank,capi_xu_intent,xu_capi);
  if (capi_xu_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(mmfd_error,"failed in converting 8th argument `xu' of mmfd.mmfd to C/Fortran array" );
  } else {
    xu = (double *)(PyArray_DATA(capi_xu_tmp));

  /* Processing variable g */
  g_Dims[0]=ncon;
  capi_g_intent |= F2PY_INTENT_INOUT;
  capi_g_tmp = array_from_pyobj(NPY_DOUBLE,g_Dims,g_Rank,capi_g_intent,g_capi);
  if (capi_g_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(mmfd_error,"failed in converting 10th argument `g' of mmfd.mmfd to C/Fortran array" );
  } else {
    g = (double *)(PyArray_DATA(capi_g_tmp));

  /* Processing variable idg */
  idg_Dims[0]=ncon;
  capi_idg_intent |= F2PY_INTENT_IN;
  capi_idg_tmp = array_from_pyobj(NPY_INT,idg_Dims,idg_Rank,capi_idg_intent,idg_capi);
  if (capi_idg_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(mmfd_error,"failed in converting 11st argument `idg' of mmfd.mmfd to C/Fortran array" );
  } else {
    idg = (int *)(PyArray_DATA(capi_idg_tmp));

  /* Processing variable wk */
  wk_Dims[0]=nrwk;
  capi_wk_intent |= F2PY_INTENT_IN;
  capi_wk_tmp = array_from_pyobj(NPY_DOUBLE,wk_Dims,wk_Rank,capi_wk_intent,wk_capi);
  if (capi_wk_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(mmfd_error,"failed in converting 12nd argument `wk' of mmfd.mmfd to C/Fortran array" );
  } else {
    wk = (double *)(PyArray_DATA(capi_wk_tmp));

  /* Processing variable iwk */
  iwk_Dims[0]=nriwk;
  capi_iwk_intent |= F2PY_INTENT_IN;
  capi_iwk_tmp = array_from_pyobj(NPY_INT,iwk_Dims,iwk_Rank,capi_iwk_intent,iwk_capi);
  if (capi_iwk_tmp == NULL) {
    if (!PyErr_Occurred())
      PyErr_SetString(mmfd_error,"failed in converting 14th argument `iwk' of mmfd.mmfd to C/Fortran array" );
  } else {
    iwk = (int *)(PyArray_DATA(capi_iwk_tmp));

/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
    if ((setjmp(cb_objfun_in_mmfd__user__routines_jmpbuf)) || (setjmp(cb_objgrd_in_mmfd__user__routines_jmpbuf))) {
      f2py_success = 0;
    } else {
        (*f2py_func)(&iiopt,&iioned,&iiprint,&ndv,&ncon,xx,xl,xu,&obj,g,idg,wk,&nrwk,iwk,&nriwk,ifile,&ct,&ctmin,&dabobj,&delobj,&thetaz,&pmlt,&itmax,&itrmop,&nfun,&ngrd,objfun_cptr,objgrd_cptr,slen(ifile));
    }
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
  f2py_success = try_pyarr_from_double(obj_capi,&obj);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(nfun_capi,&nfun);
  if (f2py_success) {
  f2py_success = try_pyarr_from_int(ngrd_capi,&ngrd);
  if (f2py_success) {
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
  } /*if (f2py_success) of ngrd pyobjfrom*/
  } /*if (f2py_success) of nfun pyobjfrom*/
  } /*if (f2py_success) of obj pyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  if((PyObject *)capi_iwk_tmp!=iwk_capi) {
    Py_XDECREF(capi_iwk_tmp); }
  }  /*if (capi_iwk_tmp == NULL) ... else of iwk*/
  /* End of cleaning variable iwk */
  if((PyObject *)capi_wk_tmp!=wk_capi) {
    Py_XDECREF(capi_wk_tmp); }
  }  /*if (capi_wk_tmp == NULL) ... else of wk*/
  /* End of cleaning variable wk */
  if((PyObject *)capi_idg_tmp!=idg_capi) {
    Py_XDECREF(capi_idg_tmp); }
  }  /*if (capi_idg_tmp == NULL) ... else of idg*/
  /* End of cleaning variable idg */
  if((PyObject *)capi_g_tmp!=g_capi) {
    Py_XDECREF(capi_g_tmp); }
  }  /*if (capi_g_tmp == NULL) ... else of g*/
  /* End of cleaning variable g */
  if((PyObject *)capi_xu_tmp!=xu_capi) {
    Py_XDECREF(capi_xu_tmp); }
  }  /*if (capi_xu_tmp == NULL) ... else of xu*/
  /* End of cleaning variable xu */
  if((PyObject *)capi_xl_tmp!=xl_capi) {
    Py_XDECREF(capi_xl_tmp); }
  }  /*if (capi_xl_tmp == NULL) ... else of xl*/
  /* End of cleaning variable xl */
  if((PyObject *)capi_xx_tmp!=xx_capi) {
    Py_XDECREF(capi_xx_tmp); }
  }  /*if (capi_xx_tmp == NULL) ... else of xx*/
  /* End of cleaning variable xx */
    CFUNCSMESS("Restoring jmpbuf for `objgrd`.\n");
    cb_objgrd_in_mmfd__user__routines_capi = objgrd_capi;
    Py_DECREF(cb_objgrd_in_mmfd__user__routines_args_capi);
    cb_objgrd_in_mmfd__user__routines_args_capi = objgrd_args_capi;
    cb_objgrd_in_mmfd__user__routines_nofargs = objgrd_nofargs_capi;
    memcpy(&cb_objgrd_in_mmfd__user__routines_jmpbuf,&objgrd_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable objgrd */
    CFUNCSMESS("Restoring jmpbuf for `objfun`.\n");
    cb_objfun_in_mmfd__user__routines_capi = objfun_capi;
    Py_DECREF(cb_objfun_in_mmfd__user__routines_args_capi);
    cb_objfun_in_mmfd__user__routines_args_capi = objfun_args_capi;
    cb_objfun_in_mmfd__user__routines_nofargs = objfun_nofargs_capi;
    memcpy(&cb_objfun_in_mmfd__user__routines_jmpbuf,&objfun_jmpbuf,sizeof(jmp_buf));
  }
  /* End of cleaning variable objfun */
  } /*if (f2py_success) of ngrd*/
  /* End of cleaning variable ngrd */
  } /*if (f2py_success) of nfun*/
  /* End of cleaning variable nfun */
  } /*if (f2py_success) of itrmop*/
  /* End of cleaning variable itrmop */
  } /*if (f2py_success) of itmax*/
  /* End of cleaning variable itmax */
  } /*if (f2py_success) of pmlt*/
  /* End of cleaning variable pmlt */
  } /*if (f2py_success) of thetaz*/
  /* End of cleaning variable thetaz */
  } /*if (f2py_success) of delobj*/
  /* End of cleaning variable delobj */
  } /*if (f2py_success) of dabobj*/
  /* End of cleaning variable dabobj */
  } /*if (f2py_success) of ctmin*/
  /* End of cleaning variable ctmin */
  } /*if (f2py_success) of ct*/
  /* End of cleaning variable ct */
    STRINGFREE(ifile);
  }  /*if (f2py_success) of ifile*/
  /* End of cleaning variable ifile */
  } /*if (f2py_success) of nriwk*/
  /* End of cleaning variable nriwk */
  } /*if (f2py_success) of nrwk*/
  /* End of cleaning variable nrwk */
  } /*if (f2py_success) of obj*/
  /* End of cleaning variable obj */
  } /*if (f2py_success) of ncon*/
  /* End of cleaning variable ncon */
  } /*if (f2py_success) of ndv*/
  /* End of cleaning variable ndv */
  } /*if (f2py_success) of iiprint*/
  /* End of cleaning variable iiprint */
  } /*if (f2py_success) of iioned*/
  /* End of cleaning variable iioned */
  } /*if (f2py_success) of iiopt*/
  /* End of cleaning variable iiopt */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************** end of mmfd ********************************/

/********************************** openunit **********************************/
static char doc_f2py_rout_mmfd_openunit[] = "\
ierror = openunit(unitnum,filename,filestatus,fileaction)\n\nWrapper for ``openunit``.\
\n\nParameters\n----------\n"
"unitnum : input int\n"
"filename : input string(len=-1)\n"
"filestatus : input string(len=-1)\n"
"fileaction : input string(len=-1)\n"
"\nReturns\n-------\n"
"ierror : int";
/* extern void F_FUNC(openunit,OPENUNIT)(int*,string,string,string,int*,size_t,size_t,size_t); */
static PyObject *f2py_rout_mmfd_openunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*,string,string,string,int*,size_t,size_t,size_t)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  string filename = NULL;
  int slen(filename);
  PyObject *filename_capi = Py_None;
  string filestatus = NULL;
  int slen(filestatus);
  PyObject *filestatus_capi = Py_None;
  string fileaction = NULL;
  int slen(fileaction);
  PyObject *fileaction_capi = Py_None;
  int ierror = 0;
  static char *capi_kwlist[] = {"unitnum","filename","filestatus","fileaction",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "OOOO:mmfd.openunit",\
    capi_kwlist,&unitnum_capi,&filename_capi,&filestatus_capi,&fileaction_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"mmfd.openunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
  /* Processing variable filename */
  slen(filename) = -1;
  f2py_success = string_from_pyobj(&filename,&slen(filename),"",filename_capi,"string_from_pyobj failed in converting 2nd argument `filename' of mmfd.openunit to C string");
  if (f2py_success) {
  /* Processing variable filestatus */
  slen(filestatus) = -1;
  f2py_success = string_from_pyobj(&filestatus,&slen(filestatus),"",filestatus_capi,"string_from_pyobj failed in converting 3rd argument `filestatus' of mmfd.openunit to C string");
  if (f2py_success) {
  /* Processing variable fileaction */
  slen(fileaction) = -1;
  f2py_success = string_from_pyobj(&fileaction,&slen(fileaction),"",fileaction_capi,"string_from_pyobj failed in converting 4th argument `fileaction' of mmfd.openunit to C string");
  if (f2py_success) {
  /* Processing variable ierror */
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum,filename,filestatus,fileaction,&ierror,slen(filename),slen(filestatus),slen(fileaction));
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("i",ierror);
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  /* End of cleaning variable ierror */
    STRINGFREE(fileaction);
  }  /*if (f2py_success) of fileaction*/
  /* End of cleaning variable fileaction */
    STRINGFREE(filestatus);
  }  /*if (f2py_success) of filestatus*/
  /* End of cleaning variable filestatus */
    STRINGFREE(filename);
  }  /*if (f2py_success) of filename*/
  /* End of cleaning variable filename */
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of openunit ******************************/

/********************************** pyflush **********************************/
static char doc_f2py_rout_mmfd_pyflush[] = "\
pyflush(unitnum)\n\nWrapper for ``pyflush``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(pyflush,PYFLUSH)(int*); */
static PyObject *f2py_rout_mmfd_pyflush(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:mmfd.pyflush",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"mmfd.pyflush() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/******************************* end of pyflush *******************************/

/********************************* closeunit *********************************/
static char doc_f2py_rout_mmfd_closeunit[] = "\
closeunit(unitnum)\n\nWrapper for ``closeunit``.\
\n\nParameters\n----------\n"
"unitnum : input int";
/* extern void F_FUNC(closeunit,CLOSEUNIT)(int*); */
static PyObject *f2py_rout_mmfd_closeunit(const PyObject *capi_self,
                           PyObject *capi_args,
                           PyObject *capi_keywds,
                           void (*f2py_func)(int*)) {
  PyObject * volatile capi_buildvalue = NULL;
  volatile int f2py_success = 1;
/*decl*/

  int unitnum = 0;
  PyObject *unitnum_capi = Py_None;
  static char *capi_kwlist[] = {"unitnum",NULL};

/*routdebugenter*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_clock();
#endif
  if (!PyArg_ParseTupleAndKeywords(capi_args,capi_keywds,\
    "O:mmfd.closeunit",\
    capi_kwlist,&unitnum_capi))
    return NULL;
/*frompyobj*/
  /* Processing variable unitnum */
    f2py_success = int_from_pyobj(&unitnum,unitnum_capi,"mmfd.closeunit() 1st argument (unitnum) can't be converted to int");
  if (f2py_success) {
/*end of frompyobj*/
#ifdef F2PY_REPORT_ATEXIT
f2py_start_call_clock();
#endif
/*callfortranroutine*/
        (*f2py_func)(&unitnum);
if (PyErr_Occurred())
  f2py_success = 0;
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_call_clock();
#endif
/*end of callfortranroutine*/
    if (f2py_success) {
/*pyobjfrom*/
/*end of pyobjfrom*/
    CFUNCSMESS("Building return value.\n");
    capi_buildvalue = Py_BuildValue("");
/*closepyobjfrom*/
/*end of closepyobjfrom*/
    } /*if (f2py_success) after callfortranroutine*/
/*cleanupfrompyobj*/
  } /*if (f2py_success) of unitnum*/
  /* End of cleaning variable unitnum */
/*end of cleanupfrompyobj*/
  if (capi_buildvalue == NULL) {
/*routdebugfailure*/
  } else {
/*routdebugleave*/
  }
  CFUNCSMESS("Freeing memory.\n");
/*freemem*/
#ifdef F2PY_REPORT_ATEXIT
f2py_stop_clock();
#endif
  return capi_buildvalue;
}
/****************************** end of closeunit ******************************/
/*eof body*/

/******************* See f2py2e/f90mod_rules.py: buildhooks *******************/
/*need_f90modhooks*/

/************** See f2py2e/rules.py: module_rules['modulebody'] **************/

/******************* See f2py2e/common_rules.py: buildhooks *******************/

/*need_commonhooks*/

/**************************** See f2py2e/rules.py ****************************/

static FortranDataDef f2py_routine_defs[] = {
  {"mmfd",-1,{{-1}},0,(char *)F_FUNC(mmfd,MMFD),(f2py_init_func)f2py_rout_mmfd_mmfd,doc_f2py_rout_mmfd_mmfd},
  {"openunit",-1,{{-1}},0,(char *)F_FUNC(openunit,OPENUNIT),(f2py_init_func)f2py_rout_mmfd_openunit,doc_f2py_rout_mmfd_openunit},
  {"pyflush",-1,{{-1}},0,(char *)F_FUNC(pyflush,PYFLUSH),(f2py_init_func)f2py_rout_mmfd_pyflush,doc_f2py_rout_mmfd_pyflush},
  {"closeunit",-1,{{-1}},0,(char *)F_FUNC(closeunit,CLOSEUNIT),(f2py_init_func)f2py_rout_mmfd_closeunit,doc_f2py_rout_mmfd_closeunit},

/*eof routine_defs*/
  {NULL}
};

static PyMethodDef f2py_module_methods[] = {

  {NULL,NULL}
};

#if PY_VERSION_HEX >= 0x03000000
static struct PyModuleDef moduledef = {
  PyModuleDef_HEAD_INIT,
  "mmfd",
  NULL,
  -1,
  f2py_module_methods,
  NULL,
  NULL,
  NULL,
  NULL
};
#endif

#if PY_VERSION_HEX >= 0x03000000
#define RETVAL m
PyMODINIT_FUNC PyInit_mmfd(void) {
#else
#define RETVAL
PyMODINIT_FUNC initmmfd(void) {
#endif
  int i;
  PyObject *m,*d, *s, *tmp;
#if PY_VERSION_HEX >= 0x03000000
  m = mmfd_module = PyModule_Create(&moduledef);
#else
  m = mmfd_module = Py_InitModule("mmfd", f2py_module_methods);
#endif
  Py_TYPE(&PyFortran_Type) = &PyType_Type;
  import_array();
  if (PyErr_Occurred())
    {PyErr_SetString(PyExc_ImportError, "can't initialize module mmfd (failed to import numpy)"); return RETVAL;}
  d = PyModule_GetDict(m);
  s = PyString_FromString("$Revision: $");
  PyDict_SetItemString(d, "__version__", s);
#if PY_VERSION_HEX >= 0x03000000
  s = PyUnicode_FromString(
#else
  s = PyString_FromString(
#endif
    "This module 'mmfd' is auto-generated with f2py (version:2).\nFunctions:\n"
"  mmfd(iiopt,iioned,iiprint,ndv,ncon,xx,xl,xu,obj,g,idg,wk,nrwk,iwk,nriwk,ifile,ct,ctmin,dabobj,delobj,thetaz,pmlt,itmax,itrmop,nfun,ngrd,objfun,objgrd,objfun_extra_args=(),objgrd_extra_args=())\n"
"  ierror = openunit(unitnum,filename,filestatus,fileaction)\n"
"  pyflush(unitnum)\n"
"  closeunit(unitnum)\n"
".");
  PyDict_SetItemString(d, "__doc__", s);
  mmfd_error = PyErr_NewException ("mmfd.error", NULL, NULL);
  Py_DECREF(s);
  for(i=0;f2py_routine_defs[i].name!=NULL;i++) {
    tmp = PyFortranObject_NewAsAttr(&f2py_routine_defs[i]);
    PyDict_SetItemString(d, f2py_routine_defs[i].name, tmp);
    Py_DECREF(tmp);
  }




/*eof initf2pywraphooks*/
/*eof initf90modhooks*/

/*eof initcommonhooks*/


#ifdef F2PY_REPORT_ATEXIT
  if (! PyErr_Occurred())
    on_exit(f2py_report_on_exit,(void*)"mmfd");
#endif

  return RETVAL;
}
#ifdef __cplusplus
}
#endif
