system_name = "Inverted Pendulum Controller"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 10

is_discrete = true
is_hybrid = false

[parameters]
  xform = [-1.0000, -1.6567, 18.6854, 3.4594]

[inputs]
  msgs = ["ipplant_state.msg", "ipmaneuver_output.msg"]

[topics]
  [topics.outputs]
    msg = "ipcontroller_output.msg"
