C     -*- fortran -*-
C     This file is autogenerated with f2py (version:2)
C     It contains Fortran 77 wrappers to fortran functions.

      subroutine f2pyinitngrc(setupfunc)
      external setupfunc
      integer mxgr
      common /ngrc/ mxgr
      call setupfunc(mxgr)
      end

      subroutine f2pyinitwsc(setupfunc)
      external setupfunc
      integer kk
      integer ll
      integer kkk
      integer lll
      integer mxws
      integer mxlws
      common /wsc/ kk,ll,kkk,lll,mxws,mxlws
      call setupfunc(kk,ll,kkk,lll,mxws,mxlws)
      end

      subroutine f2pyinitstatsc(setupfunc)
      external setupfunc
      double precision dnorm
      double precision h
      double precision hjt
      double precision hj
      integer ipeq
      integer k
      integer itn
      integer nft
      integer ngt
      common /statsc/ dnorm,h,hjt,hj,ipeq,k,itn,nft,ngt
      call setupfunc(dnorm,h,hjt,hj,ipeq,k,itn,nft,ngt)
      end

      subroutine f2pyinitdefaultc(setupfunc)
      external setupfunc
      double precision ainfty
      double precision ubd
      integer mlp
      integer mxf
      common /defaultc/ ainfty,ubd,mlp,mxf
      call setupfunc(ainfty,ubd,mlp,mxf)
      end

      subroutine f2pyinitmxm1c(setupfunc)
      external setupfunc
      integer mxm1
      common /mxm1c/ mxm1
      call setupfunc(mxm1)
      end

      subroutine f2pyinitfunctc(setupfunc)
      external setupfunc
      double precision fxd
      double precision alc
      integer m
      integer iph
      integer last1
      integer next1
      integer nx
      integer nx1
      integer nal
      integer nal1
      integer naal
      integer naal1
      integer nxd
      integer nxd1
      integer ncx
      integer ncx1
      integer ncxd
      integer ncxd1
      integer nla1
      common /functc/ fxd,alc,m,iph,last1,next1,nx,nx1,nal,nal1,na
     &al,naal1,nxd,nxd1,ncx,ncx1,ncxd,ncxd1,nla1
      call setupfunc(fxd,alc,m,iph,last1,next1,nx,nx1,nal,nal1,naa
     &l,naal1,nxd,nxd1,ncx,ncx1,ncxd,ncxd1,nla1)
      end

      subroutine f2pyinitinfoc(setupfunc)
      external setupfunc
      double precision rgnorm
      double precision vstep
      integer iter
      integer npv
      integer nfn
      integer ngr
      common /infoc/ rgnorm,vstep,iter,npv,nfn,ngr
      call setupfunc(rgnorm,vstep,iter,npv,nfn,ngr)
      end

      subroutine f2pyinitepsc(setupfunc)
      external setupfunc
      double precision eps
      double precision tol
      double precision emin
      common /epsc/ eps,tol,emin
      call setupfunc(eps,tol,emin)
      end

      subroutine f2pyinitrepc(setupfunc)
      external setupfunc
      double precision sgnf
      integer nrep
      integer npiv
      integer nres
      common /repc/ sgnf,nrep,npiv,nres
      call setupfunc(sgnf,nrep,npiv,nres)
      end

      subroutine f2pyinitmaxac(setupfunc)
      external setupfunc
      integer maxa
      common /maxac/ maxa
      call setupfunc(maxa)
      end


