system_name = "4 Chaser Can Satellite Rejoin Controller"
system_representation = "black box"
system_solver = "Euler"

sampling_frequency = 50

is_discrete = true
is_hybrid = false


[parameters]
    rest_length = 4.0
    kp = 2
    kd = 8

[inputs]
  msgs = [ "satplant_state.msg",
  "satplant_state.msg",
  "satplant_state.msg",
  "satplant_state.msg" ]

[topics]

  [topics.outputs]
      msg = "controller_output.msg"